package fr.pivot.config;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.boot.context.event.ApplicationReadyEvent;
import org.springframework.boot.info.BuildProperties;
import org.springframework.context.event.EventListener;
import org.springframework.core.env.Environment;
import org.springframework.stereotype.Component;

/**
 * Emits a single structured startup log line once the application is fully up (EN04.1):
 * service version, bound HTTP port and active Spring profile(s).
 *
 * <p>Listens for {@link ApplicationReadyEvent} rather than logging in a constructor or
 * {@code @PostConstruct} — the server has finished binding to its port and {@code
 * local.server.port} has been resolved into the {@link Environment} by that point (important
 * when {@code server.port=0}, e.g. random port in some test contexts).
 *
 * <p>{@link BuildProperties} is injected via {@link ObjectProvider} rather than directly: it is
 * only present when {@code target/classes/META-INF/build-info.properties} has been generated by
 * the {@code build-info} execution added to {@code spring-boot-maven-plugin} (bound to the
 * default {@code prepare-package} phase). During {@code mvn test}/{@code mvn verify}'s test
 * phase — which runs before {@code prepare-package} — that file does not exist yet, so the
 * {@link BuildProperties} bean is conditionally absent; falling back to {@code "unknown"} keeps
 * the full Spring context loadable in tests without it.
 */
@Component
public class StartupLogListener {

    private static final Logger LOG = LoggerFactory.getLogger(StartupLogListener.class);

    private final Environment environment;
    private final ObjectProvider<BuildProperties> buildProperties;

    /**
     * Constructs the listener with its collaborators.
     *
     * @param environment     Spring environment — active profiles and the bound server port
     * @param buildProperties provider for the (possibly absent, see class JavaDoc) build metadata
     */
    public StartupLogListener(final Environment environment,
                               final ObjectProvider<BuildProperties> buildProperties) {
        this.environment = environment;
        this.buildProperties = buildProperties;
    }

    /**
     * Logs {@code event=APPLICATION_STARTED} with version/port/profile once the application is
     * ready to serve traffic.
     */
    @EventListener(ApplicationReadyEvent.class)
    public void logStartup() {
        final BuildProperties props = buildProperties.getIfAvailable();
        final String version = props != null ? props.getVersion() : "unknown";
        final String port = environment.getProperty("local.server.port",
                environment.getProperty("server.port", "unknown"));
        final String[] activeProfiles = environment.getActiveProfiles();
        final String profile = activeProfiles.length == 0 ? "default" : String.join(",", activeProfiles);

        LOG.info("event=APPLICATION_STARTED version={} port={} profile={}", version, port, profile);
    }
}
