package fr.pivot.collaboratif.whiteboard.quiz;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;

import java.time.Instant;
import java.util.UUID;

/**
 * JPA entity representing a single participant's answer to a {@link Question} within a
 * {@link QuizSession}.
 *
 * <p>Unlike {@code Vote} (which deliberately stacks — a user may cast several dots on the same
 * card), a quiz answer is unique per {@code (sessionId, questionId, userId)}: a participant may
 * change their selection while the question is {@link QuestionState#OPEN}, which the application
 * layer implements as an upsert against this constraint (see {@code QuizActionService}, backed by
 * {@code uq_quiz_answer_once} in {@code V9__quiz.sql}), not as multiple stacked rows.
 *
 * <p>{@code sessionId}, {@code questionId} and {@code choiceId} all reference rows with
 * {@code ON DELETE CASCADE}: deleting the session, question or choice removes this answer
 * automatically.
 *
 * <p>{@code answeredAt} is pre-provisioned for the speed-bonus scoring (phase 2, not wired by the
 * MVP — the score at reveal is computed purely from correctness).
 */
@Entity
@Table(name = "quiz_answer", schema = "collaboratif")
public class Answer {

    /** Primary key generated by the database via UUID strategy — never client-supplied. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Session this answer belongs to; cascades on session deletion. */
    @Column(name = "session_id", nullable = false, updatable = false)
    private UUID sessionId;

    /** Question this answer targets; cascades on question deletion. */
    @Column(name = "question_id", nullable = false, updatable = false)
    private UUID questionId;

    /** Choice selected by the participant; cascades on choice deletion. */
    @Column(name = "choice_id", nullable = false, updatable = false)
    private UUID choiceId;

    /** The answering user's {@code public.users.id}. */
    @Column(name = "user_id", nullable = false, updatable = false)
    private Long userId;

    /** Timestamp when this answer was created. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** Timestamp used for the speed-bonus scoring, or {@code null} (not wired by MVP, phase 2). */
    @Column(name = "answered_at")
    private Instant answeredAt;

    /** No-arg constructor required by JPA. */
    protected Answer() {
    }

    /**
     * Creates a new answer.
     *
     * @param sessionId  the owning session's UUID
     * @param questionId the targeted question's UUID
     * @param choiceId   the selected choice's UUID
     * @param userId     the answering user's {@code public.users.id}
     * @param now        timestamp used for {@code createdAt}
     */
    public Answer(
            final UUID sessionId,
            final UUID questionId,
            final UUID choiceId,
            final Long userId,
            final Instant now) {
        this.sessionId = sessionId;
        this.questionId = questionId;
        this.choiceId = choiceId;
        this.userId = userId;
        this.createdAt = now;
    }

    /**
     * Sets {@code createdAt} to the current instant before the first insert, when not already set.
     */
    @PrePersist
    public void prePersist() {
        if (this.createdAt == null) {
            this.createdAt = Instant.now();
        }
    }

    /**
     * Returns the answer's unique identifier.
     *
     * @return the UUID
     */
    public UUID getId() {
        return id;
    }

    /**
     * Returns the owning session's identifier.
     *
     * @return the session UUID
     */
    public UUID getSessionId() {
        return sessionId;
    }

    /**
     * Returns the targeted question's identifier.
     *
     * @return the question UUID
     */
    public UUID getQuestionId() {
        return questionId;
    }

    /**
     * Returns the selected choice's identifier.
     *
     * @return the choice UUID
     */
    public UUID getChoiceId() {
        return choiceId;
    }

    /**
     * Returns the answering user's identifier.
     *
     * @return the user id
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * Returns the creation timestamp.
     *
     * @return the {@code createdAt} instant
     */
    public Instant getCreatedAt() {
        return createdAt;
    }

    /**
     * Returns the timestamp used for the speed-bonus scoring.
     *
     * @return the {@code answeredAt} instant, or {@code null} (not wired by MVP)
     */
    public Instant getAnsweredAt() {
        return answeredAt;
    }

    /**
     * Sets the selected choice — the sole mutation this otherwise insert-only entity exposes.
     *
     * <p>⚠️ Lot B1 addition (repositories + DTO, quiz activity): unlike {@code Vote} (which
     * genuinely never mutates — dot-voting stacks rows instead of replacing them), a quiz answer
     * is unique per {@code (sessionId, questionId, userId)} (see class Javadoc,
     * {@code uq_quiz_answer_once}), and the MVP allows a participant to change their selection
     * while the question is still {@code OPEN}. That upsert is implemented by the service layer
     * (lot C1, {@code QuizActionService}) as "load-existing, replace choice, save" rather than
     * "delete, reinsert" — this setter is the minimal surface that makes the replace-in-place
     * path possible without opening up the rest of the entity (no setters on {@code sessionId},
     * {@code questionId} or {@code userId}, which remain immutable for the answer's lifetime).
     *
     * @param choiceId the newly selected choice's UUID
     */
    public void setChoiceId(final UUID choiceId) {
        this.choiceId = choiceId;
    }

    /**
     * Sets the timestamp used for the speed-bonus scoring.
     *
     * <p>⚠️ Lot B1 addition (repositories + DTO, quiz activity) — see {@link #setChoiceId(UUID)}
     * Javadoc for the rationale. Not wired by the MVP scoring (score at reveal is computed purely
     * from correctness), but provisioned alongside {@code setChoiceId} so the service-layer upsert
     * can refresh it consistently once the speed-bonus (phase 2) is implemented, without a further
     * entity edit.
     *
     * @param answeredAt the new {@code answeredAt} instant, or {@code null}
     */
    public void setAnsweredAt(final Instant answeredAt) {
        this.answeredAt = answeredAt;
    }
}
