package fr.pivot.collaboratif.whiteboard.quiz;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.util.UUID;

/**
 * JPA entity representing a single answer choice belonging to a {@link Question}, ordered by
 * {@code position} (0-based) within the question.
 *
 * <p>Choices are composed by the facilitator and persisted atomically with their
 * {@link QuizSession}/{@link Question} on {@code quiz:start} (see {@code QuizActionService}); the
 * MVP does not support editing a choice set after the session has been created — there are
 * deliberately no setters, mirroring the insert-only shape of {@code Vote}.
 *
 * <p>{@code questionId} references a row with {@code ON DELETE CASCADE}: deleting the question
 * removes its choices.
 *
 * <p>⚠️ {@code correct} is the sensitive field of this entity: it must never be exposed through a
 * DTO for a question that is not yet {@link QuestionState#REVEALED} (masking is enforced at the
 * DTO/service layer, not here — see {@code ChoiceResponse} vs {@code ChoiceRevealResponse}). The
 * MVP UI presents a single-correct radio selection, but this entity does not itself constrain the
 * number of {@code correct} choices per question — multi-correct is pre-provisioned for phase 2.
 */
@Entity
@Table(name = "quiz_choice", schema = "collaboratif")
public class Choice {

    /** Primary key generated by the database via UUID strategy — never client-supplied. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Question this choice belongs to; cascades on question deletion. */
    @Column(name = "question_id", nullable = false, updatable = false)
    private UUID questionId;

    /** 0-based ordering position of this choice within its question. */
    @Column(nullable = false)
    private int position;

    /** The choice's label text. */
    @Column(nullable = false, length = 300)
    private String text;

    /** Whether this choice is (one of) the correct answer(s) — never exposed before reveal. */
    @Column(nullable = false)
    private boolean correct;

    /** No-arg constructor required by JPA. */
    protected Choice() {
    }

    /**
     * Creates a new choice.
     *
     * @param questionId the owning question's UUID
     * @param position   the 0-based ordering position within the question
     * @param text       the choice's label text
     * @param correct    whether this choice is (one of) the correct answer(s)
     */
    public Choice(final UUID questionId, final int position, final String text, final boolean correct) {
        this.questionId = questionId;
        this.position = position;
        this.text = text;
        this.correct = correct;
    }

    /**
     * Returns the choice's unique identifier.
     *
     * @return the UUID
     */
    public UUID getId() {
        return id;
    }

    /**
     * Returns the owning question's identifier.
     *
     * @return the question UUID
     */
    public UUID getQuestionId() {
        return questionId;
    }

    /**
     * Returns the 0-based ordering position within the question.
     *
     * @return the position
     */
    public int getPosition() {
        return position;
    }

    /**
     * Returns the choice's label text.
     *
     * @return the text
     */
    public String getText() {
        return text;
    }

    /**
     * Returns whether this choice is (one of) the correct answer(s).
     *
     * <p>⚠️ Callers must never propagate this value into a DTO for a question that is not yet
     * {@link QuestionState#REVEALED}.
     *
     * @return {@code true} if this choice is correct
     */
    public boolean isCorrect() {
        return correct;
    }
}
