package fr.pivot.collaboratif.whiteboard.quiz;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.util.UUID;

/**
 * JPA entity representing a single multiple-choice question belonging to a {@link QuizSession},
 * ordered by {@code position} (0-based) within the session.
 *
 * <p>Questions are composed by the facilitator and persisted atomically with their
 * {@link QuizSession} on {@code quiz:start} (see {@code QuizActionService}); the MVP does not
 * support editing a question set after the session has been created — there are deliberately no
 * setters, mirroring the insert-only shape of {@code Vote}.
 *
 * <p>{@code sessionId} references a row with {@code ON DELETE CASCADE}: deleting the session
 * removes its questions.
 *
 * <p>{@code timeLimitSeconds} is pre-provisioned for the per-question timer (phase 2, not wired
 * by the MVP, which is driven manually by the facilitator).
 */
@Entity
@Table(name = "quiz_question", schema = "collaboratif")
public class Question {

    /** Primary key generated by the database via UUID strategy — never client-supplied. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Session this question belongs to; cascades on session deletion. */
    @Column(name = "session_id", nullable = false, updatable = false)
    private UUID sessionId;

    /** 0-based ordering position of this question within its session. */
    @Column(nullable = false)
    private int position;

    /** The question's prompt text. */
    @Column(nullable = false, length = 500)
    private String text;

    /** Per-question timer duration in seconds, or {@code null} (no timer — MVP default, phase 2). */
    @Column(name = "time_limit_seconds")
    private Integer timeLimitSeconds;

    /** No-arg constructor required by JPA. */
    protected Question() {
    }

    /**
     * Creates a new question.
     *
     * @param sessionId        the owning session's UUID
     * @param position         the 0-based ordering position within the session
     * @param text             the question's prompt text
     * @param timeLimitSeconds the per-question timer duration in seconds, or {@code null}
     */
    public Question(
            final UUID sessionId, final int position, final String text, final Integer timeLimitSeconds) {
        this.sessionId = sessionId;
        this.position = position;
        this.text = text;
        this.timeLimitSeconds = timeLimitSeconds;
    }

    /**
     * Returns the question's unique identifier.
     *
     * @return the UUID
     */
    public UUID getId() {
        return id;
    }

    /**
     * Returns the owning session's identifier.
     *
     * @return the session UUID
     */
    public UUID getSessionId() {
        return sessionId;
    }

    /**
     * Returns the 0-based ordering position within the session.
     *
     * @return the position
     */
    public int getPosition() {
        return position;
    }

    /**
     * Returns the question's prompt text.
     *
     * @return the text
     */
    public String getText() {
        return text;
    }

    /**
     * Returns the per-question timer duration in seconds.
     *
     * @return the time limit in seconds, or {@code null} for no timer
     */
    public Integer getTimeLimitSeconds() {
        return timeLimitSeconds;
    }
}
