package fr.pivot.collaboratif.whiteboard.quiz;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;

import java.time.Instant;
import java.util.UUID;

/**
 * JPA entity representing a facilitator-driven MCQ quiz session over a board (Quiz feature,
 * Kahoot/Klaxoon-style workshop facilitation).
 *
 * <p>Created and closed exclusively over STOMP ({@code quiz:start}/{@code quiz:stop}, see
 * {@code QuizActionService}); its live and last-closed states are additionally exposed read-only
 * over REST ({@code GET /whiteboard/boards/{boardId}/quiz/current|last}, see
 * {@code QuizController}).
 *
 * <p>At most one {@link QuizStatus#ACTIVE} session exists per board at any time — enforced in
 * {@code QuizActionService} and backed by a partial unique index (see {@code V9__quiz.sql}).
 *
 * <p>{@code currentQuestionIndex}/{@code currentState} track the question currently being
 * played: both are {@code null} until the facilitator starts the quiz. The MVP ("Quiz QCM animé
 * par le facilitateur") drives {@code currentState} through {@link QuestionState#OPEN} and
 * {@link QuestionState#REVEALED} only; {@link QuestionState#PENDING}/{@link QuestionState#CLOSED}
 * remain available on the enum for a future per-question lifecycle but are not set by the MVP
 * service layer. {@code timerEndsAt} is pre-provisioned for the per-question auto-advancing timer
 * (phase 2) — the MVP is driven manually by the facilitator and leaves it {@code null}.
 */
@Entity
@Table(name = "quiz_session", schema = "collaboratif")
public class QuizSession {

    /** Primary key generated by the database via UUID strategy — never client-supplied. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Board this session belongs to; cascades on board deletion (FK {@code ON DELETE CASCADE}). */
    @Column(name = "board_id", nullable = false, updatable = false)
    private UUID boardId;

    /** Tenant owning the board this session belongs to — for tenant-scoped queries. */
    @Column(name = "tenant_id", nullable = false, updatable = false)
    private Long tenantId;

    /** Lifecycle status; {@link QuizStatus#ACTIVE} at creation, {@link QuizStatus#CLOSED} on stop. */
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    private QuizStatus status = QuizStatus.ACTIVE;

    /** 0-based position of the question currently {@code OPEN}/{@code REVEALED}, or {@code null}
     * while the quiz has not been started yet. */
    @Column(name = "current_question_index")
    private Integer currentQuestionIndex;

    /** State of the current question ({@code currentQuestionIndex}); {@code null} until started. */
    @Enumerated(EnumType.STRING)
    @Column(name = "current_state", length = 20)
    private QuestionState currentState;

    /** Instant the current question's timer elapses, or {@code null} (no timer — MVP default). */
    @Column(name = "timer_ends_at")
    private Instant timerEndsAt;

    /** Timestamp when this session was started. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** Timestamp when this session was closed, or {@code null} while it is still active. */
    @Column(name = "closed_at")
    private Instant closedAt;

    /** No-arg constructor required by JPA. */
    protected QuizSession() {
    }

    /**
     * Creates a new active quiz session, not yet started (no current question).
     *
     * @param boardId  the owning board's UUID
     * @param tenantId the owning board's tenant id
     * @param now      timestamp used for {@code createdAt}
     */
    public QuizSession(final UUID boardId, final Long tenantId, final Instant now) {
        this.boardId = boardId;
        this.tenantId = tenantId;
        this.createdAt = now;
    }

    /**
     * Sets {@code createdAt} to the current instant before the first insert, when not already set.
     */
    @PrePersist
    public void prePersist() {
        if (this.createdAt == null) {
            this.createdAt = Instant.now();
        }
    }

    /**
     * Returns the session's unique identifier.
     *
     * @return the UUID
     */
    public UUID getId() {
        return id;
    }

    /**
     * Returns the owning board's identifier.
     *
     * @return the board UUID
     */
    public UUID getBoardId() {
        return boardId;
    }

    /**
     * Returns the owning tenant's identifier.
     *
     * @return the tenant id
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * Returns the lifecycle status.
     *
     * @return the status
     */
    public QuizStatus getStatus() {
        return status;
    }

    /**
     * Returns the 0-based position of the question currently in play.
     *
     * @return the current question index, or {@code null} if the quiz has not started
     */
    public Integer getCurrentQuestionIndex() {
        return currentQuestionIndex;
    }

    /**
     * Returns the state of the current question.
     *
     * @return the current question state, or {@code null} if the quiz has not started
     */
    public QuestionState getCurrentState() {
        return currentState;
    }

    /**
     * Returns the instant the current question's timer elapses.
     *
     * @return the timer end instant, or {@code null} for no timer
     */
    public Instant getTimerEndsAt() {
        return timerEndsAt;
    }

    /**
     * Returns the creation timestamp.
     *
     * @return the {@code createdAt} instant
     */
    public Instant getCreatedAt() {
        return createdAt;
    }

    /**
     * Returns the close timestamp.
     *
     * @return the {@code closedAt} instant, or {@code null} while active
     */
    public Instant getClosedAt() {
        return closedAt;
    }

    /**
     * Sets the lifecycle status.
     *
     * @param status the new status
     */
    public void setStatus(final QuizStatus status) {
        this.status = status;
    }

    /**
     * Sets the 0-based position of the question currently in play.
     *
     * @param currentQuestionIndex the new current question index, or {@code null}
     */
    public void setCurrentQuestionIndex(final Integer currentQuestionIndex) {
        this.currentQuestionIndex = currentQuestionIndex;
    }

    /**
     * Sets the state of the current question.
     *
     * @param currentState the new current question state, or {@code null}
     */
    public void setCurrentState(final QuestionState currentState) {
        this.currentState = currentState;
    }

    /**
     * Sets the instant the current question's timer elapses.
     *
     * @param timerEndsAt the new timer end instant, or {@code null} for no timer
     */
    public void setTimerEndsAt(final Instant timerEndsAt) {
        this.timerEndsAt = timerEndsAt;
    }

    /**
     * Sets the close timestamp.
     *
     * @param closedAt the close instant
     */
    public void setClosedAt(final Instant closedAt) {
        this.closedAt = closedAt;
    }
}
