sonar.projectKey=pivot-platform_PIVOT
sonar.organization=pivot-platform
sonar.projectName=PIVOT

# Sources
sonar.sources=backend/src/main/java,frontend/src
sonar.tests=backend/src/test/java

# Java
sonar.java.binaries=backend/target/classes
sonar.java.source=24

# Coverage
sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

# Exclusions
sonar.exclusions=\
  **/generated/**,\
  **/*.spec.ts,\
  **/node_modules/**,\
  backend/src/main/resources/**,\
  frontend/dist/**

sonar.test.exclusions=\
  **/node_modules/**,\
  frontend/dist/**

# Encoding
sonar.sourceEncoding=UTF-8
