package fr.pivot.agilite.retro.action;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;

import java.time.Instant;
import java.time.LocalDate;
import java.util.UUID;

/**
 * JPA entity representing a single action created during a retrospective session's {@link
 * fr.pivot.agilite.retro.session.RetroPhase#ACTION} phase (US20.3.1).
 *
 * <p>{@code tenantId}/{@code teamId} are denormalized from the owning session at creation time
 * (never re-derived through a join) — see {@code V1__schema_init.sql}'s comment on {@code
 * agilite.retro_actions} for why this is required for both {@code GET
 * /retro/teams/{teamId}/actions} and {@code PATCH /retro/actions/{actionId}}, neither of which has
 * a session id in its path.
 */
@Entity
@Table(name = "retro_actions", schema = "agilite")
public class RetroAction {

    /** Primary key generated by the database via UUID strategy. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Owning tenant, denormalized from the session at creation time; never trusted from input. */
    @Column(name = "tenant_id", nullable = false)
    private Long tenantId;

    /** Owning team ({@code public.teams.id}), denormalized from the session at creation time. */
    @Column(name = "team_id", nullable = false)
    private Long teamId;

    /** Session this action was created from; FK to {@code agilite.retro_sessions.id}. */
    @Column(name = "session_id", nullable = false)
    private UUID sessionId;

    /**
     * Optional retrospective card this action originates from; FK to {@code
     * agilite.retro_cards.id}, {@code null} if the action was not created from a specific card.
     */
    @Column(name = "source_card_id")
    private UUID sourceCardId;

    /** Free-text action title (max 200 chars, enforced at the API layer). */
    @Column(name = "title", nullable = false, length = 200)
    private String title;

    /**
     * Optional assignee; {@code public.users.id} of a member of {@link #teamId}, or {@code null}
     * if the action is not yet assigned.
     */
    @Column(name = "owner_user_id")
    private Long ownerUserId;

    /** Optional due date. */
    @Column(name = "due_date")
    private LocalDate dueDate;

    /** Current lifecycle status; defaults to {@link RetroActionStatus#A_FAIRE} on creation. */
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    private RetroActionStatus status = RetroActionStatus.A_FAIRE;

    /** The caller who created this action ({@code public.users.id}) — facilitator or any team member. */
    @Column(name = "created_by_user_id", nullable = false)
    private Long createdByUserId;

    /** Timestamp when the action was first persisted. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** Timestamp of the last update; refreshed automatically before every update. */
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /** No-arg constructor required by JPA. */
    protected RetroAction() {
    }

    /**
     * Full constructor for creating a new action, always in {@link RetroActionStatus#A_FAIRE}.
     *
     * @param tenantId        owning tenant, denormalized from the session
     * @param teamId          owning team, denormalized from the session
     * @param sessionId       the session this action was created from
     * @param sourceCardId    optional source card id, may be {@code null}
     * @param title           the action's title
     * @param ownerUserId     optional assignee, may be {@code null}
     * @param dueDate         optional due date, may be {@code null}
     * @param createdByUserId the creating caller's {@code public.users.id}
     * @param now             timestamp used for both {@code createdAt} and {@code updatedAt}
     */
    public RetroAction(
            final Long tenantId,
            final Long teamId,
            final UUID sessionId,
            final UUID sourceCardId,
            final String title,
            final Long ownerUserId,
            final LocalDate dueDate,
            final Long createdByUserId,
            final Instant now) {
        this.tenantId = tenantId;
        this.teamId = teamId;
        this.sessionId = sessionId;
        this.sourceCardId = sourceCardId;
        this.title = title;
        this.ownerUserId = ownerUserId;
        this.dueDate = dueDate;
        this.status = RetroActionStatus.A_FAIRE;
        this.createdByUserId = createdByUserId;
        this.createdAt = now;
        this.updatedAt = now;
    }

    /**
     * Sets {@code createdAt} and {@code updatedAt} to the current instant before the first
     * insert, when the fields have not already been set.
     */
    @PrePersist
    public void prePersist() {
        Instant now = Instant.now();
        if (this.createdAt == null) {
            this.createdAt = now;
        }
        if (this.updatedAt == null) {
            this.updatedAt = now;
        }
    }

    /**
     * Refreshes {@code updatedAt} to the current instant before every update.
     */
    @PreUpdate
    public void preUpdate() {
        this.updatedAt = Instant.now();
    }

    /**
     * Returns the action's unique identifier.
     *
     * @return the UUID
     */
    public UUID getId() {
        return id;
    }

    /**
     * Returns the tenant identifier.
     *
     * @return the owning tenant's {@code public.tenants.id}
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * Returns the team identifier.
     *
     * @return the owning team's {@code public.teams.id}
     */
    public Long getTeamId() {
        return teamId;
    }

    /**
     * Returns the owning session identifier.
     *
     * @return the session UUID this action was created from
     */
    public UUID getSessionId() {
        return sessionId;
    }

    /**
     * Returns the optional source card identifier.
     *
     * @return the source card's UUID, or {@code null}
     */
    public UUID getSourceCardId() {
        return sourceCardId;
    }

    /**
     * Returns the action's title.
     *
     * @return the title
     */
    public String getTitle() {
        return title;
    }

    /**
     * Returns the optional assignee.
     *
     * @return the assignee's {@code public.users.id}, or {@code null}
     */
    public Long getOwnerUserId() {
        return ownerUserId;
    }

    /**
     * Returns the optional due date.
     *
     * @return the due date, or {@code null}
     */
    public LocalDate getDueDate() {
        return dueDate;
    }

    /**
     * Returns the current lifecycle status.
     *
     * @return the current status
     */
    public RetroActionStatus getStatus() {
        return status;
    }

    /**
     * Sets the current lifecycle status — free transitions between all 4 statuses, no strict
     * state machine (US20.3.1 AC).
     *
     * @param status the new status
     */
    public void setStatus(final RetroActionStatus status) {
        this.status = status;
    }

    /**
     * Returns the creating caller's identifier.
     *
     * @return the creator's {@code public.users.id}
     */
    public Long getCreatedByUserId() {
        return createdByUserId;
    }

    /**
     * Returns the creation timestamp.
     *
     * @return the createdAt instant
     */
    public Instant getCreatedAt() {
        return createdAt;
    }

    /**
     * Returns the last-updated timestamp.
     *
     * @return the updatedAt instant
     */
    public Instant getUpdatedAt() {
        return updatedAt;
    }
}
