package fr.pivot.collaboratif.meetops.booking;

import fr.pivot.collaboratif.meeting.Meeting;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

import java.util.UUID;

/**
 * JPA entity for one participant of a booking-flow {@link Meeting} (US12.4.1) — the raw {@code
 * participant_ref} (e-mail, as carried by the {@code roadmap.event.window.created} event's {@code
 * participants[]}) plus a best-effort, same-tenant resolution to a platform user
 * ({@link #participantUserId}, may be {@code null}).
 *
 * <p><strong>Deliberately not a foreign key to any roadmap/upstream entity</strong> — {@code
 * participant_ref} is a correlation string only, per ADR-006/008 (no cross-module FK). {@code
 * participant_user_id}, when resolved, IS a genuine {@code public.users.id} FK — that identity
 * concept belongs to this platform, not to the upstream roadmap module.
 *
 * <p><strong>RGPD posture</strong> — this table stores only the raw participant reference needed
 * to send the eventual invitation and to resolve organizer/participant authorization; it never
 * stores or logs any calendar/availability detail (see {@code AvailabilityPort}'s Javadoc for the
 * free/busy-only aggregate boundary that keeps this US12.4.1 "RGPD — agrégat only" AC).
 */
@Entity
@Table(name = "meeting_participants", schema = "collaboratif")
public class MeetingParticipant {

    /** Primary key generated by the database via UUID strategy. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Owning meeting. */
    @ManyToOne
    @JoinColumn(name = "meeting_id", nullable = false)
    private Meeting meeting;

    /** Raw participant identifier from the upstream event (typically an e-mail). */
    @Column(name = "participant_ref", nullable = false, length = 320)
    private String participantRef;

    /**
     * Best-effort resolution of {@link #participantRef} to a {@code public.users.id} of the
     * meeting's own tenant, or {@code null} when it does not resolve to a registered account.
     */
    @Column(name = "participant_user_id")
    private Long participantUserId;

    /** No-arg constructor required by JPA. */
    protected MeetingParticipant() {
    }

    /**
     * Full constructor.
     *
     * @param meeting            the owning meeting
     * @param participantRef     the raw participant identifier (e-mail)
     * @param participantUserId  the resolved platform user id, or {@code null}
     */
    public MeetingParticipant(final Meeting meeting, final String participantRef, final Long participantUserId) {
        this.meeting = meeting;
        this.participantRef = participantRef;
        this.participantUserId = participantUserId;
    }

    /**
     * Returns the participant record's unique identifier.
     *
     * @return the UUID
     */
    public UUID getId() {
        return id;
    }

    /**
     * Returns the owning meeting.
     *
     * @return the meeting
     */
    public Meeting getMeeting() {
        return meeting;
    }

    /**
     * Returns the raw participant identifier.
     *
     * @return the participant ref (e-mail)
     */
    public String getParticipantRef() {
        return participantRef;
    }

    /**
     * Returns the resolved platform user id.
     *
     * @return the {@code public.users.id}, or {@code null} if unresolved
     */
    public Long getParticipantUserId() {
        return participantUserId;
    }
}
