package fr.pivot.collaboratif.meetops.booking;

import fr.pivot.collaboratif.meeting.Meeting;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

import java.time.Instant;
import java.util.UUID;

/**
 * JPA entity for a single best-slot-engine candidate persisted against a {@link Meeting}
 * (US12.4.1). {@code rank} 1 is the recommended slot (proposed by default) — a plain integer
 * column, not a separate boolean, per the Gate 1 schema. {@code hasConflict}/{@code
 * conflictReason} surface the "moins mauvais créneau" AC when no fully-available candidate
 * exists in the booking window.
 *
 * <p>Always created/replaced as a batch by {@code BestSlotEngine} + {@code BookingService} —
 * never mutated individually except by the organizer's manual adjustment ({@code PATCH
 * .../meetings/{id}/slot}), which only ever targets an existing row's {@code slotStart}/{@code
 * slotEnd}.
 */
@Entity
@Table(name = "proposed_slots", schema = "collaboratif")
public class ProposedSlot {

    /** Primary key generated by the database via UUID strategy. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Owning meeting. */
    @ManyToOne
    @JoinColumn(name = "meeting_id", nullable = false)
    private Meeting meeting;

    /** Candidate slot start. */
    @Column(name = "slot_start", nullable = false)
    private Instant slotStart;

    /** Candidate slot end. */
    @Column(name = "slot_end", nullable = false)
    private Instant slotEnd;

    /** {@code 1}-based rank within the meeting's candidates — rank 1 is the recommended slot. */
    @Column(nullable = false)
    private int rank;

    /** {@code true} when at least one participant is unavailable on this candidate. */
    @Column(name = "has_conflict", nullable = false)
    private boolean hasConflict;

    /** Human-readable conflict reason, or {@code null} when {@link #hasConflict} is false. */
    @Column(name = "conflict_reason", length = 200)
    private String conflictReason;

    /** Timestamp this candidate was generated. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** No-arg constructor required by JPA. */
    protected ProposedSlot() {
    }

    /**
     * Full constructor.
     *
     * @param meeting         the owning meeting
     * @param slotStart       candidate slot start
     * @param slotEnd         candidate slot end
     * @param rank            {@code 1}-based rank, {@code 1} is recommended
     * @param hasConflict     whether at least one participant is unavailable
     * @param conflictReason  human-readable reason, or {@code null}
     * @param createdAt       generation timestamp
     */
    public ProposedSlot(
            final Meeting meeting, final Instant slotStart, final Instant slotEnd, final int rank,
            final boolean hasConflict, final String conflictReason, final Instant createdAt) {
        this.meeting = meeting;
        this.slotStart = slotStart;
        this.slotEnd = slotEnd;
        this.rank = rank;
        this.hasConflict = hasConflict;
        this.conflictReason = conflictReason;
        this.createdAt = createdAt;
    }

    /**
     * Applies a manual organizer adjustment to this slot's boundaries (US12.4.1 "ajuster
     * manuellement"). Clears any conflict flag — a manual override is an explicit organizer
     * acceptance of the new boundaries.
     *
     * @param slotStart new start
     * @param slotEnd   new end
     */
    public void adjust(final Instant slotStart, final Instant slotEnd) {
        this.slotStart = slotStart;
        this.slotEnd = slotEnd;
        this.hasConflict = false;
        this.conflictReason = null;
    }

    /**
     * Returns the slot's unique identifier.
     *
     * @return the UUID
     */
    public UUID getId() {
        return id;
    }

    /**
     * Returns the owning meeting.
     *
     * @return the meeting
     */
    public Meeting getMeeting() {
        return meeting;
    }

    /**
     * Returns the candidate slot start.
     *
     * @return the slot start
     */
    public Instant getSlotStart() {
        return slotStart;
    }

    /**
     * Returns the candidate slot end.
     *
     * @return the slot end
     */
    public Instant getSlotEnd() {
        return slotEnd;
    }

    /**
     * Returns the {@code 1}-based rank.
     *
     * @return the rank
     */
    public int getRank() {
        return rank;
    }

    /**
     * Returns whether this candidate has a participant availability conflict.
     *
     * @return {@code true} if conflicted
     */
    public boolean isHasConflict() {
        return hasConflict;
    }

    /**
     * Returns the human-readable conflict reason.
     *
     * @return the reason, or {@code null} when not conflicted
     */
    public String getConflictReason() {
        return conflictReason;
    }

    /**
     * Returns the generation timestamp.
     *
     * @return the createdAt instant
     */
    public Instant getCreatedAt() {
        return createdAt;
    }
}
