package fr.pivot.agilite.capacity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;

import java.time.Instant;
import java.time.LocalDate;
import java.util.UUID;

/**
 * JPA entity representing a capacity-planning event (US11.1.1) — a PI Planning, Sprint, Release,
 * or Custom period a team plans capacity against.
 *
 * <p>Deliberately independent of {@code fr.pivot.agilite.pi.PiCycle} (E50 PI Planning, delivered
 * this same sprint) — a {@code PI_PLANNING}-typed event here is a capacity-planning concept, not
 * a Program Increment cycle; no schema coupling between the two modules at this stage (US11.1.1
 * §Architecture). A {@code PI_PLANNING} event never carries its own {@link CapacityEventMember}
 * roster — it aggregates capacity from its {@code SPRINT}/{@code RELEASE}/{@code CUSTOM} children
 * (via {@code parentEventId}) instead (US11.3.1), max depth 2 levels.
 *
 * <p>{@link CapacityEventMember}/{@link CapacityAbsence}/{@link CapacityBurndownEntry} are
 * deliberately NOT mapped as JPA collections here — always loaded directly via their own
 * repositories by {@code eventId}, same posture as {@code fr.pivot.agilite.pi.PiTicket} relative
 * to {@code PiCycle} (avoids an unbounded eager collection on every {@code GET .../events/{id}},
 * and sidesteps the flush-before-response-DTO gotcha hit when adding children to an
 * already-persisted parent's cascade collection).
 */
@Entity
@Table(name = "capacity_event", schema = "agilite")
public class CapacityEvent {

    /** Primary key generated by the database via UUID strategy. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Tenant that owns this event; used for multi-tenant isolation. */
    @Column(name = "tenant_id", nullable = false)
    private Long tenantId;

    /** Owning team's {@code public.teams.id}. */
    @Column(name = "team_id", nullable = false)
    private Long teamId;

    /**
     * The PI Planning event this event is a child of, or {@code null} for a top-level event. Only
     * {@code PI_PLANNING}-typed, parent-less events may be referenced (US11.3.1, max depth 2).
     */
    @Column(name = "parent_event_id")
    private UUID parentEventId;

    /** Event kind — see {@link CapacityEventType}. */
    @Enumerated(EnumType.STRING)
    @Column(name = "type", nullable = false, length = 20)
    private CapacityEventType type;

    /** Human-readable event name; maximum 120 characters enforced at the service layer. */
    @Column(name = "name", nullable = false, length = 120)
    private String name;

    /** Event start date. */
    @Column(name = "start_date", nullable = false)
    private LocalDate startDate;

    /** Event end date; strictly after {@code startDate} (service-layer validated). */
    @Column(name = "end_date", nullable = false)
    private LocalDate endDate;

    /** Optional points-per-day conversion factor (US11.1.2), used to derive {@code netCapacityPoints}. */
    @Column(name = "points_per_day")
    private Double pointsPerDay;

    /** Points committed at sprint planning time (US11.4.1); {@code SPRINT} events only. */
    @Column(name = "committed_points")
    private Integer committedPoints;

    /** Points actually delivered by sprint end (US11.4.1); {@code SPRINT} events only. */
    @Column(name = "completed_points")
    private Integer completedPoints;

    /** User who created this event. */
    @Column(name = "created_by", nullable = false)
    private Long createdBy;

    /** Timestamp when the event was first persisted. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** Timestamp of the last update; refreshed automatically before every update. */
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /** No-arg constructor required by JPA. */
    protected CapacityEvent() {
    }

    /**
     * Full constructor for creating a new capacity event.
     *
     * @param tenantId      owning tenant's {@code public.tenants.id}
     * @param teamId        owning team's {@code public.teams.id}
     * @param parentEventId the parent PI Planning event's id, or {@code null}
     * @param type          the event kind
     * @param name          event name (max 120 chars)
     * @param startDate     event start date
     * @param endDate       event end date
     * @param createdBy     creating user's {@code public.users.id}
     * @param now           timestamp used for both {@code createdAt} and {@code updatedAt}
     */
    public CapacityEvent(
            final Long tenantId,
            final Long teamId,
            final UUID parentEventId,
            final CapacityEventType type,
            final String name,
            final LocalDate startDate,
            final LocalDate endDate,
            final Long createdBy,
            final Instant now) {
        this.tenantId = tenantId;
        this.teamId = teamId;
        this.parentEventId = parentEventId;
        this.type = type;
        this.name = name;
        this.startDate = startDate;
        this.endDate = endDate;
        this.createdBy = createdBy;
        this.createdAt = now;
        this.updatedAt = now;
    }

    /**
     * Sets {@code createdAt} and {@code updatedAt} to the current instant before
     * the first insert, when the fields have not already been set.
     */
    @PrePersist
    public void prePersist() {
        Instant now = Instant.now();
        if (this.createdAt == null) {
            this.createdAt = now;
        }
        if (this.updatedAt == null) {
            this.updatedAt = now;
        }
    }

    /**
     * Refreshes {@code updatedAt} to the current instant before every update.
     */
    @PreUpdate
    public void preUpdate() {
        this.updatedAt = Instant.now();
    }

    /**
     * Returns the event's unique identifier.
     *
     * @return the UUID
     */
    public UUID getId() {
        return id;
    }

    /**
     * Returns the tenant identifier.
     *
     * @return the tenant's {@code public.tenants.id}
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * Returns the owning team's identifier.
     *
     * @return the team's {@code public.teams.id}
     */
    public Long getTeamId() {
        return teamId;
    }

    /**
     * Returns the parent PI Planning event's id, or {@code null}.
     *
     * @return the parent event id, or {@code null}
     */
    public UUID getParentEventId() {
        return parentEventId;
    }

    /**
     * Returns the event kind.
     *
     * @return the type
     */
    public CapacityEventType getType() {
        return type;
    }

    /**
     * Returns the event name.
     *
     * @return the name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the event name.
     *
     * @param name the name to set
     */
    public void setName(final String name) {
        this.name = name;
    }

    /**
     * Returns the event start date.
     *
     * @return the start date
     */
    public LocalDate getStartDate() {
        return startDate;
    }

    /**
     * Sets the event start date.
     *
     * @param startDate the new start date
     */
    public void setStartDate(final LocalDate startDate) {
        this.startDate = startDate;
    }

    /**
     * Returns the event end date.
     *
     * @return the end date
     */
    public LocalDate getEndDate() {
        return endDate;
    }

    /**
     * Sets the event end date.
     *
     * @param endDate the new end date
     */
    public void setEndDate(final LocalDate endDate) {
        this.endDate = endDate;
    }

    /**
     * Returns the points-per-day conversion factor, or {@code null} if unset.
     *
     * @return the points-per-day factor, or {@code null}
     */
    public Double getPointsPerDay() {
        return pointsPerDay;
    }

    /**
     * Sets the points-per-day conversion factor.
     *
     * @param pointsPerDay the new points-per-day factor, or {@code null}
     */
    public void setPointsPerDay(final Double pointsPerDay) {
        this.pointsPerDay = pointsPerDay;
    }

    /**
     * Returns the committed points, or {@code null} if not yet set.
     *
     * @return the committed points, or {@code null}
     */
    public Integer getCommittedPoints() {
        return committedPoints;
    }

    /**
     * Sets the committed points.
     *
     * @param committedPoints the new committed points, or {@code null}
     */
    public void setCommittedPoints(final Integer committedPoints) {
        this.committedPoints = committedPoints;
    }

    /**
     * Returns the completed points, or {@code null} if not yet set.
     *
     * @return the completed points, or {@code null}
     */
    public Integer getCompletedPoints() {
        return completedPoints;
    }

    /**
     * Sets the completed points.
     *
     * @param completedPoints the new completed points, or {@code null}
     */
    public void setCompletedPoints(final Integer completedPoints) {
        this.completedPoints = completedPoints;
    }

    /**
     * Returns the creating user's identifier.
     *
     * @return the creator's {@code public.users.id}
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * Returns the creation timestamp.
     *
     * @return the createdAt instant
     */
    public Instant getCreatedAt() {
        return createdAt;
    }

    /**
     * Returns the last-updated timestamp.
     *
     * @return the updatedAt instant
     */
    public Instant getUpdatedAt() {
        return updatedAt;
    }
}
