package fr.pivot.agilite.capacity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.time.LocalDate;
import java.util.UUID;

/**
 * JPA entity representing a single day's daily-entered "points remaining" value for a {@code
 * SPRINT}-typed {@link CapacityEvent}'s burndown chart (US11.4.2).
 *
 * <p>One row per {@code (eventId, date)} pair — a database-level unique constraint backs the
 * idempotent upsert AC ({@code PUT .../burndown/{date}} replaces rather than duplicates).
 */
@Entity
@Table(name = "capacity_burndown_entry", schema = "agilite")
public class CapacityBurndownEntry {

    /** Primary key generated by the database via UUID strategy. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Owning event's id. */
    @Column(name = "event_id", nullable = false)
    private UUID eventId;

    /** The calendar date this entry was recorded for. */
    @Column(name = "entry_date", nullable = false)
    private LocalDate date;

    /** Points remaining as of this date; expected already validated non-negative. */
    @Column(name = "points_remaining", nullable = false)
    private int pointsRemaining;

    /** No-arg constructor required by JPA. */
    protected CapacityBurndownEntry() {
    }

    /**
     * Full constructor for creating a new burndown entry.
     *
     * @param eventId         the owning event's id
     * @param date            the calendar date this entry is for
     * @param pointsRemaining the points remaining, expected already validated non-negative
     */
    public CapacityBurndownEntry(final UUID eventId, final LocalDate date, final int pointsRemaining) {
        this.eventId = eventId;
        this.date = date;
        this.pointsRemaining = pointsRemaining;
    }

    /**
     * Returns the entry's unique identifier.
     *
     * @return the UUID
     */
    public UUID getId() {
        return id;
    }

    /**
     * Returns the owning event's id.
     *
     * @return the event id
     */
    public UUID getEventId() {
        return eventId;
    }

    /**
     * Returns the calendar date this entry was recorded for.
     *
     * @return the date
     */
    public LocalDate getDate() {
        return date;
    }

    /**
     * Returns the points remaining as of this date.
     *
     * @return the points remaining
     */
    public int getPointsRemaining() {
        return pointsRemaining;
    }

    /**
     * Updates the points remaining (upsert path).
     *
     * @param pointsRemaining the new points remaining, expected already validated non-negative
     */
    public void setPointsRemaining(final int pointsRemaining) {
        this.pointsRemaining = pointsRemaining;
    }
}
