package fr.pivot.agilite.capacity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.time.LocalDate;
import java.util.UUID;

/**
 * JPA entity representing an absence period for a {@link CapacityEventMember} (US11.2.2).
 *
 * <p><strong>RGPD — deliberately carries no reason/category/comment field</strong> (US11.2.2
 * §Architecture, explicit maintainer decision): the EPIC's own RGPD section states data
 * minimisation — only unavailability periods, never reasons or health data. Only {@code
 * dateDebut}/{@code dateFin} are persisted; the request DTO ({@code
 * fr.pivot.agilite.capacity.dto.CreateAbsenceRequest}) declares no {@code motif}/{@code reason}
 * field either, so a legacy/malicious client sending one has nothing to be silently dropped by
 * Jackson deserialization — there is no column to write it to even if it were accepted.
 */
@Entity
@Table(name = "capacity_absence", schema = "agilite")
public class CapacityAbsence {

    /** Primary key generated by the database via UUID strategy. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Owning event member's id. */
    @Column(name = "event_member_id", nullable = false)
    private UUID eventMemberId;

    /** Absence start date, inclusive. */
    @Column(name = "date_debut", nullable = false)
    private LocalDate dateDebut;

    /** Absence end date, inclusive; expected already validated {@code >= dateDebut}. */
    @Column(name = "date_fin", nullable = false)
    private LocalDate dateFin;

    /** No-arg constructor required by JPA. */
    protected CapacityAbsence() {
    }

    /**
     * Full constructor for creating a new absence.
     *
     * @param eventMemberId the owning event member's id
     * @param dateDebut     absence start date (inclusive)
     * @param dateFin       absence end date (inclusive)
     */
    public CapacityAbsence(final UUID eventMemberId, final LocalDate dateDebut, final LocalDate dateFin) {
        this.eventMemberId = eventMemberId;
        this.dateDebut = dateDebut;
        this.dateFin = dateFin;
    }

    /**
     * Returns the absence's unique identifier.
     *
     * @return the UUID
     */
    public UUID getId() {
        return id;
    }

    /**
     * Returns the owning event member's id.
     *
     * @return the event member id
     */
    public UUID getEventMemberId() {
        return eventMemberId;
    }

    /**
     * Returns the absence start date.
     *
     * @return the start date, inclusive
     */
    public LocalDate getDateDebut() {
        return dateDebut;
    }

    /**
     * Returns the absence end date.
     *
     * @return the end date, inclusive
     */
    public LocalDate getDateFin() {
        return dateFin;
    }
}
