package fr.pivot.agilite.capacity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.util.UUID;

/**
 * JPA entity representing a team member's roster row within a {@link CapacityEvent} (US11.2.1).
 *
 * <p>Auto-seeded once, at event creation, from the owning team's current roster ({@code
 * SPRINT}/{@code RELEASE}/{@code CUSTOM} events only — see {@code CapacityEvent}'s Javadoc) —
 * this US covers consulting/adjusting that already-fixed roster, never adding/removing a member
 * from it. {@code name} is a denormalized snapshot (same precedent as {@code
 * StandupParticipant.name}/{@code fr.pivot.agilite.pi.PiCycleTeam.name}) so a later departure
 * from the team never breaks the event's historical roster. Plain {@code eventId} FK column, not
 * a JPA {@code @ManyToOne}/collection — always loaded directly via {@code
 * CapacityEventMemberRepository} by {@code eventId}, same posture as {@code
 * fr.pivot.agilite.pi.PiTicket} relative to {@code PiCycle}.
 */
@Entity
@Table(name = "capacity_event_member", schema = "agilite")
public class CapacityEventMember {

    /** Default availability percentage assigned at auto-seed time. */
    public static final int DEFAULT_AVAILABILITY_PERCENT = 100;

    /** Primary key generated by the database via UUID strategy. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Owning event's id. */
    @Column(name = "event_id", nullable = false)
    private UUID eventId;

    /** Source {@code public.team_members.id} this row was seeded from. */
    @Column(name = "team_member_id", nullable = false)
    private Long teamMemberId;

    /** Display name — denormalized snapshot, never re-read from {@code public.team_members}. */
    @Column(name = "name", nullable = false, length = 200)
    private String name;

    /** Availability percentage in {@code [10, 100]}; defaults to {@value #DEFAULT_AVAILABILITY_PERCENT}. */
    @Column(name = "availability_percent", nullable = false)
    private int availabilityPercent;

    /** Whether this member is excluded from capacity calculations while remaining in the roster. */
    @Column(name = "excluded", nullable = false)
    private boolean excluded;

    /** No-arg constructor required by JPA. */
    protected CapacityEventMember() {
    }

    /**
     * Full constructor for auto-seeding a roster row.
     *
     * @param eventId      the owning event's id
     * @param teamMemberId the source {@code public.team_members.id}
     * @param name         the member's resolved display name, denormalized at seed time
     */
    public CapacityEventMember(final UUID eventId, final Long teamMemberId, final String name) {
        this.eventId = eventId;
        this.teamMemberId = teamMemberId;
        this.name = name;
        this.availabilityPercent = DEFAULT_AVAILABILITY_PERCENT;
        this.excluded = false;
    }

    /**
     * Returns the member row's unique identifier.
     *
     * @return the UUID
     */
    public UUID getId() {
        return id;
    }

    /**
     * Returns the owning event's id.
     *
     * @return the event id
     */
    public UUID getEventId() {
        return eventId;
    }

    /**
     * Returns the source {@code public.team_members.id}.
     *
     * @return the team member id
     */
    public Long getTeamMemberId() {
        return teamMemberId;
    }

    /**
     * Returns the denormalized display name.
     *
     * @return the name
     */
    public String getName() {
        return name;
    }

    /**
     * Returns the availability percentage.
     *
     * @return the availability percentage, in {@code [10, 100]}
     */
    public int getAvailabilityPercent() {
        return availabilityPercent;
    }

    /**
     * Sets the availability percentage.
     *
     * @param availabilityPercent the new availability percentage, expected already validated in
     *                            {@code [10, 100]}
     */
    public void setAvailabilityPercent(final int availabilityPercent) {
        this.availabilityPercent = availabilityPercent;
    }

    /**
     * Returns whether this member is excluded from capacity calculations.
     *
     * @return {@code true} if excluded
     */
    public boolean isExcluded() {
        return excluded;
    }

    /**
     * Sets whether this member is excluded from capacity calculations.
     *
     * @param excluded the new exclusion flag
     */
    public void setExcluded(final boolean excluded) {
        this.excluded = excluded;
    }
}
