package fr.pivot.agilite.capacity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.time.LocalDate;
import java.util.UUID;

/**
 * JPA entity representing a tenant-level holiday, manually maintained by a tenant administrator
 * (US11.6.1).
 *
 * <p><strong>Deliberately minimal, in-module replacement for the permanently out-of-scope
 * {@code EN22.3}</strong> (US11.6.1 §Architecture): {@code EN22.3} (calendars/holidays by
 * locality, E22 Roadmap) was not just undelivered but permanently extracted to the separate
 * Pilotage product — this entity is a single flat list per tenant, no multi-locality calendar, no
 * per-member weekend customization.
 */
@Entity
@Table(name = "capacity_holiday", schema = "agilite")
public class CapacityHoliday {

    /** Primary key generated by the database via UUID strategy. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Tenant that owns this holiday; used for multi-tenant isolation. */
    @Column(name = "tenant_id", nullable = false)
    private Long tenantId;

    /** The holiday date. */
    @Column(name = "date", nullable = false)
    private LocalDate date;

    /** Human-readable label; maximum 100 characters enforced at the service layer. */
    @Column(name = "label", nullable = false, length = 100)
    private String label;

    /** No-arg constructor required by JPA. */
    protected CapacityHoliday() {
    }

    /**
     * Full constructor for creating a new holiday.
     *
     * @param tenantId owning tenant's {@code public.tenants.id}
     * @param date     the holiday date
     * @param label    human-readable label (max 100 chars)
     */
    public CapacityHoliday(final Long tenantId, final LocalDate date, final String label) {
        this.tenantId = tenantId;
        this.date = date;
        this.label = label;
    }

    /**
     * Returns the holiday's unique identifier.
     *
     * @return the UUID
     */
    public UUID getId() {
        return id;
    }

    /**
     * Returns the tenant identifier.
     *
     * @return the tenant's {@code public.tenants.id}
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * Returns the holiday date.
     *
     * @return the date
     */
    public LocalDate getDate() {
        return date;
    }

    /**
     * Returns the holiday's label.
     *
     * @return the label
     */
    public String getLabel() {
        return label;
    }
}
