package fr.pivot.agilite.capacity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;

import java.time.Instant;
import java.util.UUID;

/**
 * JPA entity representing one append-only entry of a team's agile-maturity change history
 * (US11.6.4) — never updated or deleted once written.
 */
@Entity
@Table(name = "capacity_team_maturity_history", schema = "agilite")
public class CapacityTeamMaturityHistory {

    /** Primary key generated by the database via UUID strategy. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Tenant that owns this row; used for multi-tenant isolation. */
    @Column(name = "tenant_id", nullable = false)
    private Long tenantId;

    /** The team this change applies to. */
    @Column(name = "team_id", nullable = false)
    private Long teamId;

    /** The maturity tier before this change, or {@code null} if this is the first entry. */
    @Enumerated(EnumType.STRING)
    @Column(name = "previous_maturity", length = 20)
    private CapacityMaturityLevel previousMaturity;

    /** The maturity tier after this change. */
    @Enumerated(EnumType.STRING)
    @Column(name = "new_maturity", nullable = false, length = 20)
    private CapacityMaturityLevel newMaturity;

    /** Timestamp when this change was recorded. */
    @Column(name = "changed_at", nullable = false)
    private Instant changedAt;

    /** User who made this change. */
    @Column(name = "changed_by", nullable = false)
    private Long changedBy;

    /** No-arg constructor required by JPA. */
    protected CapacityTeamMaturityHistory() {
    }

    /**
     * Full constructor for recording a new maturity change.
     *
     * @param tenantId         owning tenant's {@code public.tenants.id}
     * @param teamId           the team's {@code public.teams.id}
     * @param previousMaturity the tier before this change, or {@code null} if this is the first
     * @param newMaturity      the tier after this change
     * @param changedBy        the changing user's {@code public.users.id}
     */
    public CapacityTeamMaturityHistory(
            final Long tenantId,
            final Long teamId,
            final CapacityMaturityLevel previousMaturity,
            final CapacityMaturityLevel newMaturity,
            final Long changedBy) {
        this.tenantId = tenantId;
        this.teamId = teamId;
        this.previousMaturity = previousMaturity;
        this.newMaturity = newMaturity;
        this.changedBy = changedBy;
    }

    /**
     * Sets {@code changedAt} before the first insert.
     */
    @PrePersist
    public void prePersist() {
        this.changedAt = Instant.now();
    }

    /**
     * Returns the row's unique identifier.
     *
     * @return the UUID
     */
    public UUID getId() {
        return id;
    }

    /**
     * Returns the team identifier.
     *
     * @return the team's {@code public.teams.id}
     */
    public Long getTeamId() {
        return teamId;
    }

    /**
     * Returns the maturity tier before this change, or {@code null}.
     *
     * @return the previous maturity, or {@code null}
     */
    public CapacityMaturityLevel getPreviousMaturity() {
        return previousMaturity;
    }

    /**
     * Returns the maturity tier after this change.
     *
     * @return the new maturity
     */
    public CapacityMaturityLevel getNewMaturity() {
        return newMaturity;
    }

    /**
     * Returns the timestamp when this change was recorded.
     *
     * @return the changedAt instant
     */
    public Instant getChangedAt() {
        return changedAt;
    }

    /**
     * Returns the changing user's identifier.
     *
     * @return the changer's {@code public.users.id}
     */
    public Long getChangedBy() {
        return changedBy;
    }
}
