package fr.pivot.agilite.capacity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;

import java.time.Instant;
import java.util.UUID;

/**
 * JPA entity representing a team's current agile-maturity tier (US11.6.4) — one row per team,
 * unique on {@code teamId}. Change history is tracked separately in {@link
 * CapacityTeamMaturityHistory}, appended by {@link CapacityTeamMaturityService}.
 */
@Entity
@Table(name = "capacity_team_maturity", schema = "agilite")
public class CapacityTeamMaturity {

    /** Primary key generated by the database via UUID strategy. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Tenant that owns this row; used for multi-tenant isolation. */
    @Column(name = "tenant_id", nullable = false)
    private Long tenantId;

    /** The team this maturity tier applies to; unique. */
    @Column(name = "team_id", nullable = false)
    private Long teamId;

    /** The team's current maturity tier. */
    @Enumerated(EnumType.STRING)
    @Column(name = "maturity", nullable = false, length = 20)
    private CapacityMaturityLevel maturity;

    /** Timestamp of the last update. */
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /** User who last updated this row. */
    @Column(name = "updated_by", nullable = false)
    private Long updatedBy;

    /** No-arg constructor required by JPA. */
    protected CapacityTeamMaturity() {
    }

    /**
     * Full constructor for creating a new team-maturity row.
     *
     * @param tenantId  owning tenant's {@code public.tenants.id}
     * @param teamId    the team's {@code public.teams.id}
     * @param maturity  the initial maturity tier
     * @param updatedBy the updating user's {@code public.users.id}
     */
    public CapacityTeamMaturity(final Long tenantId, final Long teamId, final CapacityMaturityLevel maturity, final Long updatedBy) {
        this.tenantId = tenantId;
        this.teamId = teamId;
        this.maturity = maturity;
        this.updatedBy = updatedBy;
    }

    /**
     * Sets {@code updatedAt} before the first insert.
     */
    @PrePersist
    public void prePersist() {
        this.updatedAt = Instant.now();
    }

    /**
     * Refreshes {@code updatedAt} before every update.
     */
    @PreUpdate
    public void preUpdate() {
        this.updatedAt = Instant.now();
    }

    /**
     * Returns the row's unique identifier.
     *
     * @return the UUID
     */
    public UUID getId() {
        return id;
    }

    /**
     * Returns the tenant identifier.
     *
     * @return the tenant's {@code public.tenants.id}
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * Returns the team identifier.
     *
     * @return the team's {@code public.teams.id}
     */
    public Long getTeamId() {
        return teamId;
    }

    /**
     * Returns the current maturity tier.
     *
     * @return the maturity tier
     */
    public CapacityMaturityLevel getMaturity() {
        return maturity;
    }

    /**
     * Sets the current maturity tier.
     *
     * @param maturity the new maturity tier
     */
    public void setMaturity(final CapacityMaturityLevel maturity) {
        this.maturity = maturity;
        this.updatedAt = Instant.now();
    }

    /**
     * Returns the last-update timestamp.
     *
     * @return the updatedAt instant
     */
    public Instant getUpdatedAt() {
        return updatedAt;
    }

    /**
     * Returns the last-updating user's identifier.
     *
     * @return the updater's {@code public.users.id}
     */
    public Long getUpdatedBy() {
        return updatedBy;
    }

    /**
     * Sets the last-updating user's identifier.
     *
     * @param updatedBy the updater's {@code public.users.id}
     */
    public void setUpdatedBy(final Long updatedBy) {
        this.updatedBy = updatedBy;
    }
}
