package fr.pivot.agilite.capacity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;

import java.time.Instant;
import java.time.LocalDate;
import java.util.UUID;

/**
 * JPA entity representing a capacity-planning event (US11.1.1) — a PI Planning, Sprint, Release,
 * or Custom period a team plans capacity against.
 *
 * <p>Deliberately independent of {@code fr.pivot.agilite.pi.PiCycle} (E50 PI Planning, delivered
 * this same sprint) — a {@code PI_PLANNING}-typed event here is a capacity-planning concept, not
 * a Program Increment cycle; no schema coupling between the two modules at this stage (US11.1.1
 * §Architecture). A {@code PI_PLANNING} event never carries its own {@link CapacityEventMember}
 * roster — it aggregates capacity from its {@code SPRINT}/{@code RELEASE}/{@code CUSTOM} children
 * (via {@code parentEventId}) instead (US11.3.1), max depth 2 levels.
 *
 * <p>{@link CapacityEventMember}/{@link CapacityAbsence}/{@link CapacityBurndownEntry} are
 * deliberately NOT mapped as JPA collections here — always loaded directly via their own
 * repositories by {@code eventId}, same posture as {@code fr.pivot.agilite.pi.PiTicket} relative
 * to {@code PiCycle} (avoids an unbounded eager collection on every {@code GET .../events/{id}},
 * and sidesteps the flush-before-response-DTO gotcha hit when adding children to an
 * already-persisted parent's cascade collection).
 */
@Entity
@Table(name = "capacity_event", schema = "agilite")
public class CapacityEvent {

    /** Primary key generated by the database via UUID strategy. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Tenant that owns this event; used for multi-tenant isolation. */
    @Column(name = "tenant_id", nullable = false)
    private Long tenantId;

    /** Owning team's {@code public.teams.id}. */
    @Column(name = "team_id", nullable = false)
    private Long teamId;

    /**
     * The PI Planning event this event is a child of, or {@code null} for a top-level event. Only
     * {@code PI_PLANNING}-typed, parent-less events may be referenced (US11.3.1, max depth 2).
     */
    @Column(name = "parent_event_id")
    private UUID parentEventId;

    /** Event kind — see {@link CapacityEventType}. */
    @Enumerated(EnumType.STRING)
    @Column(name = "type", nullable = false, length = 20)
    private CapacityEventType type;

    /** Human-readable event name; maximum 120 characters enforced at the service layer. */
    @Column(name = "name", nullable = false, length = 120)
    private String name;

    /** Event start date. */
    @Column(name = "start_date", nullable = false)
    private LocalDate startDate;

    /** Event end date; strictly after {@code startDate} (service-layer validated). */
    @Column(name = "end_date", nullable = false)
    private LocalDate endDate;

    /** Optional points-per-day conversion factor (US11.1.2), used to derive {@code netCapacityPoints}. */
    @Column(name = "points_per_day")
    private Double pointsPerDay;

    /**
     * Marks a {@code SPRINT} child of a {@code PI_PLANNING} parent as the IP iteration (US11.5.1)
     * — excluded from that parent's aggregated capacity. Ignored (no effect, never an error) on
     * any other event: a top-level event, or a child of an {@code INCREMENT} parent.
     */
    @Column(name = "is_ip_iteration", nullable = false)
    private boolean isIpIteration;

    /**
     * Event-level focus-factor override in {@code [10, 100]} (US11.6.2), or {@code null} to fall
     * back to the owning team's maturity-derived default, then the global 70% default
     * (US11.6.4) — resolution centralized in {@code CapacitySummaryService}, never duplicated.
     */
    @Column(name = "focus_factor_percent")
    private Integer focusFactorPercent;

    /** Points committed at sprint planning time (US11.4.1); {@code SPRINT} events only. */
    @Column(name = "committed_points")
    private Integer committedPoints;

    /** Points actually delivered by sprint end (US11.4.1); {@code SPRINT} events only. */
    @Column(name = "completed_points")
    private Integer completedPoints;

    /** User who created this event. */
    @Column(name = "created_by", nullable = false)
    private Long createdBy;

    /** Timestamp when the event was first persisted. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** Timestamp of the last update; refreshed automatically before every update. */
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /** No-arg constructor required by JPA. */
    protected CapacityEvent() {
    }

    /**
     * Constructor for creating a new top-level capacity event (no parent) — {@code
     * parentEventId} is set separately via {@link #setParentEventId} for child events, keeping
     * this constructor within the 7-parameter limit. {@code createdAt}/{@code updatedAt} are
     * left to {@link #prePersist}, which always fires on the first insert.
     *
     * @param tenantId  owning tenant's {@code public.tenants.id}
     * @param teamId    owning team's {@code public.teams.id}
     * @param type      the event kind
     * @param name      event name (max 120 chars)
     * @param startDate event start date
     * @param endDate   event end date
     * @param createdBy creating user's {@code public.users.id}
     */
    public CapacityEvent(
            final Long tenantId,
            final Long teamId,
            final CapacityEventType type,
            final String name,
            final LocalDate startDate,
            final LocalDate endDate,
            final Long createdBy) {
        this.tenantId = tenantId;
        this.teamId = teamId;
        this.type = type;
        this.name = name;
        this.startDate = startDate;
        this.endDate = endDate;
        this.createdBy = createdBy;
    }

    /**
     * Sets {@code createdAt} and {@code updatedAt} to the current instant before
     * the first insert, when the fields have not already been set.
     */
    @PrePersist
    public void prePersist() {
        Instant now = Instant.now();
        if (this.createdAt == null) {
            this.createdAt = now;
        }
        if (this.updatedAt == null) {
            this.updatedAt = now;
        }
    }

    /**
     * Refreshes {@code updatedAt} to the current instant before every update.
     */
    @PreUpdate
    public void preUpdate() {
        this.updatedAt = Instant.now();
    }

    /**
     * Returns the event's unique identifier.
     *
     * @return the UUID
     */
    public UUID getId() {
        return id;
    }

    /**
     * Returns the tenant identifier.
     *
     * @return the tenant's {@code public.tenants.id}
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * Returns the owning team's identifier.
     *
     * @return the team's {@code public.teams.id}
     */
    public Long getTeamId() {
        return teamId;
    }

    /**
     * Returns the parent PI Planning event's id, or {@code null}.
     *
     * @return the parent event id, or {@code null}
     */
    public UUID getParentEventId() {
        return parentEventId;
    }

    /**
     * Sets the parent PI Planning event's id — called once, right after construction, for a
     * child ({@code SPRINT}/{@code RELEASE}/{@code CUSTOM}) event (US11.3.1); left {@code null}
     * for a top-level event.
     *
     * @param parentEventId the parent event's id, or {@code null}
     */
    public void setParentEventId(final UUID parentEventId) {
        this.parentEventId = parentEventId;
    }

    /**
     * Returns the event kind.
     *
     * @return the type
     */
    public CapacityEventType getType() {
        return type;
    }

    /**
     * Returns the event name.
     *
     * @return the name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the event name.
     *
     * @param name the name to set
     */
    public void setName(final String name) {
        this.name = name;
    }

    /**
     * Returns the event start date.
     *
     * @return the start date
     */
    public LocalDate getStartDate() {
        return startDate;
    }

    /**
     * Sets the event start date.
     *
     * @param startDate the new start date
     */
    public void setStartDate(final LocalDate startDate) {
        this.startDate = startDate;
    }

    /**
     * Returns the event end date.
     *
     * @return the end date
     */
    public LocalDate getEndDate() {
        return endDate;
    }

    /**
     * Sets the event end date.
     *
     * @param endDate the new end date
     */
    public void setEndDate(final LocalDate endDate) {
        this.endDate = endDate;
    }

    /**
     * Returns the points-per-day conversion factor, or {@code null} if unset.
     *
     * @return the points-per-day factor, or {@code null}
     */
    public Double getPointsPerDay() {
        return pointsPerDay;
    }

    /**
     * Sets the points-per-day conversion factor.
     *
     * @param pointsPerDay the new points-per-day factor, or {@code null}
     */
    public void setPointsPerDay(final Double pointsPerDay) {
        this.pointsPerDay = pointsPerDay;
    }

    /**
     * Returns whether this event is the IP iteration of its {@code PI_PLANNING} parent.
     *
     * @return {@code true} if flagged as the IP iteration
     */
    public boolean isIpIteration() {
        return isIpIteration;
    }

    /**
     * Sets the IP-iteration flag — accepted unconditionally (US11.5.1: meaningful only for a
     * {@code SPRINT} child of a {@code PI_PLANNING} parent, silently without effect otherwise).
     *
     * @param ipIteration the new flag value
     */
    public void setIpIteration(final boolean ipIteration) {
        this.isIpIteration = ipIteration;
    }

    /**
     * Returns the event-level focus-factor override, or {@code null} if unset.
     *
     * @return the focus-factor percentage, {@code [10, 100]}, or {@code null}
     */
    public Integer getFocusFactorPercent() {
        return focusFactorPercent;
    }

    /**
     * Sets the event-level focus-factor override.
     *
     * @param focusFactorPercent the new focus-factor percentage, expected already validated in
     *                           {@code [10, 100]}, or {@code null} to clear the override
     */
    public void setFocusFactorPercent(final Integer focusFactorPercent) {
        this.focusFactorPercent = focusFactorPercent;
    }

    /**
     * Returns the committed points, or {@code null} if not yet set.
     *
     * @return the committed points, or {@code null}
     */
    public Integer getCommittedPoints() {
        return committedPoints;
    }

    /**
     * Sets the committed points.
     *
     * @param committedPoints the new committed points, or {@code null}
     */
    public void setCommittedPoints(final Integer committedPoints) {
        this.committedPoints = committedPoints;
    }

    /**
     * Returns the completed points, or {@code null} if not yet set.
     *
     * @return the completed points, or {@code null}
     */
    public Integer getCompletedPoints() {
        return completedPoints;
    }

    /**
     * Sets the completed points.
     *
     * @param completedPoints the new completed points, or {@code null}
     */
    public void setCompletedPoints(final Integer completedPoints) {
        this.completedPoints = completedPoints;
    }

    /**
     * Returns the creating user's identifier.
     *
     * @return the creator's {@code public.users.id}
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * Returns the creation timestamp.
     *
     * @return the createdAt instant
     */
    public Instant getCreatedAt() {
        return createdAt;
    }

    /**
     * Returns the last-updated timestamp.
     *
     * @return the updatedAt instant
     */
    public Instant getUpdatedAt() {
        return updatedAt;
    }
}
