package fr.pivot.agilite.capacity.cadence;

import fr.pivot.agilite.capacity.CapacityEvent;
import fr.pivot.agilite.capacity.CapacityEventStatus;

import java.time.LocalDate;
import java.util.UUID;

/**
 * Response shape for a single sprint generated by {@code POST
 * /capacity/events/{piId}/cadence} (F11.5) — deliberately carries the {@code ipSprint} flag,
 * which the shared {@code CapacityEventChildResponse} (F11.3) does not expose, since asserting it
 * is the whole point of the SAFe cadence feature.
 *
 * @param id        unique identifier of the generated sprint event
 * @param status    the generated sprint's lifecycle status, always {@code PLANNING}
 * @param name      the generated sprint's display name
 * @param startDate the generated sprint's first calendar day (inclusive)
 * @param endDate   the generated sprint's last calendar day (inclusive)
 * @param ipSprint  {@code true} if this is the trailing SAFe Innovation &amp; Planning sprint
 */
public record CadenceSprintResponse(
        UUID id,
        CapacityEventStatus status,
        String name,
        LocalDate startDate,
        LocalDate endDate,
        boolean ipSprint) {

    /**
     * Factory method that creates a {@link CadenceSprintResponse} from a persisted {@link
     * CapacityEvent}.
     *
     * @param event the generated sprint event entity
     * @return a populated response record
     */
    public static CadenceSprintResponse from(final CapacityEvent event) {
        return new CadenceSprintResponse(
                event.getId(),
                event.getStatus(),
                event.getName(),
                event.getStartDate(),
                event.getEndDate(),
                event.isIpSprint());
    }
}
