package fr.pivot.collaboratif.session.poll;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.time.Instant;
import java.util.UUID;

/**
 * A single participant's active vote on a POLL-type session (US19.3.2) — one row per
 * {@code (sessionId, participantId)}, upserted on re-vote while the session is {@code LIVE}.
 *
 * <p>{@code optionIds} is a JSONB array of {@link SessionPollOption#getId()} values — one element
 * for single-choice, N for {@code allowMultiple} — avoiding a separate join table for what is
 * always read/written as a single unit.
 */
@Entity
@Table(name = "session_poll_vote", schema = "collaboratif")
public class SessionPollVote {

    /** Primary key generated by the database via UUID strategy — never client-supplied. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Owning session; cascades on session deletion. */
    @Column(name = "session_id", nullable = false, updatable = false)
    private UUID sessionId;

    /** The voting participant; cascades on participant deletion. */
    @Column(name = "participant_id", nullable = false, updatable = false)
    private UUID participantId;

    /** Selected option ids, stored as a JSONB array of UUID strings. */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "option_ids", nullable = false, columnDefinition = "jsonb")
    private String optionIds;

    /** Timestamp of the most recent submission of this vote. */
    @Column(name = "submitted_at", nullable = false)
    private Instant submittedAt;

    /** No-arg constructor required by JPA. */
    protected SessionPollVote() {
    }

    /**
     * Creates a new vote.
     *
     * @param sessionId     the owning session's UUID
     * @param participantId the voting participant's UUID
     * @param optionIds     selected option ids, as a JSON array string
     * @param now           the submission timestamp
     */
    public SessionPollVote(
            final UUID sessionId, final UUID participantId, final String optionIds, final Instant now) {
        this.sessionId = sessionId;
        this.participantId = participantId;
        this.optionIds = optionIds;
        this.submittedAt = now;
    }

    /**
     * Sets {@code submittedAt} before the first insert, when not already set.
     */
    @PrePersist
    public void prePersist() {
        if (this.submittedAt == null) {
            this.submittedAt = Instant.now();
        }
    }

    /**
     * Replaces the selected options and refreshes the submission timestamp (re-vote).
     *
     * @param optionIds the new selected option ids, as a JSON array string
     * @param now       the new submission timestamp
     */
    public void replace(final String optionIds, final Instant now) {
        this.optionIds = optionIds;
        this.submittedAt = now;
    }

    /**
     * Returns the vote's unique identifier.
     *
     * @return the UUID
     */
    public UUID getId() {
        return id;
    }

    /**
     * Returns the owning session's identifier.
     *
     * @return the session UUID
     */
    public UUID getSessionId() {
        return sessionId;
    }

    /**
     * Returns the voting participant's identifier.
     *
     * @return the participant UUID
     */
    public UUID getParticipantId() {
        return participantId;
    }

    /**
     * Returns the selected option ids as a JSON array string.
     *
     * @return the raw JSON array of option ids
     */
    public String getOptionIds() {
        return optionIds;
    }

    /**
     * Returns the timestamp of the most recent submission.
     *
     * @return the submittedAt instant
     */
    public Instant getSubmittedAt() {
        return submittedAt;
    }
}
