package fr.pivot.collaboratif.session.poll;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.util.UUID;

/**
 * A single answer option of a POLL-type session's active poll (US19.3.2), 2-8 rows per session.
 */
@Entity
@Table(name = "session_poll_option", schema = "collaboratif")
public class SessionPollOption {

    /** Primary key generated by the database via UUID strategy — never client-supplied. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Owning session; cascades on session deletion. */
    @Column(name = "session_id", nullable = false, updatable = false)
    private UUID sessionId;

    /** Display label of this option. */
    @Column(nullable = false, length = 200)
    private String label;

    /** 0-based display order among the session's options. */
    @Column(name = "sort_order", nullable = false)
    private int sortOrder;

    /** No-arg constructor required by JPA. */
    protected SessionPollOption() {
    }

    /**
     * Creates a poll option.
     *
     * @param sessionId the owning session's UUID
     * @param label     the option's display label
     * @param sortOrder the 0-based display order
     */
    public SessionPollOption(final UUID sessionId, final String label, final int sortOrder) {
        this.sessionId = sessionId;
        this.label = label;
        this.sortOrder = sortOrder;
    }

    /**
     * Returns the option's unique identifier.
     *
     * @return the UUID
     */
    public UUID getId() {
        return id;
    }

    /**
     * Returns the owning session's identifier.
     *
     * @return the session UUID
     */
    public UUID getSessionId() {
        return sessionId;
    }

    /**
     * Returns the option's display label.
     *
     * @return the label
     */
    public String getLabel() {
        return label;
    }

    /**
     * Returns the 0-based display order.
     *
     * @return the sort order
     */
    public int getSortOrder() {
        return sortOrder;
    }
}
