package fr.pivot.collaboratif.meeting.report;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.time.Instant;
import java.util.UUID;

/**
 * JPA entity for the frozen compte-rendu snapshot written once, at meeting closure (US12.3.1) —
 * backed by {@code collaboratif.meeting_report} (V19), one row per meeting ({@code meeting_id}
 * {@code UNIQUE}).
 *
 * <p>{@link #content} holds the full {@link MeetingReportDto} serialized as JSON — the exact
 * value {@code GET .../report} returns, unchanged, for every subsequent read of a closed meeting
 * (AC Security — immutability: a later edit to a decision/action, US12.3.2, never touches this
 * row). {@link #actualDurationSeconds} is denormalized out of that JSON purely so it can be
 * queried/reported on directly without a JSON parse, mirroring the DTO's own field of the same
 * name captured at freeze time.
 *
 * <p>{@code content} uses the same {@code @JdbcTypeCode(SqlTypes.JSON)} String-backed JSONB
 * mapping as {@code fr.pivot.collaboratif.whiteboard.canvas.Card#meta} — a plain Java
 * {@code String} column, serialized/deserialized by the caller ({@code MeetingReportService})
 * via the auto-configured {@code ObjectMapper}, not a typed JPA converter.
 */
@Entity
@Table(name = "meeting_report", schema = "collaboratif")
public class MeetingReportSnapshot {

    /** Primary key generated by the database via identity/sequence strategy ({@code BIGSERIAL}). */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** The meeting this snapshot was frozen for; unique — one frozen report per meeting. */
    @Column(name = "meeting_id", nullable = false, updatable = false, unique = true)
    private UUID meetingId;

    /** Tenant that owns this snapshot; denormalized for isolation-filtered queries. */
    @Column(name = "tenant_id", nullable = false, updatable = false)
    private Long tenantId;

    /** The full {@link MeetingReportDto}, serialized as JSON, frozen at closure. */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(nullable = false)
    private String content;

    /** Whole-meeting actual duration in seconds, denormalized from {@link #content}. */
    @Column(name = "actual_duration_seconds")
    private Integer actualDurationSeconds;

    /** The {@code public.users.id} of the organizer/admin who closed the meeting. */
    @Column(name = "generated_by", nullable = false, updatable = false)
    private Long generatedBy;

    /** Timestamp this snapshot was frozen. */
    @Column(name = "generated_at", nullable = false, updatable = false)
    private Instant generatedAt;

    /** No-arg constructor required by JPA. */
    protected MeetingReportSnapshot() {
    }

    /**
     * Full constructor for freezing a new snapshot (US12.3.1) — a row is only ever inserted, never
     * updated afterward (immutability, AC Security).
     *
     * @param meetingId              the meeting being closed
     * @param tenantId               the meeting's tenant
     * @param content                the full {@link MeetingReportDto}, serialized as JSON
     * @param actualDurationSeconds  whole-meeting actual duration in seconds, or {@code null}
     * @param generatedBy            the closing organizer/admin's {@code public.users.id}
     * @param generatedAt            the freeze instant
     */
    public MeetingReportSnapshot(
            final UUID meetingId, final Long tenantId, final String content,
            final Integer actualDurationSeconds, final Long generatedBy, final Instant generatedAt) {
        this.meetingId = meetingId;
        this.tenantId = tenantId;
        this.content = content;
        this.actualDurationSeconds = actualDurationSeconds;
        this.generatedBy = generatedBy;
        this.generatedAt = generatedAt;
    }

    /**
     * Returns this snapshot's primary key.
     *
     * @return the id
     */
    public Long getId() {
        return id;
    }

    /**
     * Returns the meeting this snapshot was frozen for.
     *
     * @return the meeting's UUID
     */
    public UUID getMeetingId() {
        return meetingId;
    }

    /**
     * Returns the owning tenant.
     *
     * @return the tenant's {@code public.tenants.id}
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * Returns the serialized report content.
     *
     * @return the JSON content
     */
    public String getContent() {
        return content;
    }

    /**
     * Returns the denormalized whole-meeting actual duration.
     *
     * @return the actual duration in seconds, or {@code null}
     */
    public Integer getActualDurationSeconds() {
        return actualDurationSeconds;
    }

    /**
     * Returns the closing organizer/admin's user id.
     *
     * @return the generator's {@code public.users.id}
     */
    public Long getGeneratedBy() {
        return generatedBy;
    }

    /**
     * Returns the freeze instant.
     *
     * @return the generatedAt instant
     */
    public Instant getGeneratedAt() {
        return generatedAt;
    }
}
