package fr.pivot.collaboratif.meeting;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

import java.util.UUID;

/**
 * JPA entity representing a single agenda point of a {@link Meeting} (US12.1.1 AC2).
 *
 * <p>Always created through {@link Meeting#addAgendaItem} — never independently — so its
 * {@link #position} is always correctly derived from the owning meeting's current item count at
 * construction time. {@code facilitator} is a free-text display name (optional), not a
 * {@code public.users.id} reference — the AC does not require the facilitator to be a resolvable
 * platform account.
 */
@Entity
@Table(name = "agenda_items", schema = "collaboratif")
public class AgendaItem {

    /** Primary key generated by the database via UUID strategy. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Owning meeting. */
    @ManyToOne
    @JoinColumn(name = "meeting_id", nullable = false)
    private Meeting meeting;

    /** {@code 0}-based display order within the meeting's agenda. */
    @Column(nullable = false)
    private int position;

    /** Agenda item title; maximum 200 characters enforced at the API layer. */
    @Column(nullable = false, length = 200)
    private String title;

    /** Planned duration in minutes; strictly positive, enforced at the API layer. */
    @Column(name = "duration_minutes", nullable = false)
    private Integer durationMinutes;

    /** Category of this agenda item. */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private AgendaItemType type;

    /** Optional free-text facilitator display name, or {@code null}. */
    @Column(length = 200)
    private String facilitator;

    /** No-arg constructor required by JPA. */
    protected AgendaItem() {
    }

    /**
     * Full constructor for creating a new agenda item.
     *
     * @param meeting          the owning meeting
     * @param position         {@code 0}-based display order
     * @param title            item title (max 200 chars)
     * @param durationMinutes  planned duration in minutes, strictly positive
     * @param type             the item's category
     * @param facilitator      optional facilitator display name, or {@code null}
     */
    public AgendaItem(
            final Meeting meeting, final int position, final String title,
            final Integer durationMinutes, final AgendaItemType type, final String facilitator) {
        this.meeting = meeting;
        this.position = position;
        this.title = title;
        this.durationMinutes = durationMinutes;
        this.type = type;
        this.facilitator = facilitator;
    }

    /**
     * Returns the agenda item's unique identifier.
     *
     * @return the UUID
     */
    public UUID getId() {
        return id;
    }

    /**
     * Returns the owning meeting.
     *
     * @return the meeting
     */
    public Meeting getMeeting() {
        return meeting;
    }

    /**
     * Returns the {@code 0}-based display order within the meeting's agenda.
     *
     * @return the position
     */
    public int getPosition() {
        return position;
    }

    /**
     * Returns the agenda item title.
     *
     * @return the title
     */
    public String getTitle() {
        return title;
    }

    /**
     * Returns the planned duration in minutes.
     *
     * @return the duration minutes
     */
    public Integer getDurationMinutes() {
        return durationMinutes;
    }

    /**
     * Returns the item's category.
     *
     * @return the type
     */
    public AgendaItemType getType() {
        return type;
    }

    /**
     * Returns the optional facilitator display name.
     *
     * @return the facilitator name, or {@code null}
     */
    public String getFacilitator() {
        return facilitator;
    }
}
