package fr.pivot.collaboratif.meeting;

import jakarta.persistence.Column;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;

import java.util.UUID;

/**
 * Shared JPA base for the two "captured during a meeting" note entities, {@link MeetingAction}
 * and {@link MeetingDecision}: both are a free-text {@code label} scoped by tenant, meeting and
 * (optionally) the agenda item current at capture time — extracted here (US12.3.1) purely to
 * remove the field/getter duplication SonarCloud flagged between the two, once
 * {@code MeetingDecision} was introduced alongside the already-existing {@code MeetingAction}
 * (US12.2.1). Neither subclass's own fields (e.g. {@code ownerUserId}/{@code dueDate}/{@code
 * status} on {@link MeetingAction}, {@code decidedAt}/{@code createdBy} on {@link
 * MeetingDecision}) belong here — only what both genuinely share.
 */
@MappedSuperclass
public abstract class MeetingCaptureEntity {

    /** Primary key generated by the database via UUID strategy. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Tenant that owns this row; used for multi-tenant isolation. */
    @Column(name = "tenant_id", nullable = false, updatable = false)
    private Long tenantId;

    /** The meeting this row was captured/recorded during. */
    @Column(name = "meeting_id", nullable = false, updatable = false)
    private UUID meetingId;

    /** The agenda item current at capture/recording time, or {@code null}. */
    @Column(name = "agenda_item_id", updatable = false)
    private UUID agendaItemId;

    /** Free-text description. */
    @Column(nullable = false, columnDefinition = "TEXT")
    private String label;

    /** No-arg constructor required by JPA. */
    protected MeetingCaptureEntity() {
    }

    /**
     * Full constructor for the shared fields — subclasses add their own on top.
     *
     * @param tenantId     owning tenant's {@code public.tenants.id}
     * @param meetingId    the meeting this row was captured/recorded during
     * @param agendaItemId the agenda item current at capture/recording time, or {@code null}
     * @param label        the free-text description
     */
    protected MeetingCaptureEntity(
            final Long tenantId, final UUID meetingId, final UUID agendaItemId, final String label) {
        this.tenantId = tenantId;
        this.meetingId = meetingId;
        this.agendaItemId = agendaItemId;
        this.label = label;
    }

    /**
     * Returns this row's unique identifier.
     *
     * @return the UUID
     */
    public UUID getId() {
        return id;
    }

    /**
     * Returns the tenant identifier.
     *
     * @return the tenant's {@code public.tenants.id}
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * Returns the meeting this row was captured/recorded during.
     *
     * @return the meeting's UUID
     */
    public UUID getMeetingId() {
        return meetingId;
    }

    /**
     * Returns the agenda item current at capture/recording time.
     *
     * @return the agenda item's UUID, or {@code null}
     */
    public UUID getAgendaItemId() {
        return agendaItemId;
    }

    /**
     * Returns the free-text description.
     *
     * @return the label
     */
    public String getLabel() {
        return label;
    }
}
