package fr.pivot.collaboratif.meeting;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OrderBy;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;

import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

/**
 * JPA entity representing a prepared meeting with a structured agenda (US12.1.1).
 *
 * <p>Belongs to a single tenant; {@code teamId} is optional — a meeting may be created for
 * individual/personal use, mirroring {@code fr.pivot.collaboratif.session.Session}'s own optional
 * {@code teamId} (never a hard multi-tenant-relevant field, unlike {@code tenantId}). Owns its
 * ordered list of {@link AgendaItem} rows as an aggregate (cascade all, orphan removal) — agenda
 * items are never created/deleted independently of their meeting, which is what makes the
 * "création atomique" requirement (AC6 — a validation failure on any item rolls back the whole
 * meeting) fall out of a single {@code meetingRepository.save(meeting)} call rather than needing
 * explicit compensating logic.
 */
@Entity
@Table(name = "meetings", schema = "collaboratif")
public class Meeting {

    /** Primary key generated by the database via UUID strategy. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Tenant that owns this meeting; used for multi-tenant isolation. */
    @Column(name = "tenant_id", nullable = false, updatable = false)
    private Long tenantId;

    /** Optional owning team's {@code public.teams.id} — {@code null} for a personal meeting. */
    @Column(name = "team_id")
    private Long teamId;

    /** Human-readable meeting title; maximum 200 characters enforced at the API layer. */
    @Column(nullable = false, length = 200)
    private String title;

    /** Date/time the meeting is scheduled for. */
    @Column(name = "scheduled_at", nullable = false)
    private Instant scheduledAt;

    /** Planned total duration of the meeting, in minutes (bounds [1, 1440] at the API layer). */
    @Column(name = "total_duration_minutes", nullable = false)
    private Integer totalDurationMinutes;

    /** Lifecycle status; {@link MeetingStatus#DRAFT} at creation (this US's only value). */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private MeetingStatus status = MeetingStatus.DRAFT;

    /** User who created this meeting — the authenticated principal, never client-supplied. */
    @Column(name = "created_by", nullable = false, updatable = false)
    private Long createdBy;

    /** Timestamp when this meeting was first persisted. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** Timestamp of the last update; refreshed automatically before every update. */
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /**
     * {@code id} of the {@link AgendaItem} currently being animated ({@link
     * AgendaItemStatus#CURRENT}), or {@code null} when the meeting has not started or has ended
     * (US12.2.1). Not a JPA association on purpose — this column is written/read purely as a
     * scalar id (mirrors {@code current_agenda_item_id}'s own shape in V18) so {@link
     * #getCurrentAgendaItem()} can resolve it against the already-loaded {@link #agendaItems}
     * collection without an extra query.
     */
    @Column(name = "current_agenda_item_id")
    private UUID currentAgendaItemId;

    /** Timestamp the meeting was started ({@code POST .../start}, AC-01), or {@code null}. */
    @Column(name = "started_at")
    private Instant startedAt;

    /** Timestamp the meeting was concluded (AC-03 last item / AC-06 {@code end}), or {@code null}. */
    @Column(name = "ended_at")
    private Instant endedAt;

    /**
     * Whether the server auto-advances the agenda when the current item's allotted duration
     * expires (AC-05) — {@code false} by default (manual-only progression, AC-03/AC-04).
     */
    @Column(name = "auto_advance", nullable = false)
    private boolean autoAdvance;

    /**
     * Agenda items of this meeting, aggregate-owned — cascades all persistence operations,
     * ordered by their {@code 0}-based display {@link AgendaItem#getPosition()}.
     */
    @OneToMany(mappedBy = "meeting", cascade = CascadeType.ALL, orphanRemoval = true)
    @OrderBy("position ASC")
    private List<AgendaItem> agendaItems = new ArrayList<>();

    /** No-arg constructor required by JPA. */
    protected Meeting() {
    }

    /**
     * Full constructor for creating a new meeting, {@link MeetingStatus#DRAFT}.
     *
     * @param tenantId              owning tenant's {@code public.tenants.id} — from
     *                              {@code TenantContext}, never client-supplied
     * @param teamId                optional owning team's {@code public.teams.id}, or
     *                              {@code null} for a personal meeting
     * @param title                 meeting title (max 200 chars)
     * @param scheduledAt           the scheduled date/time
     * @param totalDurationMinutes  planned total duration in minutes
     * @param createdBy             creating user's {@code public.users.id} — the authenticated
     *                              principal, never client-supplied
     * @param now                   timestamp used for both {@code createdAt} and
     *                              {@code updatedAt}
     */
    public Meeting(
            final Long tenantId,
            final Long teamId,
            final String title,
            final Instant scheduledAt,
            final Integer totalDurationMinutes,
            final Long createdBy,
            final Instant now) {
        this.tenantId = tenantId;
        this.teamId = teamId;
        this.title = title;
        this.scheduledAt = scheduledAt;
        this.totalDurationMinutes = totalDurationMinutes;
        this.status = MeetingStatus.DRAFT;
        this.createdBy = createdBy;
        this.createdAt = now;
        this.updatedAt = now;
    }

    /**
     * Sets {@code createdAt} and {@code updatedAt} to the current instant before
     * the first insert, when the fields have not already been set.
     */
    @PrePersist
    public void prePersist() {
        Instant now = Instant.now();
        if (this.createdAt == null) {
            this.createdAt = now;
        }
        if (this.updatedAt == null) {
            this.updatedAt = now;
        }
    }

    /**
     * Refreshes {@code updatedAt} to the current instant before every update.
     */
    @PreUpdate
    public void preUpdate() {
        this.updatedAt = Instant.now();
    }

    /**
     * Appends a new agenda item owned by this meeting, at the next {@code 0}-based position.
     *
     * @param title            agenda item title (max 200 chars)
     * @param durationMinutes  planned duration in minutes, strictly positive
     * @param type             the item's category
     * @param facilitator      optional facilitator display name, or {@code null}
     * @return the newly created, not-yet-persisted {@link AgendaItem}
     */
    public AgendaItem addAgendaItem(
            final String title, final Integer durationMinutes, final AgendaItemType type,
            final String facilitator) {
        AgendaItem item = new AgendaItem(this, agendaItems.size(), title, durationMinutes, type, facilitator);
        agendaItems.add(item);
        return item;
    }

    /**
     * Returns the meeting's unique identifier.
     *
     * @return the UUID
     */
    public UUID getId() {
        return id;
    }

    /**
     * Returns the tenant identifier.
     *
     * @return the tenant's {@code public.tenants.id}
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * Returns the optional owning team identifier.
     *
     * @return the team's {@code public.teams.id}, or {@code null} for a personal meeting
     */
    public Long getTeamId() {
        return teamId;
    }

    /**
     * Returns the meeting title.
     *
     * @return the title
     */
    public String getTitle() {
        return title;
    }

    /**
     * Returns the scheduled date/time.
     *
     * @return the scheduledAt instant
     */
    public Instant getScheduledAt() {
        return scheduledAt;
    }

    /**
     * Returns the planned total duration in minutes.
     *
     * @return the total duration minutes
     */
    public Integer getTotalDurationMinutes() {
        return totalDurationMinutes;
    }

    /**
     * Returns the lifecycle status.
     *
     * @return the status
     */
    public MeetingStatus getStatus() {
        return status;
    }

    /**
     * Returns the creating user's identifier.
     *
     * @return the creator's {@code public.users.id}
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * Returns the creation timestamp.
     *
     * @return the createdAt instant
     */
    public Instant getCreatedAt() {
        return createdAt;
    }

    /**
     * Returns the last-updated timestamp.
     *
     * @return the updatedAt instant
     */
    public Instant getUpdatedAt() {
        return updatedAt;
    }

    /**
     * Returns the live, mutable, position-sorted list of agenda items.
     *
     * @return the mutable agenda items list
     */
    public List<AgendaItem> getAgendaItems() {
        return agendaItems;
    }

    /**
     * Returns the id of the {@link AgendaItem} currently being animated.
     *
     * @return the current agenda item's id, or {@code null} if none
     */
    public UUID getCurrentAgendaItemId() {
        return currentAgendaItemId;
    }

    /**
     * Resolves {@link #getCurrentAgendaItemId()} against the already-loaded {@link #agendaItems}.
     *
     * @return the current agenda item, or empty if the meeting has no current item
     */
    public Optional<AgendaItem> getCurrentAgendaItem() {
        if (currentAgendaItemId == null) {
            return Optional.empty();
        }
        return agendaItems.stream().filter(item -> currentAgendaItemId.equals(item.getId())).findFirst();
    }

    /**
     * Returns the timestamp the meeting was started.
     *
     * @return the startedAt instant, or {@code null} if not yet started
     */
    public Instant getStartedAt() {
        return startedAt;
    }

    /**
     * Returns the timestamp the meeting was concluded.
     *
     * @return the endedAt instant, or {@code null} if not yet ended
     */
    public Instant getEndedAt() {
        return endedAt;
    }

    /**
     * Returns whether the server auto-advances the agenda on expiry (AC-05).
     *
     * @return {@code true} if auto-advance is enabled
     */
    public boolean isAutoAdvance() {
        return autoAdvance;
    }

    /**
     * Transitions the meeting to {@link MeetingStatus#IN_PROGRESS} and makes {@code item} the
     * current one (AC-01) — the caller is responsible for having already validated the previous
     * status and that {@code item} belongs to this meeting.
     *
     * @param item the agenda item to make current (normally the first, position {@code 0})
     * @param now  server-authoritative timestamp, used for both the meeting's {@code startedAt}
     *             and the item's {@code currentItemStartedAt}
     */
    public void start(final AgendaItem item, final Instant now) {
        this.status = MeetingStatus.IN_PROGRESS;
        this.startedAt = now;
        this.currentAgendaItemId = item.getId();
        item.markCurrent(now);
    }

    /**
     * Marks {@code current} as {@link AgendaItemStatus#DONE} and {@code next} as the new
     * {@link AgendaItemStatus#CURRENT} item (AC-03 manual, AC-05 auto-advance) — the caller is
     * responsible for having already validated the meeting is {@link MeetingStatus#IN_PROGRESS}.
     *
     * @param current the item being left, marked {@code DONE}
     * @param next    the item being entered, marked {@code CURRENT}
     * @param now     server-authoritative timestamp
     */
    public void advanceTo(final AgendaItem current, final AgendaItem next, final Instant now) {
        current.markDone(now);
        next.markCurrent(now);
        this.currentAgendaItemId = next.getId();
    }

    /**
     * Transitions the meeting to {@link MeetingStatus#ENDED} (AC-03 last item, AC-06 manual
     * {@code end}) — marks {@code current} {@code DONE} first when one exists (a meeting can be
     * ended with no current item only defensively; every reachable {@code IN_PROGRESS} meeting
     * has one by construction).
     *
     * @param current the current item, marked {@code DONE}, or {@code null} if none
     * @param now     server-authoritative timestamp
     */
    public void end(final AgendaItem current, final Instant now) {
        if (current != null) {
            current.markDone(now);
        }
        this.status = MeetingStatus.ENDED;
        this.endedAt = now;
        this.currentAgendaItemId = null;
    }
}
