package fr.pivot.collaboratif.session.vote;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.time.Instant;
import java.util.UUID;

/**
 * A single participant's ballot on a VOTE-type session (US19.3.6) — one row per
 * {@code (sessionId, participantId)}, never overwritten: a second submission is a 409, unlike
 * POLL's re-votable ballot (a structured decision must be an auditable, one-shot record).
 *
 * <p>{@code payload} is a JSONB blob whose shape depends on the vote type — {@code {"value": 0..5}}
 * for FIST_TO_FIVE, {@code {"allocations": {"0": n, "1": m, ...}}} for WEIGHTED.
 */
@Entity
@Table(name = "session_vote_ballot", schema = "collaboratif")
public class SessionVoteBallot {

    /** Primary key generated by the database via UUID strategy — never client-supplied. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Owning session; cascades on session deletion. */
    @Column(name = "session_id", nullable = false, updatable = false)
    private UUID sessionId;

    /** The voting participant. */
    @Column(name = "participant_id", nullable = false, updatable = false)
    private UUID participantId;

    /** The type-dependent ballot payload, stored as a JSONB object. */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(nullable = false, columnDefinition = "jsonb")
    private String payload;

    /** Submission timestamp — part of the decision's audit trail. */
    @Column(name = "submitted_at", nullable = false, updatable = false)
    private Instant submittedAt;

    /** No-arg constructor required by JPA. */
    protected SessionVoteBallot() {
    }

    /**
     * Creates a new ballot.
     *
     * @param sessionId     the owning session's UUID
     * @param participantId the voting participant's UUID
     * @param payload       the type-dependent ballot payload, as a JSON object string
     * @param now           the submission timestamp
     */
    public SessionVoteBallot(
            final UUID sessionId, final UUID participantId, final String payload, final Instant now) {
        this.sessionId = sessionId;
        this.participantId = participantId;
        this.payload = payload;
        this.submittedAt = now;
    }

    /** Sets {@code submittedAt} before the first insert, when not already set. */
    @PrePersist
    public void prePersist() {
        if (this.submittedAt == null) {
            this.submittedAt = Instant.now();
        }
    }

    public UUID getId() {
        return id;
    }

    public UUID getSessionId() {
        return sessionId;
    }

    public UUID getParticipantId() {
        return participantId;
    }

    public String getPayload() {
        return payload;
    }

    public Instant getSubmittedAt() {
        return submittedAt;
    }
}
