package fr.pivot.collaboratif.session.postitrush;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.time.Duration;
import java.time.Instant;
import java.util.UUID;

/**
 * One server-generated post-it of a {@link SessionPostitRushRound} (US47.2.1) — position, color,
 * spawn instant and lifespan are always server-decided, never client-supplied. {@link #claimedBy}
 * is set atomically by the first winning click; {@link #expired} is set by the scheduler once
 * {@link #spawnedAt} + {@link #lifespanMs} elapses unclaimed.
 */
@Entity
@Table(name = "session_postit_rush_spawn", schema = "collaboratif")
public class SessionPostitRushSpawn {

    /** Primary key generated by the database via UUID strategy — never client-supplied. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Owning round; cascades on round deletion. */
    @Column(name = "round_id", nullable = false, updatable = false)
    private UUID roundId;

    /** Percentage x-coordinate (0-100) on the shared board. */
    @Column(name = "x", nullable = false, updatable = false)
    private double x;

    /** Percentage y-coordinate (0-100) on the shared board. */
    @Column(name = "y", nullable = false, updatable = false)
    private double y;

    /** Non-color visual identity key (e.g. {@code "amber"}) — paired with shape/label client-side. */
    @Column(name = "color_key", nullable = false, length = 20, updatable = false)
    private String colorKey;

    /** Server-authoritative spawn instant. */
    @Column(name = "spawned_at", nullable = false, updatable = false)
    private Instant spawnedAt;

    /** Random lifespan in milliseconds (1200-2500), server-decided at spawn time. */
    @Column(name = "lifespan_ms", nullable = false, updatable = false)
    private int lifespanMs;

    /** The participant who claimed it first, or {@code null} while unclaimed. */
    @Column(name = "claimed_by")
    private UUID claimedBy;

    /** Instant of the claim, or {@code null} while unclaimed. */
    @Column(name = "claimed_at")
    private Instant claimedAt;

    /** {@code true} once the lifespan elapsed without a claim. */
    @Column(name = "expired", nullable = false)
    private boolean expired;

    /** No-arg constructor required by JPA. */
    protected SessionPostitRushSpawn() {
    }

    /**
     * Creates a new, unclaimed spawn.
     *
     * @param roundId    the owning round's UUID
     * @param x          percentage x-coordinate (0-100)
     * @param y          percentage y-coordinate (0-100)
     * @param colorKey   non-color visual identity key
     * @param spawnedAt  server-authoritative spawn instant
     * @param lifespanMs random lifespan in milliseconds (1200-2500)
     */
    public SessionPostitRushSpawn(
            final UUID roundId,
            final double x,
            final double y,
            final String colorKey,
            final Instant spawnedAt,
            final int lifespanMs) {
        this.roundId = roundId;
        this.x = x;
        this.y = y;
        this.colorKey = colorKey;
        this.spawnedAt = spawnedAt;
        this.lifespanMs = lifespanMs;
    }

    /**
     * Returns whether this post-it is still live (unclaimed and unexpired) at the given instant.
     *
     * @param now the instant to check against
     * @return {@code true} if unclaimed, unexpired, and the lifespan has not elapsed
     */
    public boolean isLiveAt(final Instant now) {
        return claimedBy == null && !expired && spawnedAt.plusMillis(lifespanMs).isAfter(now);
    }

    /**
     * Returns whether this post-it's lifespan has elapsed at the given instant, regardless of
     * claim state.
     *
     * @param now the instant to check against
     * @return {@code true} if {@code spawnedAt + lifespanMs <= now}
     */
    public boolean isPastLifespan(final Instant now) {
        return !spawnedAt.plusMillis(lifespanMs).isAfter(now);
    }

    /**
     * Returns the milliseconds remaining before this post-it expires, floored at zero.
     *
     * @param now the instant to compute against
     * @return the remaining lifespan in milliseconds, never negative
     */
    public long remainingMs(final Instant now) {
        long remaining = Duration.between(now, spawnedAt.plusMillis(lifespanMs)).toMillis();
        return Math.max(0, remaining);
    }

    /**
     * Records a successful claim.
     *
     * @param participantId the claiming participant's id
     * @param claimedAt     the claim instant
     */
    public void claim(final UUID participantId, final Instant claimedAt) {
        this.claimedBy = participantId;
        this.claimedAt = claimedAt;
    }

    /**
     * Marks this post-it as expired.
     */
    public void expire() {
        this.expired = true;
    }

    /**
     * Returns the spawn's unique identifier.
     *
     * @return the UUID
     */
    public UUID getId() {
        return id;
    }

    /**
     * Returns the owning round's identifier.
     *
     * @return the round UUID
     */
    public UUID getRoundId() {
        return roundId;
    }

    /**
     * Returns the percentage x-coordinate.
     *
     * @return x, 0-100
     */
    public double getX() {
        return x;
    }

    /**
     * Returns the percentage y-coordinate.
     *
     * @return y, 0-100
     */
    public double getY() {
        return y;
    }

    /**
     * Returns the non-color visual identity key.
     *
     * @return the color key
     */
    public String getColorKey() {
        return colorKey;
    }

    /**
     * Returns the server-authoritative spawn instant.
     *
     * @return the spawnedAt instant
     */
    public Instant getSpawnedAt() {
        return spawnedAt;
    }

    /**
     * Returns the lifespan in milliseconds.
     *
     * @return the lifespan
     */
    public int getLifespanMs() {
        return lifespanMs;
    }

    /**
     * Returns the claiming participant's id.
     *
     * @return the participant UUID, or {@code null} while unclaimed
     */
    public UUID getClaimedBy() {
        return claimedBy;
    }

    /**
     * Returns whether this post-it has expired.
     *
     * @return the expired flag
     */
    public boolean isExpired() {
        return expired;
    }
}
