package fr.pivot.collaboratif.session.postitrush;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.time.Instant;
import java.util.UUID;

/**
 * One round of the POST-IT RUSH activity type (US47.2.1) — the server-authoritative clock for a
 * single 90-second (default) rush: {@link #startedAt}/{@link #durationSeconds} are what the
 * backend alone uses to decide when the round ends, never a client-reported elapsed time.
 *
 * <p>{@link #nextSpawnAt} is internal scheduler bookkeeping (never serialized to a client — the
 * spawn schedule is never pre-disclosed). {@link #leaderboardBroadcastAt}/{@link
 * #leaderboardDirty} implement the 500ms {@code LEADERBOARD_UPDATED} broadcast throttle.
 */
@Entity
@Table(name = "session_postit_rush_round", schema = "collaboratif")
public class SessionPostitRushRound {

    /** Primary key generated by the database via UUID strategy — never client-supplied. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Owning session; cascades on session deletion. */
    @Column(name = "session_id", nullable = false, updatable = false)
    private UUID sessionId;

    /** 1-based sequence number of this round within its session. */
    @Column(name = "round_number", nullable = false, updatable = false)
    private int roundNumber;

    /** Server-authoritative round duration in seconds (default 90). */
    @Column(name = "duration_seconds", nullable = false, updatable = false)
    private int durationSeconds;

    /** Server-authoritative round start instant. */
    @Column(name = "started_at", nullable = false, updatable = false)
    private Instant startedAt;

    /** Set once the round ends (timer elapsed); {@code null} while the round is active. */
    @Column(name = "ended_at")
    private Instant endedAt;

    /** Scheduler bookkeeping: the next instant a post-it should be spawned. */
    @Column(name = "next_spawn_at")
    private Instant nextSpawnAt;

    /** Instant of the last {@code LEADERBOARD_UPDATED} broadcast for this round. */
    @Column(name = "leaderboard_broadcast_at")
    private Instant leaderboardBroadcastAt;

    /** {@code true} when a score changed since the last leaderboard broadcast (throttle pending). */
    @Column(name = "leaderboard_dirty", nullable = false)
    private boolean leaderboardDirty;

    /** No-arg constructor required by JPA. */
    protected SessionPostitRushRound() {
    }

    /**
     * Creates a new round.
     *
     * @param sessionId       the owning session's UUID
     * @param roundNumber     1-based sequence number within the session
     * @param durationSeconds server-authoritative duration in seconds
     * @param startedAt       server-authoritative start instant
     */
    public SessionPostitRushRound(
            final UUID sessionId, final int roundNumber, final int durationSeconds, final Instant startedAt) {
        this.sessionId = sessionId;
        this.roundNumber = roundNumber;
        this.durationSeconds = durationSeconds;
        this.startedAt = startedAt;
        this.nextSpawnAt = startedAt;
    }

    /**
     * Returns whether this round is still active (not yet ended).
     *
     * @return {@code true} if {@link #endedAt} is {@code null}
     */
    public boolean isActive() {
        return endedAt == null;
    }

    /**
     * Returns whether, at the given instant, this round's duration has elapsed.
     *
     * @param now the instant to check against
     * @return {@code true} if {@code startedAt + durationSeconds <= now}
     */
    public boolean isElapsed(final Instant now) {
        return !startedAt.plusSeconds(durationSeconds).isAfter(now);
    }

    /**
     * Marks the round as ended.
     *
     * @param endedAt the end instant
     */
    public void end(final Instant endedAt) {
        this.endedAt = endedAt;
    }

    /**
     * Returns the round's unique identifier.
     *
     * @return the UUID
     */
    public UUID getId() {
        return id;
    }

    /**
     * Returns the owning session's identifier.
     *
     * @return the session UUID
     */
    public UUID getSessionId() {
        return sessionId;
    }

    /**
     * Returns this round's 1-based sequence number.
     *
     * @return the round number
     */
    public int getRoundNumber() {
        return roundNumber;
    }

    /**
     * Returns the server-authoritative duration in seconds.
     *
     * @return the duration
     */
    public int getDurationSeconds() {
        return durationSeconds;
    }

    /**
     * Returns the server-authoritative start instant.
     *
     * @return the startedAt instant
     */
    public Instant getStartedAt() {
        return startedAt;
    }

    /**
     * Returns the end instant.
     *
     * @return the endedAt instant, or {@code null} while active
     */
    public Instant getEndedAt() {
        return endedAt;
    }

    /**
     * Returns the next scheduled spawn instant.
     *
     * @return the nextSpawnAt instant
     */
    public Instant getNextSpawnAt() {
        return nextSpawnAt;
    }

    /**
     * Sets the next scheduled spawn instant.
     *
     * @param nextSpawnAt the new next-spawn instant
     */
    public void setNextSpawnAt(final Instant nextSpawnAt) {
        this.nextSpawnAt = nextSpawnAt;
    }

    /**
     * Returns the last leaderboard broadcast instant.
     *
     * @return the leaderboardBroadcastAt instant, or {@code null} if never broadcast
     */
    public Instant getLeaderboardBroadcastAt() {
        return leaderboardBroadcastAt;
    }

    /**
     * Sets the last leaderboard broadcast instant.
     *
     * @param leaderboardBroadcastAt the new instant
     */
    public void setLeaderboardBroadcastAt(final Instant leaderboardBroadcastAt) {
        this.leaderboardBroadcastAt = leaderboardBroadcastAt;
    }

    /**
     * Returns whether a leaderboard broadcast is pending (throttled).
     *
     * @return {@code true} if a score changed since the last broadcast
     */
    public boolean isLeaderboardDirty() {
        return leaderboardDirty;
    }

    /**
     * Sets whether a leaderboard broadcast is pending.
     *
     * @param leaderboardDirty the new dirty flag
     */
    public void setLeaderboardDirty(final boolean leaderboardDirty) {
        this.leaderboardDirty = leaderboardDirty;
    }
}
