package fr.pivot.agilite.retro.vote;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;

import java.time.Instant;
import java.util.UUID;

/**
 * JPA entity representing a single dot-vote cast on a revealed retrospective card (US20.1.2b).
 *
 * <p>Maps {@code agilite.retro_votes}. A participant may cast several votes on the same card —
 * there is no uniqueness constraint on {@code (sessionId, cardId, voterToken)} — up to their
 * overall session balance, tracked separately by {@link RetroVoteBalance}. {@link #voterToken} is
 * never broadcast over any STOMP channel (see {@code RetroVoteService}); only the per-card
 * aggregate count derived from {@link RetroVoteRepository#countByCardId(UUID)} ever leaves the
 * server.
 */
@Entity
@Table(name = "retro_votes", schema = "agilite")
public class RetroVote {

    /** Primary key generated by the database via UUID strategy. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Owning session; FK to {@code agilite.retro_sessions.id}. */
    @Column(name = "session_id", nullable = false)
    private UUID sessionId;

    /** Voted-on card; FK to {@code agilite.retro_cards.id}. */
    @Column(name = "card_id", nullable = false)
    private UUID cardId;

    /**
     * Opaque identity of the voting participant — the same access-token string minted by {@code
     * RetroSessionAccessService#join} and carried on every STOMP frame as {@code
     * RetroChannelInterceptor#ACCESS_TOKEN_HEADER}. Never broadcast.
     */
    @Column(name = "voter_token", nullable = false, length = 64)
    private String voterToken;

    /** Timestamp when the vote was cast. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** No-arg constructor required by JPA. */
    protected RetroVote() {
    }

    /**
     * Full constructor for casting a new vote.
     *
     * @param sessionId  the owning session's id
     * @param cardId     the voted-on card's id
     * @param voterToken the voting participant's opaque access-token identity
     * @param createdAt  the timestamp the vote was cast at
     */
    public RetroVote(
            final UUID sessionId, final UUID cardId, final String voterToken, final Instant createdAt) {
        this.sessionId = sessionId;
        this.cardId = cardId;
        this.voterToken = voterToken;
        this.createdAt = createdAt;
    }

    /**
     * Sets {@code createdAt} to the current instant before the first insert, when not already
     * set.
     */
    @PrePersist
    public void prePersist() {
        if (this.createdAt == null) {
            this.createdAt = Instant.now();
        }
    }

    /**
     * Returns the vote's unique identifier.
     *
     * @return the UUID, {@code null} until first persisted
     */
    public UUID getId() {
        return id;
    }

    /**
     * Returns the owning session's identifier.
     *
     * @return the session UUID
     */
    public UUID getSessionId() {
        return sessionId;
    }

    /**
     * Returns the voted-on card's identifier.
     *
     * @return the card UUID
     */
    public UUID getCardId() {
        return cardId;
    }

    /**
     * Returns the voting participant's opaque access-token identity.
     *
     * @return the voter token
     */
    public String getVoterToken() {
        return voterToken;
    }

    /**
     * Returns the timestamp the vote was cast at.
     *
     * @return the createdAt instant
     */
    public Instant getCreatedAt() {
        return createdAt;
    }
}
