package fr.pivot.agilite.retro.vote;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;

import java.time.Instant;
import java.util.UUID;

/**
 * JPA entity tracking a single participant's remaining dot-vote balance for a retrospective
 * session (US20.1.2b).
 *
 * <p>Maps {@code agilite.retro_vote_balances}, unique on {@code (sessionId, voterToken)}. Rows
 * are created via {@code RetroVoteBalanceRepository#ensureBalanceRow} (native {@code INSERT ...
 * ON CONFLICT DO NOTHING}) and {@code votesUsed} is only ever mutated via that repository's
 * guarded atomic {@code UPDATE} statements ({@code incrementIfAvailable}/{@code
 * decrementIfPositive}) — never through this entity's own setters via {@code save()} — so the
 * balance can never go negative or exceed {@code votesAllowed} under concurrent contention. This
 * entity exists primarily for reading the authoritative current balance back (e.g. {@code
 * RetroVoteService#queryBalance}).
 */
@Entity
@Table(name = "retro_vote_balances", schema = "agilite")
public class RetroVoteBalance {

    /** Primary key generated by the database via UUID strategy. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Owning session; FK to {@code agilite.retro_sessions.id}. */
    @Column(name = "session_id", nullable = false)
    private UUID sessionId;

    /** Opaque identity of the participant this balance belongs to. */
    @Column(name = "voter_token", nullable = false, length = 64)
    private String voterToken;

    /** Number of votes this participant has cast so far in this session. */
    @Column(name = "votes_used", nullable = false)
    private int votesUsed;

    /** Total number of votes allotted to this participant for this session. */
    @Column(name = "votes_allowed", nullable = false)
    private int votesAllowed;

    /** Timestamp when this balance row was first created. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** Timestamp of the last update; refreshed automatically before every update. */
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /** No-arg constructor required by JPA. */
    protected RetroVoteBalance() {
    }

    /**
     * Full constructor — used by tests; production code creates rows exclusively via {@code
     * RetroVoteBalanceRepository#ensureBalanceRow}'s native insert.
     *
     * @param sessionId    the owning session's id
     * @param voterToken   the participant's opaque access-token identity
     * @param votesUsed    the number of votes already used
     * @param votesAllowed the total number of votes allotted
     * @param now          timestamp used for both {@code createdAt} and {@code updatedAt}
     */
    public RetroVoteBalance(
            final UUID sessionId, final String voterToken,
            final int votesUsed, final int votesAllowed, final Instant now) {
        this.sessionId = sessionId;
        this.voterToken = voterToken;
        this.votesUsed = votesUsed;
        this.votesAllowed = votesAllowed;
        this.createdAt = now;
        this.updatedAt = now;
    }

    /**
     * Sets {@code createdAt} and {@code updatedAt} to the current instant before the first
     * insert, when the fields have not already been set.
     */
    @PrePersist
    public void prePersist() {
        Instant now = Instant.now();
        if (this.createdAt == null) {
            this.createdAt = now;
        }
        if (this.updatedAt == null) {
            this.updatedAt = now;
        }
    }

    /**
     * Refreshes {@code updatedAt} to the current instant before every update.
     */
    @PreUpdate
    public void preUpdate() {
        this.updatedAt = Instant.now();
    }

    /**
     * Returns the balance row's unique identifier.
     *
     * @return the UUID, {@code null} until first persisted
     */
    public UUID getId() {
        return id;
    }

    /**
     * Returns the owning session's identifier.
     *
     * @return the session UUID
     */
    public UUID getSessionId() {
        return sessionId;
    }

    /**
     * Returns the participant's opaque access-token identity.
     *
     * @return the voter token
     */
    public String getVoterToken() {
        return voterToken;
    }

    /**
     * Returns the number of votes already used.
     *
     * @return the votes-used count
     */
    public int getVotesUsed() {
        return votesUsed;
    }

    /**
     * Returns the total number of votes allotted.
     *
     * @return the votes-allowed count
     */
    public int getVotesAllowed() {
        return votesAllowed;
    }

    /**
     * Returns the creation timestamp.
     *
     * @return the createdAt instant
     */
    public Instant getCreatedAt() {
        return createdAt;
    }

    /**
     * Returns the last-updated timestamp.
     *
     * @return the updatedAt instant
     */
    public Instant getUpdatedAt() {
        return updatedAt;
    }
}
