package fr.pivot.agilite.wheel;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OrderBy;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;

import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * JPA entity representing a wheel (module La Roue, US14.1.1).
 *
 * <p>A wheel belongs to a single team (and, redundantly, its tenant — mirroring {@code
 * collaboratif.Board}'s own {@code tenantId} column even though it is also derivable via the
 * team) and owns its list of {@link WheelEntry} rows as an aggregate: the {@code entries}
 * collection is loaded/mutated live (never a defensive copy) so that {@link WheelService} can
 * perform a full replace with {@code wheel.getEntries().clear()} followed by re-population,
 * relying on {@code orphanRemoval} to delete the previous rows.
 */
@Entity
@Table(name = "wheel", schema = "agilite")
public class Wheel {

    /** Primary key generated by the database via UUID strategy. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Tenant that owns this wheel; used for multi-tenant isolation. */
    @Column(name = "tenant_id", nullable = false)
    private Long tenantId;

    /** Team this wheel belongs to; immutable after creation. */
    @Column(name = "team_id", nullable = false)
    private Long teamId;

    /** Human-readable wheel name; maximum 100 characters enforced at the API layer. */
    @Column(name = "name", nullable = false, length = 100)
    private String name;

    /**
     * Marker for the anti-repeat weighted draw (US14.2.1) — the {@link WheelEntry#getId()} last
     * drawn on this wheel, or {@code null} if no draw has occurred yet. Written by {@link
     * WheelDrawService} after each successful {@code spin} (US14.2.1); always {@code null} until
     * then.
     */
    @Column(name = "last_drawn_entry_id")
    private UUID lastDrawnEntryId;

    /** User who created this wheel. */
    @Column(name = "created_by", nullable = false)
    private Long createdBy;

    /** Timestamp when the wheel was first persisted. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** Timestamp of the last update; refreshed automatically before every update. */
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /** Entries of this wheel — aggregate-owned, cascades all persistence operations. */
    @OneToMany(mappedBy = "wheel", cascade = CascadeType.ALL, orphanRemoval = true)
    @OrderBy("createdAt ASC")
    private List<WheelEntry> entries = new ArrayList<>();

    /** No-arg constructor required by JPA. */
    protected Wheel() {
    }

    /**
     * Full constructor for creating a new wheel.
     *
     * @param tenantId  owning tenant's {@code public.tenants.id}
     * @param teamId    owning team's {@code public.teams.id}
     * @param name      wheel name (max 100 chars)
     * @param createdBy creating user's {@code public.users.id}
     * @param now       timestamp used for both {@code createdAt} and {@code updatedAt}
     */
    public Wheel(
            final Long tenantId,
            final Long teamId,
            final String name,
            final Long createdBy,
            final Instant now) {
        this.tenantId = tenantId;
        this.teamId = teamId;
        this.name = name;
        this.createdBy = createdBy;
        this.createdAt = now;
        this.updatedAt = now;
    }

    /**
     * Sets {@code createdAt} and {@code updatedAt} to the current instant before
     * the first insert, when the fields have not already been set.
     */
    @PrePersist
    public void prePersist() {
        Instant now = Instant.now();
        if (this.createdAt == null) {
            this.createdAt = now;
        }
        if (this.updatedAt == null) {
            this.updatedAt = now;
        }
    }

    /**
     * Refreshes {@code updatedAt} to the current instant before every update.
     */
    @PreUpdate
    public void preUpdate() {
        this.updatedAt = Instant.now();
    }

    /**
     * Returns the wheel's unique identifier.
     *
     * @return the UUID
     */
    public UUID getId() {
        return id;
    }

    /**
     * Returns the tenant identifier.
     *
     * @return the tenant's {@code public.tenants.id}
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * Returns the team identifier.
     *
     * @return the team's {@code public.teams.id}
     */
    public Long getTeamId() {
        return teamId;
    }

    /**
     * Returns the wheel name.
     *
     * @return the name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the wheel name.
     *
     * @param name the name to set
     */
    public void setName(final String name) {
        this.name = name;
    }

    /**
     * Returns the id of the last drawn entry, or {@code null} if no draw has occurred yet.
     *
     * @return the last drawn entry's UUID, or {@code null}
     */
    public UUID getLastDrawnEntryId() {
        return lastDrawnEntryId;
    }

    /**
     * Records the entry just drawn by a weighted {@code spin} (US14.2.1) as this wheel's
     * anti-repeat marker, consumed by the next draw.
     *
     * @param entryId the drawn entry's identifier
     */
    public void setLastDrawnEntryId(final UUID entryId) {
        this.lastDrawnEntryId = entryId;
    }

    /**
     * Returns the creating user's identifier.
     *
     * @return the creator's {@code public.users.id}
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * Returns the creation timestamp.
     *
     * @return the createdAt instant
     */
    public Instant getCreatedAt() {
        return createdAt;
    }

    /**
     * Returns the last-updated timestamp.
     *
     * @return the updatedAt instant
     */
    public Instant getUpdatedAt() {
        return updatedAt;
    }

    /**
     * Returns the live, mutable list of entries — callers may {@code clear()}/{@code add} onto
     * it directly to perform a full replace relying on {@code orphanRemoval}.
     *
     * @return the mutable entries list
     */
    public List<WheelEntry> getEntries() {
        return entries;
    }
}
