package fr.pivot.agilite.wheel;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;

import java.time.Instant;
import java.util.UUID;

/**
 * JPA entity representing a single entrant of a {@link Wheel} (US14.1.1).
 *
 * <p>Either references an existing team member ({@link WheelEntryType#TEAM_MEMBER},
 * {@code teamMemberId} set, {@code label} resolved server-side from {@code public.users} at
 * write time) or is a free-text ad hoc entrant ({@link WheelEntryType#FREE_TEXT},
 * {@code teamMemberId} {@code null}, {@code label} the raw client-provided text).
 */
@Entity
@Table(name = "wheel_entry", schema = "agilite")
public class WheelEntry {

    /** Primary key generated by the database via UUID strategy. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Owning wheel. */
    @ManyToOne
    @JoinColumn(name = "wheel_id", nullable = false)
    private Wheel wheel;

    /** Kind of entry — team member reference or free text. */
    @Enumerated(EnumType.STRING)
    @Column(name = "entry_type", nullable = false, length = 20)
    private WheelEntryType entryType;

    /** Referenced {@code public.team_members.id}, or {@code null} for a free-text entry. */
    @Column(name = "team_member_id")
    private Long teamMemberId;

    /**
     * Display label — server-resolved display name for a {@code TEAM_MEMBER} entry, raw
     * client-provided text for a {@code FREE_TEXT} entry.
     */
    @Column(name = "label", nullable = false, length = 150)
    private String label;

    /** Draw weight, 1 (lowest) to 10 (highest); defaults to 1 (equal weighting). */
    @Column(name = "weight", nullable = false)
    private int weight = 1;

    /** Timestamp when the entry was first persisted. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** Timestamp of the last update; refreshed automatically before every update. */
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /** No-arg constructor required by JPA. */
    protected WheelEntry() {
    }

    /**
     * Full constructor for creating a new entry.
     *
     * @param wheel        the owning wheel
     * @param entryType    the kind of entry
     * @param teamMemberId the referenced {@code public.team_members.id}, or {@code null}
     * @param label        the display label
     * @param weight       the draw weight (1-10)
     * @param now          timestamp used for both {@code createdAt} and {@code updatedAt}
     */
    public WheelEntry(
            final Wheel wheel,
            final WheelEntryType entryType,
            final Long teamMemberId,
            final String label,
            final int weight,
            final Instant now) {
        this.wheel = wheel;
        this.entryType = entryType;
        this.teamMemberId = teamMemberId;
        this.label = label;
        this.weight = weight;
        this.createdAt = now;
        this.updatedAt = now;
    }

    /**
     * Sets {@code createdAt} and {@code updatedAt} to the current instant before
     * the first insert, when the fields have not already been set.
     */
    @PrePersist
    public void prePersist() {
        Instant now = Instant.now();
        if (this.createdAt == null) {
            this.createdAt = now;
        }
        if (this.updatedAt == null) {
            this.updatedAt = now;
        }
    }

    /**
     * Refreshes {@code updatedAt} to the current instant before every update.
     */
    @PreUpdate
    public void preUpdate() {
        this.updatedAt = Instant.now();
    }

    /**
     * Returns the entry's unique identifier.
     *
     * @return the UUID
     */
    public UUID getId() {
        return id;
    }

    /**
     * Returns the owning wheel.
     *
     * @return the wheel
     */
    public Wheel getWheel() {
        return wheel;
    }

    /**
     * Returns the entry kind.
     *
     * @return the entry type
     */
    public WheelEntryType getEntryType() {
        return entryType;
    }

    /**
     * Returns the referenced team member id, or {@code null} for a free-text entry.
     *
     * @return the {@code public.team_members.id}, or {@code null}
     */
    public Long getTeamMemberId() {
        return teamMemberId;
    }

    /**
     * Returns the display label.
     *
     * @return the label
     */
    public String getLabel() {
        return label;
    }

    /**
     * Returns the draw weight.
     *
     * @return the weight, 1-10
     */
    public int getWeight() {
        return weight;
    }

    /**
     * Returns the creation timestamp.
     *
     * @return the createdAt instant
     */
    public Instant getCreatedAt() {
        return createdAt;
    }

    /**
     * Returns the last-updated timestamp.
     *
     * @return the updatedAt instant
     */
    public Instant getUpdatedAt() {
        return updatedAt;
    }
}
