package fr.pivot.agilite.wheel;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.time.Instant;
import java.util.UUID;

/**
 * JPA entity representing a single persisted draw result for a {@link Wheel} (US14.2.1).
 *
 * <p>Deliberately a plain {@code wheel_id}/{@code entry_id} column pair rather than {@code
 * @ManyToOne} JPA associations: this is an append-only history log, not part of the {@link Wheel}
 * aggregate, and must survive both the entry being removed later via {@code PUT /wheels/{id}}
 * (hence {@code entry_id} being nullable, {@code ON DELETE SET NULL} in the migration, and {@code
 * entryLabel} being a frozen snapshot rather than a live join) and independent read access via
 * {@code GET /wheels/{id}/draws} without pulling in the owning {@link Wheel}.
 */
@Entity
@Table(name = "wheel_draw", schema = "agilite")
public class WheelDraw {

    /** Primary key generated by the database via UUID strategy. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** The drawn-from wheel's identifier. */
    @Column(name = "wheel_id", nullable = false)
    private UUID wheelId;

    /**
     * The drawn entry's identifier, or {@code null} if that entry has since been removed from the
     * wheel (the {@code entryLabel} snapshot below still reflects what was actually drawn).
     */
    @Column(name = "entry_id")
    private UUID entryId;

    /** Display label of the drawn entry, frozen at draw time. */
    @Column(name = "entry_label", nullable = false, length = 150)
    private String entryLabel;

    /** Timestamp when the draw occurred. */
    @Column(name = "drawn_at", nullable = false)
    private Instant drawnAt;

    /** No-arg constructor required by JPA. */
    protected WheelDraw() {
    }

    /**
     * Creates a new draw history row.
     *
     * @param wheelId    the drawn-from wheel's identifier
     * @param entryId    the drawn entry's identifier
     * @param entryLabel the drawn entry's display label, frozen at draw time
     * @param drawnAt    the timestamp of the draw
     */
    public WheelDraw(final UUID wheelId, final UUID entryId, final String entryLabel, final Instant drawnAt) {
        this.wheelId = wheelId;
        this.entryId = entryId;
        this.entryLabel = entryLabel;
        this.drawnAt = drawnAt;
    }

    /**
     * Returns the draw's unique identifier.
     *
     * @return the UUID
     */
    public UUID getId() {
        return id;
    }

    /**
     * Returns the drawn-from wheel's identifier.
     *
     * @return the wheel's UUID
     */
    public UUID getWheelId() {
        return wheelId;
    }

    /**
     * Returns the drawn entry's identifier, or {@code null} if it has since been removed.
     *
     * @return the entry's UUID, or {@code null}
     */
    public UUID getEntryId() {
        return entryId;
    }

    /**
     * Returns the drawn entry's display label, frozen at draw time.
     *
     * @return the label
     */
    public String getEntryLabel() {
        return entryLabel;
    }

    /**
     * Returns the timestamp of the draw.
     *
     * @return the drawnAt instant
     */
    public Instant getDrawnAt() {
        return drawnAt;
    }
}
