package fr.pivot.collaboratif.session;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;

import java.time.Instant;
import java.util.UUID;

/**
 * The single active activity of a {@link Session} (EN19.1).
 *
 * <p>This socle maps exactly one {@link Activity} per {@link Session} ({@code type} is fixed at
 * session creation, no multi-activity sequence within one session) — kept as a distinct entity
 * purely to absorb a future multi-activity evolution without a breaking migration
 * (US19.1.1 §Notes d'implémentation), created alongside the session it belongs to.
 */
@Entity
@Table(name = "session_activity", schema = "collaboratif")
public class Activity {

    /** Primary key generated by the database via UUID strategy — never client-supplied. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Owning session; unique — one activity per session in this socle. */
    @Column(name = "session_id", nullable = false, updatable = false, unique = true)
    private UUID sessionId;

    /** Activity type — mirrors the owning {@link Session#getType()} at creation time. */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20, updatable = false)
    private SessionType type;

    /** Timestamp when this activity was first persisted. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** No-arg constructor required by JPA. */
    protected Activity() {
    }

    /**
     * Creates the single activity for a newly-created session.
     *
     * @param sessionId the owning session's UUID
     * @param type      the activity type, mirroring the session's own type
     */
    public Activity(final UUID sessionId, final SessionType type) {
        this.sessionId = sessionId;
        this.type = type;
    }

    /**
     * Sets {@code createdAt} before the first insert, when not already set.
     */
    @PrePersist
    public void prePersist() {
        if (this.createdAt == null) {
            this.createdAt = Instant.now();
        }
    }

    /**
     * Returns the activity's unique identifier.
     *
     * @return the UUID
     */
    public UUID getId() {
        return id;
    }

    /**
     * Returns the owning session's identifier.
     *
     * @return the session UUID
     */
    public UUID getSessionId() {
        return sessionId;
    }

    /**
     * Returns the activity type.
     *
     * @return the type
     */
    public SessionType getType() {
        return type;
    }

    /**
     * Returns the creation timestamp.
     *
     * @return the createdAt instant
     */
    public Instant getCreatedAt() {
        return createdAt;
    }
}
