package fr.pivot.collaboratif.session;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;

import java.time.Instant;
import java.util.UUID;

/**
 * A participant of a {@link Session}, either an authenticated PIVOT user or an anonymous
 * {@code ROLE_GUEST} (US19.2.1).
 *
 * <p>{@code userId} is {@code null} for a guest, non-null for an authenticated participant.
 * {@code guestToken} is the reverse: an opaque, sealed, session-scoped credential set only for
 * guests, {@code null} for authenticated participants. A guest token is never valid on any other
 * session and never transformable into a real account.
 */
@Entity
@Table(name = "session_participant", schema = "collaboratif")
public class Participant {

    /** Primary key generated by the database via UUID strategy — never client-supplied. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Owning session; cascades on session deletion. */
    @Column(name = "session_id", nullable = false, updatable = false)
    private UUID sessionId;

    /** Authenticated participant's identity, or {@code null} for an anonymous guest. */
    @Column(name = "user_id", updatable = false)
    private Long userId;

    /**
     * Opaque, sealed, session-scoped guest credential, or {@code null} for an authenticated
     * participant.
     */
    @Column(name = "guest_token", length = 100, updatable = false)
    private String guestToken;

    /** Display name for this session — may differ from the account's own profile name. */
    @Column(name = "display_name", nullable = false, length = 40)
    private String displayName;

    /** Timestamp this participant joined the session. */
    @Column(name = "joined_at", nullable = false, updatable = false)
    private Instant joinedAt;

    /**
     * Timestamp of the last guest heartbeat — only meaningful for guests, drives guest-token
     * expiry (rolling TTL, see {@code SessionParticipantService#heartbeat}).
     */
    @Column(name = "last_heartbeat_at")
    private Instant lastHeartbeatAt;

    /**
     * This participant's role (US47.2.1) — {@code PLAYER} for every session created before this
     * field existed and for every non-{@code POSTIT_RUSH} session type; {@code SPECTATOR} only for
     * a {@code POSTIT_RUSH} joiner admitted past the room's hard capacity.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "role", nullable = false, length = 20)
    private ParticipantRole role = ParticipantRole.PLAYER;

    /** No-arg constructor required by JPA. */
    protected Participant() {
    }

    /**
     * Full constructor for creating a new {@code PLAYER} participant.
     *
     * @param sessionId   the owning session's UUID
     * @param userId      the authenticated user's id, or {@code null} for a guest
     * @param guestToken  the sealed guest token, or {@code null} for an authenticated participant
     * @param displayName display name for this session (1-40 chars)
     * @param now         timestamp used for {@code joinedAt} (and {@code lastHeartbeatAt} for guests)
     */
    public Participant(
            final UUID sessionId,
            final Long userId,
            final String guestToken,
            final String displayName,
            final Instant now) {
        this.sessionId = sessionId;
        this.userId = userId;
        this.guestToken = guestToken;
        this.displayName = displayName;
        this.joinedAt = now;
        if (guestToken != null) {
            this.lastHeartbeatAt = now;
        }
    }

    /**
     * Full constructor for creating a participant with an explicit role (US47.2.1
     * {@code POSTIT_RUSH} hard-capacity spectator fallback).
     *
     * @param sessionId   the owning session's UUID
     * @param userId      the authenticated user's id, or {@code null} for a guest
     * @param guestToken  the sealed guest token, or {@code null} for an authenticated participant
     * @param displayName display name for this session (1-40 chars)
     * @param now         timestamp used for {@code joinedAt} (and {@code lastHeartbeatAt} for guests)
     * @param role        the participant's role; {@code null} treated as {@link ParticipantRole#PLAYER}
     */
    public Participant(
            final UUID sessionId,
            final Long userId,
            final String guestToken,
            final String displayName,
            final Instant now,
            final ParticipantRole role) {
        this(sessionId, userId, guestToken, displayName, now);
        this.role = role == null ? ParticipantRole.PLAYER : role;
    }

    /**
     * Sets {@code joinedAt} before the first insert, when not already set.
     */
    @PrePersist
    public void prePersist() {
        if (this.joinedAt == null) {
            this.joinedAt = Instant.now();
        }
    }

    /**
     * Returns whether this participant is an anonymous guest.
     *
     * @return {@code true} if {@code userId} is {@code null}
     */
    public boolean isGuest() {
        return userId == null;
    }

    /**
     * Returns the participant's unique identifier.
     *
     * @return the UUID
     */
    public UUID getId() {
        return id;
    }

    /**
     * Returns the owning session's identifier.
     *
     * @return the session UUID
     */
    public UUID getSessionId() {
        return sessionId;
    }

    /**
     * Returns the authenticated user's identifier.
     *
     * @return the user's {@code public.users.id}, or {@code null} for a guest
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * Returns the guest token.
     *
     * @return the opaque guest token, or {@code null} for an authenticated participant
     */
    public String getGuestToken() {
        return guestToken;
    }

    /**
     * Returns the display name for this session.
     *
     * @return the display name
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Returns when this participant joined.
     *
     * @return the joinedAt instant
     */
    public Instant getJoinedAt() {
        return joinedAt;
    }

    /**
     * Returns the last guest heartbeat instant.
     *
     * @return the lastHeartbeatAt instant, or {@code null}
     */
    public Instant getLastHeartbeatAt() {
        return lastHeartbeatAt;
    }

    /**
     * Refreshes the guest heartbeat timestamp (rolling TTL).
     *
     * @param now the new heartbeat instant
     */
    public void refreshHeartbeat(final Instant now) {
        this.lastHeartbeatAt = now;
    }

    /**
     * Returns this participant's role.
     *
     * @return the role, never {@code null}
     */
    public ParticipantRole getRole() {
        return role;
    }
}
