package fr.pivot.collaboratif.session;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.time.Instant;
import java.util.UUID;

/**
 * A live interactive session (E19 — QUIZ/POLL/WORDCLOUD/BRAINSTORM/QA/VOTE), joined by
 * participants via a short {@link #joinCode} (US19.1.1).
 *
 * <p>Architecturally independent from {@code fr.pivot.collaboratif.whiteboard.quiz.QuizSession}/
 * {@code .vote.VoteSession} — those are hard-{@code boardId}-scoped whiteboard facilitation
 * features, not a standalone session concept. This module never references a board.
 *
 * <p>{@code teamId} is optional: a session may be created without a team for individual use — it
 * only affects visibility/listing ({@code GET /sessions}), never lifecycle authorization (see
 * {@code SessionAccessService#resolveSessionForOwnerOrAdmin}, US19.1.2).
 */
@Entity
@Table(name = "session", schema = "collaboratif")
public class Session {

    /** Primary key generated by the database via UUID strategy — never client-supplied. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Tenant owning this session; used for multi-tenant isolation. */
    @Column(name = "tenant_id", nullable = false, updatable = false)
    private Long tenantId;

    /** Optional owning team's {@code public.teams.id} — affects visibility only, never auth. */
    @Column(name = "team_id")
    private Long teamId;

    /** Human-readable session title; maximum 120 characters enforced at the API layer. */
    @Column(nullable = false, length = 120)
    private String title;

    /** Fixed activity type, set at creation and never changed. */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20, updatable = false)
    private SessionType type;

    /** Lifecycle status; {@link SessionStatus#DRAFT} at creation. */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private SessionStatus status = SessionStatus.DRAFT;

    /**
     * 6-character alphanumeric join code, unique among non-{@link SessionStatus#COMPLETED}
     * sessions of the tenant (see {@code uq_session_join_code_active}, {@link JoinCodeGenerator}).
     */
    @Column(name = "join_code", nullable = false, length = 6)
    private String joinCode;

    /**
     * Type-dependent configuration blob, stored as raw JSON text (JSONB column). Its shape
     * depends on {@link #type} — see each activity's own service for validation.
     */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(columnDefinition = "jsonb")
    private String config;

    /** User who created this session. */
    @Column(name = "created_by", nullable = false, updatable = false)
    private Long createdBy;

    /** Timestamp when this session was first persisted. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** Timestamp of the last update; refreshed automatically before every update. */
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /** Timestamp the session transitioned to {@link SessionStatus#LIVE} for the first time. */
    @Column(name = "started_at")
    private Instant startedAt;

    /** Timestamp the session transitioned to {@link SessionStatus#COMPLETED}. */
    @Column(name = "ended_at")
    private Instant endedAt;

    /** No-arg constructor required by JPA. */
    protected Session() {
    }

    /**
     * Full constructor for creating a new session.
     *
     * @param tenantId  owning tenant's {@code public.tenants.id}
     * @param teamId    optional owning team's {@code public.teams.id}, or {@code null}
     * @param title     session title (max 120 chars)
     * @param type      fixed activity type
     * @param joinCode  pre-generated unique join code
     * @param config    initial config blob (raw JSON), never {@code null}
     * @param createdBy creating user's {@code public.users.id}
     * @param now       timestamp used for both {@code createdAt} and {@code updatedAt}
     */
    public Session(
            final Long tenantId,
            final Long teamId,
            final String title,
            final SessionType type,
            final String joinCode,
            final String config,
            final Long createdBy,
            final Instant now) {
        this.tenantId = tenantId;
        this.teamId = teamId;
        this.title = title;
        this.type = type;
        this.joinCode = joinCode;
        this.config = config;
        this.createdBy = createdBy;
        this.createdAt = now;
        this.updatedAt = now;
    }

    /**
     * Sets {@code createdAt}/{@code updatedAt} before the first insert, when not already set.
     */
    @PrePersist
    public void prePersist() {
        Instant now = Instant.now();
        if (this.createdAt == null) {
            this.createdAt = now;
        }
        if (this.updatedAt == null) {
            this.updatedAt = now;
        }
    }

    /**
     * Refreshes {@code updatedAt} before every update.
     */
    @PreUpdate
    public void preUpdate() {
        this.updatedAt = Instant.now();
    }

    /**
     * Returns the session's unique identifier.
     *
     * @return the UUID
     */
    public UUID getId() {
        return id;
    }

    /**
     * Returns the tenant identifier.
     *
     * @return the tenant's {@code public.tenants.id}
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * Returns the optional owning team identifier.
     *
     * @return the team's {@code public.teams.id}, or {@code null}
     */
    public Long getTeamId() {
        return teamId;
    }

    /**
     * Returns the session title.
     *
     * @return the title
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the session title.
     *
     * @param title the new title
     */
    public void setTitle(final String title) {
        this.title = title;
    }

    /**
     * Returns the fixed activity type.
     *
     * @return the type
     */
    public SessionType getType() {
        return type;
    }

    /**
     * Returns the lifecycle status.
     *
     * @return the status
     */
    public SessionStatus getStatus() {
        return status;
    }

    /**
     * Sets the lifecycle status.
     *
     * @param status the new status
     */
    public void setStatus(final SessionStatus status) {
        this.status = status;
    }

    /**
     * Returns the join code.
     *
     * @return the 6-character join code
     */
    public String getJoinCode() {
        return joinCode;
    }

    /**
     * Returns the type-dependent config blob.
     *
     * @return raw JSON config, or {@code null}
     */
    public String getConfig() {
        return config;
    }

    /**
     * Replaces the type-dependent config blob.
     *
     * @param config the new raw JSON config
     */
    public void setConfig(final String config) {
        this.config = config;
    }

    /**
     * Returns the creating user's identifier.
     *
     * @return the creator's {@code public.users.id}
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * Returns the creation timestamp.
     *
     * @return the createdAt instant
     */
    public Instant getCreatedAt() {
        return createdAt;
    }

    /**
     * Returns the last-updated timestamp.
     *
     * @return the updatedAt instant
     */
    public Instant getUpdatedAt() {
        return updatedAt;
    }

    /**
     * Returns when this session first went {@link SessionStatus#LIVE}.
     *
     * @return the startedAt instant, or {@code null} if never started
     */
    public Instant getStartedAt() {
        return startedAt;
    }

    /**
     * Sets when this session went {@link SessionStatus#LIVE}.
     *
     * @param startedAt the start instant
     */
    public void setStartedAt(final Instant startedAt) {
        this.startedAt = startedAt;
    }

    /**
     * Returns when this session was completed.
     *
     * @return the endedAt instant, or {@code null} while not completed
     */
    public Instant getEndedAt() {
        return endedAt;
    }

    /**
     * Sets when this session was completed.
     *
     * @param endedAt the end instant
     */
    public void setEndedAt(final Instant endedAt) {
        this.endedAt = endedAt;
    }
}
