package fr.pivot.collaboratif.session.brainstorm;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;

import java.time.Instant;
import java.util.UUID;

/**
 * A single participant-authored post-it on a BRAINSTORM board (US19.3.4) — editable and deletable
 * only by its author (enforced by the service), and groupable into a free-text {@code category} by
 * the facilitator.
 */
@Entity
@Table(name = "session_brainstorm_card", schema = "collaboratif")
public class SessionBrainstormCard {

    /** Primary key generated by the database via UUID strategy — never client-supplied. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Owning session; cascades on session deletion. */
    @Column(name = "session_id", nullable = false, updatable = false)
    private UUID sessionId;

    /** The authoring participant — the only one allowed to edit/delete this card. */
    @Column(name = "participant_id", nullable = false, updatable = false)
    private UUID participantId;

    /** The post-it text, stored verbatim — escaping is a render-time (frontend) concern. */
    @Column(nullable = false, length = 280)
    private String text;

    /** The post-it colour, from the fixed {@link BrainstormCardColor} palette. */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private BrainstormCardColor color;

    /** Facilitator-assigned grouping label, or {@code null} when uncategorized. */
    @Column(length = 80)
    private String category;

    /** Creation timestamp, used as the stable list ordering. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** No-arg constructor required by JPA. */
    protected SessionBrainstormCard() {
    }

    /**
     * Creates a new, uncategorized card.
     *
     * @param sessionId     the owning session's UUID
     * @param participantId the authoring participant's UUID
     * @param text          the post-it text
     * @param color         the post-it colour
     * @param now           the creation timestamp
     */
    public SessionBrainstormCard(
            final UUID sessionId, final UUID participantId, final String text,
            final BrainstormCardColor color, final Instant now) {
        this.sessionId = sessionId;
        this.participantId = participantId;
        this.text = text;
        this.color = color;
        this.createdAt = now;
    }

    /** Sets {@code createdAt} before the first insert, when not already set. */
    @PrePersist
    public void prePersist() {
        if (this.createdAt == null) {
            this.createdAt = Instant.now();
        }
    }

    /**
     * Replaces the editable content (author action).
     *
     * @param text  the new text
     * @param color the new colour
     */
    public void edit(final String text, final BrainstormCardColor color) {
        this.text = text;
        this.color = color;
    }

    /**
     * Sets the facilitator's grouping label.
     *
     * @param category the new category, or {@code null} to clear it
     */
    public void categorize(final String category) {
        this.category = category;
    }

    public UUID getId() {
        return id;
    }

    public UUID getSessionId() {
        return sessionId;
    }

    public UUID getParticipantId() {
        return participantId;
    }

    public String getText() {
        return text;
    }

    public BrainstormCardColor getColor() {
        return color;
    }

    public String getCategory() {
        return category;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }
}
