package fr.pivot.collaboratif.whiteboard.board;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * JPA entity representing a whiteboard board.
 *
 * <p>Boards belong to a single tenant and always have one owner. The {@code visibility}
 * field defaults to {@link BoardVisibility#PRIVATE}. Timestamps are managed automatically
 * via JPA lifecycle callbacks.
 */
@Entity
@Table(name = "board", schema = "collaboratif")
public class Board {

    /** Primary key generated by the database via UUID strategy. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Human-readable board title; maximum 100 characters enforced at the API layer. */
    @Column(name = "title", nullable = false, length = 100)
    private String title;

    /** Tenant that owns this board; used for multi-tenant isolation. */
    @Column(name = "tenant_id", nullable = false)
    private Long tenantId;

    /** User who created and owns this board. */
    @Column(name = "owner_id", nullable = false)
    private Long ownerId;

    /** Visibility of the board; defaults to {@link BoardVisibility#PRIVATE}. */
    @Enumerated(EnumType.STRING)
    @Column(name = "visibility", nullable = false, length = 20)
    private BoardVisibility visibility = BoardVisibility.PRIVATE;

    /** Timestamp when the board was first persisted. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** Timestamp of the last update; refreshed automatically before every update. */
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /**
     * Timestamp when the board was soft-deleted (moved to the trash), or {@code null}
     * when the board is not in the trash (US08.1.7).
     */
    @Column(name = "deleted_at")
    private Instant deletedAt;

    /** Optional free-text description of the board, up to 500 characters (US08.2.4). */
    @Column(name = "description")
    private String description;

    /** Optional URL of a cover image for the board (US08.2.4). */
    @Column(name = "cover_image")
    private String coverImage;

    /** Optional maximum number of simultaneous participants, or {@code null} for unlimited
     * (US08.2.4). */
    @Column(name = "max_participants")
    private Integer maxParticipants;

    /** Whitelisted activity codes enabled on this board; empty by default (US08.2.4). */
    @JdbcTypeCode(SqlTypes.ARRAY)
    @Column(name = "enabled_activities", columnDefinition = "text[]", nullable = false)
    private List<String> enabledActivities = new ArrayList<>();

    /** No-arg constructor required by JPA. */
    protected Board() {
    }

    /**
     * Full constructor for creating a new board with all fields.
     *
     * @param title    board title (max 100 chars)
     * @param tenantId owning tenant's {@code public.tenants.id}
     * @param ownerId  creating user's {@code public.users.id}
     * @param now      timestamp used for both {@code createdAt} and {@code updatedAt}
     */
    public Board(
            final String title,
            final Long tenantId,
            final Long ownerId,
            final Instant now) {
        this.title = title;
        this.tenantId = tenantId;
        this.ownerId = ownerId;
        this.visibility = BoardVisibility.PRIVATE;
        this.createdAt = now;
        this.updatedAt = now;
    }

    /**
     * Sets {@code createdAt} and {@code updatedAt} to the current instant before
     * the first insert, when the fields have not already been set.
     */
    @PrePersist
    public void prePersist() {
        Instant now = Instant.now();
        if (this.createdAt == null) {
            this.createdAt = now;
        }
        if (this.updatedAt == null) {
            this.updatedAt = now;
        }
    }

    /**
     * Refreshes {@code updatedAt} to the current instant before every update.
     */
    @PreUpdate
    public void preUpdate() {
        this.updatedAt = Instant.now();
    }

    /**
     * Returns the board's unique identifier.
     *
     * @return the UUID
     */
    public UUID getId() {
        return id;
    }

    /**
     * Returns the board title.
     *
     * @return the title
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the board title.
     *
     * @param title the title to set
     */
    public void setTitle(final String title) {
        this.title = title;
    }

    /**
     * Returns the tenant identifier.
     *
     * @return the tenant's {@code public.tenants.id}
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * Returns the owner user identifier.
     *
     * @return the owner's {@code public.users.id}
     */
    public Long getOwnerId() {
        return ownerId;
    }

    /**
     * Returns the board visibility.
     *
     * @return the visibility
     */
    public BoardVisibility getVisibility() {
        return visibility;
    }

    /**
     * Returns the creation timestamp.
     *
     * @return the createdAt instant
     */
    public Instant getCreatedAt() {
        return createdAt;
    }

    /**
     * Returns the last-updated timestamp.
     *
     * @return the updatedAt instant
     */
    public Instant getUpdatedAt() {
        return updatedAt;
    }

    /**
     * Sets the last-updated timestamp (normally managed by {@link #preUpdate()}).
     *
     * @param updatedAt the instant to set
     */
    public void setUpdatedAt(final Instant updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * Returns the timestamp when the board was soft-deleted, or {@code null} if it is not
     * in the trash.
     *
     * @return the deletedAt instant, or {@code null}
     */
    public Instant getDeletedAt() {
        return deletedAt;
    }

    /**
     * Sets the soft-delete timestamp. Passing {@code null} restores the board out of the
     * trash (US08.1.7).
     *
     * @param deletedAt the instant to set, or {@code null} to restore
     */
    public void setDeletedAt(final Instant deletedAt) {
        this.deletedAt = deletedAt;
    }

    /**
     * Returns whether the board is currently in the trash.
     *
     * @return {@code true} if {@code deletedAt} is set
     */
    public boolean isDeleted() {
        return deletedAt != null;
    }

    /**
     * Returns the board's optional description.
     *
     * @return the description, or {@code null}
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the board's description.
     *
     * @param description the description to set, or {@code null} to clear it
     */
    public void setDescription(final String description) {
        this.description = description;
    }

    /**
     * Returns the board's optional cover image URL.
     *
     * @return the cover image URL, or {@code null}
     */
    public String getCoverImage() {
        return coverImage;
    }

    /**
     * Sets the board's cover image URL.
     *
     * @param coverImage the cover image URL to set, or {@code null} to clear it
     */
    public void setCoverImage(final String coverImage) {
        this.coverImage = coverImage;
    }

    /**
     * Returns the maximum number of simultaneous participants, or {@code null} if unlimited.
     *
     * @return the max participants, or {@code null}
     */
    public Integer getMaxParticipants() {
        return maxParticipants;
    }

    /**
     * Sets the maximum number of simultaneous participants.
     *
     * @param maxParticipants the max participants to set, or {@code null} for unlimited
     */
    public void setMaxParticipants(final Integer maxParticipants) {
        this.maxParticipants = maxParticipants;
    }

    /**
     * Returns the whitelisted activity codes enabled on this board.
     *
     * @return the enabled activities (never {@code null}, possibly empty)
     */
    public List<String> getEnabledActivities() {
        return enabledActivities;
    }

    /**
     * Sets the whitelisted activity codes enabled on this board.
     *
     * @param enabledActivities the enabled activities to set; {@code null} is normalized to
     *                          an empty list
     */
    public void setEnabledActivities(final List<String> enabledActivities) {
        this.enabledActivities = enabledActivities != null ? enabledActivities : new ArrayList<>();
    }
}
