package fr.pivot.collaboratif.whiteboard.canvas;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.time.Instant;
import java.util.UUID;

/**
 * JPA entity representing one custom field defined on a whiteboard board (US08.10.1) — a
 * board-level column (typed {@link FieldType}) that every card of the board can later carry a
 * value for (the value itself lives in {@link CardFieldValue}, populated by US08.10.2).
 *
 * <p>Same durable current-state model as {@link Frame}/{@link Card}: a single row per field,
 * created by {@code boardfield:create}, mutated in place by {@code boardfield:update}, and removed
 * by {@code boardfield:delete} (see {@link CanvasActionService}). A field's list is part of the
 * {@code board:state} reply sent to a late-joining participant on {@code JOIN}.
 *
 * <p>Mirrors the frontend's {@code BoardField} model ({@code board.types.ts}):
 * {@code {id, boardId, name, emoji, type, options, order}} — see
 * {@link fr.pivot.collaboratif.whiteboard.canvas.dto.BoardFieldDto} for the wire shape.
 *
 * <p>The {@code type} is fixed at creation and never modified afterwards (acceptance criterion);
 * only {@code name}/{@code emoji}/{@code options}/{@code order} are mutable. {@code options} holds a
 * JSON array of allowed values for a {@link FieldType#SELECT} field and is {@code null} otherwise.
 */
@Entity
@Table(name = "board_field", schema = "collaboratif")
public class BoardField {

    /** Primary key generated by the database via UUID strategy — never client-supplied. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Board this field belongs to; cascades on board deletion (FK {@code ON DELETE CASCADE}). */
    @Column(name = "board_id", nullable = false, updatable = false)
    private UUID boardId;

    /** Tenant owning the board this field belongs to — for tenant-scoped safety. */
    @Column(name = "tenant_id", nullable = false, updatable = false)
    private Long tenantId;

    /** Human-readable field name (user-editable). */
    @Column(name = "name", nullable = false)
    private String name;

    /** Optional emoji shown alongside the field name; {@code null} if none. */
    @Column(name = "emoji", length = 32)
    private String emoji;

    /** Typed discriminant; fixed at creation, never modified afterwards (acceptance criterion). */
    @Enumerated(EnumType.STRING)
    @Column(name = "type", nullable = false, length = 20, updatable = false)
    private FieldType type;

    /**
     * JSON array (JSONB) of allowed values for a {@link FieldType#SELECT} field; {@code null} for
     * every other type. Stored as an opaque JSON string, mirroring {@link Card}'s {@code meta}.
     */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "options")
    private String options;

    /** Display order among the board's fields; defaults to 0. Maps to reserved-word-safe column
     * {@code field_order} ({@code order} is a SQL reserved word). */
    @Column(name = "field_order", nullable = false)
    private int order;

    /** Timestamp when this field was first persisted. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** No-arg constructor required by JPA. */
    protected BoardField() {
    }

    /**
     * Creates a new board field.
     *
     * @param boardId  the owning board's UUID
     * @param tenantId the owning board's tenant id
     * @param name     the field name
     * @param emoji    the optional emoji, or {@code null}
     * @param type     the typed discriminant (fixed for the field's lifetime)
     * @param options  the JSON array of allowed values for a SELECT field, or {@code null}
     * @param order    the display order
     * @param now      timestamp used for {@code createdAt}
     */
    public BoardField(
            final UUID boardId,
            final Long tenantId,
            final String name,
            final String emoji,
            final FieldType type,
            final String options,
            final int order,
            final Instant now) {
        this.boardId = boardId;
        this.tenantId = tenantId;
        this.name = name;
        this.emoji = emoji;
        this.type = type;
        this.options = options;
        this.order = order;
        this.createdAt = now;
    }

    /**
     * Sets {@code createdAt} to the current instant before the first insert, when not already set.
     */
    @PrePersist
    public void prePersist() {
        if (this.createdAt == null) {
            this.createdAt = Instant.now();
        }
    }

    /**
     * Returns the field's unique identifier.
     *
     * @return the UUID
     */
    public UUID getId() {
        return id;
    }

    /**
     * Returns the owning board's identifier.
     *
     * @return the board UUID
     */
    public UUID getBoardId() {
        return boardId;
    }

    /**
     * Returns the owning tenant's identifier.
     *
     * @return the tenant id
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * Returns the field name.
     *
     * @return the name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the field name.
     *
     * @param name the name to set
     */
    public void setName(final String name) {
        this.name = name;
    }

    /**
     * Returns the emoji.
     *
     * @return the emoji, or {@code null} if none
     */
    public String getEmoji() {
        return emoji;
    }

    /**
     * Sets the emoji.
     *
     * @param emoji the emoji to set, or {@code null}
     */
    public void setEmoji(final String emoji) {
        this.emoji = emoji;
    }

    /**
     * Returns the typed discriminant.
     *
     * @return the {@link FieldType}
     */
    public FieldType getType() {
        return type;
    }

    /**
     * Returns the JSON array of allowed values (SELECT fields only).
     *
     * @return the options JSON string, or {@code null}
     */
    public String getOptions() {
        return options;
    }

    /**
     * Sets the JSON array of allowed values.
     *
     * @param options the options JSON string to set, or {@code null}
     */
    public void setOptions(final String options) {
        this.options = options;
    }

    /**
     * Returns the display order.
     *
     * @return the order
     */
    public int getOrder() {
        return order;
    }

    /**
     * Sets the display order.
     *
     * @param order the order to set
     */
    public void setOrder(final int order) {
        this.order = order;
    }

    /**
     * Returns the creation timestamp.
     *
     * @return the {@code createdAt} instant
     */
    public Instant getCreatedAt() {
        return createdAt;
    }
}
