package fr.pivot.collaboratif.whiteboard.canvas;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

import java.util.UUID;

/**
 * JPA entity holding one card's value for one custom board field ({@link BoardField}, US08.10.1) —
 * the intersection of a {@link Card} and a {@link BoardField}, unique per {@code (card, field)}
 * pair.
 *
 * <p>Created now so that (a) deleting a {@link BoardField} cascades away its values via the FK
 * {@code ON DELETE CASCADE}, and (b) US08.10.2 can build the set/clear handlers on top of it. The
 * {@code value} is a plain string interpreted according to the field's {@link FieldType}. This
 * entity's own set/clear STOMP handlers are out of scope for US08.10.1 — only the schema, the
 * cascade, and a minimal lookup exist here.
 */
@Entity
@Table(
        name = "card_field_value",
        schema = "collaboratif",
        uniqueConstraints = @UniqueConstraint(columnNames = {"card_id", "field_id"}))
public class CardFieldValue {

    /** Primary key generated by the database via UUID strategy — never client-supplied. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Card this value belongs to; cascades on card deletion (FK {@code ON DELETE CASCADE}). */
    @Column(name = "card_id", nullable = false, updatable = false)
    private UUID cardId;

    /** Field this value is for; cascades on field deletion (FK {@code ON DELETE CASCADE}). */
    @Column(name = "field_id", nullable = false, updatable = false)
    private UUID fieldId;

    /** The stored value, interpreted according to the field's {@link FieldType}. */
    @Column(name = "value", nullable = false)
    private String value;

    /** No-arg constructor required by JPA. */
    protected CardFieldValue() {
    }

    /**
     * Creates a new card field value.
     *
     * @param cardId  the card's UUID
     * @param fieldId the field's UUID
     * @param value   the stored value
     */
    public CardFieldValue(final UUID cardId, final UUID fieldId, final String value) {
        this.cardId = cardId;
        this.fieldId = fieldId;
        this.value = value;
    }

    /**
     * Returns the value's unique identifier.
     *
     * @return the UUID
     */
    public UUID getId() {
        return id;
    }

    /**
     * Returns the owning card's identifier.
     *
     * @return the card UUID
     */
    public UUID getCardId() {
        return cardId;
    }

    /**
     * Returns the field's identifier.
     *
     * @return the field UUID
     */
    public UUID getFieldId() {
        return fieldId;
    }

    /**
     * Returns the stored value.
     *
     * @return the value
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the stored value (for the upsert path in US08.10.2).
     *
     * @param value the value to set
     */
    public void setValue(final String value) {
        this.value = value;
    }
}
