package fr.pivot.collaboratif.whiteboard.canvas;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.time.Instant;
import java.util.UUID;

/**
 * JPA entity representing the current, mutable state of one whiteboard canvas object (EN08.4).
 *
 * <p>Unlike {@link CanvasEvent} — an append-only event log where every {@code DRAW} is a new
 * row — a {@code Card} is a single row per object, updated in place by {@code CARD_MOVE},
 * {@code CARD_RESIZE}, {@code CARD_UPDATE}, {@code CARD_RECOLOR} and {@code CARD_LAYER} actions
 * (see {@link CanvasActionService}). This is the durable state a late-joining participant is
 * brought up to date on (the {@code board-state} reply on {@code JOIN}), which the pure
 * event-log {@code canvas_event} table could not directly support.
 *
 * <p>Default field values ({@code posX}/{@code posY} = 0, {@code width} = 192,
 * {@code height} = 128, {@code color} = {@code #FFEB3B}, {@code layer} = 1, {@code locked} =
 * {@code false}) match the reference whiteboard's card defaults (parity spec §1.5) exactly.
 */
@Entity
@Table(name = "card", schema = "collaboratif")
public class Card {

    /** Primary key generated by the database via UUID strategy — never client-supplied. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Board this card belongs to; cascades on board deletion (FK {@code ON DELETE CASCADE}). */
    @Column(name = "board_id", nullable = false, updatable = false)
    private UUID boardId;

    /** Tenant owning the board this card belongs to — for tenant-scoped queries. */
    @Column(name = "tenant_id", nullable = false, updatable = false)
    private Long tenantId;

    /** Typed discriminant; falls back to {@link CardType#TEXT} if an unknown value is submitted. */
    @Enumerated(EnumType.STRING)
    @Column(name = "type", nullable = false, length = 20)
    private CardType type;

    /** Type-specific content (plain/rich text, image URL, table cell data, stroke path…). */
    @Column(name = "content", nullable = false)
    private String content;

    /**
     * Opaque JSONB metadata cache — currently the OpenGraph preview
     * ({@code title}/{@code description}/{@code image}/{@code siteName}) for {@link
     * CardType#LINK} cards, populated asynchronously (US08.6.5, out of scope for EN08.4).
     * {@code null} until enriched.
     */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "meta")
    private String meta;

    /** X position on the canvas; defaults to 0. */
    @Column(name = "pos_x", nullable = false)
    private double posX;

    /** Y position on the canvas; defaults to 0. */
    @Column(name = "pos_y", nullable = false)
    private double posY;

    /** Card width in canvas units; defaults to 192. */
    @Column(name = "width", nullable = false)
    private double width = 192;

    /** Card height in canvas units; defaults to 128. */
    @Column(name = "height", nullable = false)
    private double height = 128;

    /** Card colour (hex); defaults to {@code #FFEB3B} (the reference whiteboard's sticky-note yellow). */
    @Column(name = "color", nullable = false, length = 20)
    private String color = "#FFEB3B";

    /** Group this card belongs to, or {@code null} if ungrouped. */
    @Column(name = "group_id")
    private UUID groupId;

    /** Colour applied to this card's group outline, or {@code null}. */
    @Column(name = "group_color", length = 20)
    private String groupColor;

    /** When {@code true}, {@code CARD_MOVE}/{@code CARD_RESIZE}/{@code CARD_UPDATE}/{@code CARD_RECOLOR}
     * are refused (see {@link CanvasActionService}); {@code CARD_LAYER} is not affected. */
    @Column(name = "locked", nullable = false)
    private boolean locked;

    /** Z-order among cards/frames on the same board; defaults to 1. */
    @Column(name = "layer", nullable = false)
    private int layer = 1;

    /** Timestamp when this card was first persisted. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** Timestamp of the last update; refreshed automatically before every update. */
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /** No-arg constructor required by JPA. */
    protected Card() {
    }

    /**
     * Creates a new card with the given content and position, taking every other field's
     * default value.
     *
     * @param boardId  the owning board's UUID
     * @param tenantId the owning board's tenant id
     * @param type     the card's typed discriminant
     * @param content  the type-specific content
     * @param posX     initial X position
     * @param posY     initial Y position
     * @param now      timestamp used for both {@code createdAt} and {@code updatedAt}
     */
    public Card(
            final UUID boardId,
            final Long tenantId,
            final CardType type,
            final String content,
            final double posX,
            final double posY,
            final Instant now) {
        this.boardId = boardId;
        this.tenantId = tenantId;
        this.type = type;
        this.content = content;
        this.posX = posX;
        this.posY = posY;
        this.createdAt = now;
        this.updatedAt = now;
    }

    /**
     * Sets {@code createdAt} and {@code updatedAt} to the current instant before
     * the first insert, when the fields have not already been set.
     */
    @PrePersist
    public void prePersist() {
        Instant now = Instant.now();
        if (this.createdAt == null) {
            this.createdAt = now;
        }
        if (this.updatedAt == null) {
            this.updatedAt = now;
        }
    }

    /**
     * Refreshes {@code updatedAt} to the current instant before every update.
     */
    @PreUpdate
    public void preUpdate() {
        this.updatedAt = Instant.now();
    }

    /**
     * Returns the card's unique identifier.
     *
     * @return the UUID
     */
    public UUID getId() {
        return id;
    }

    /**
     * Returns the owning board's identifier.
     *
     * @return the board UUID
     */
    public UUID getBoardId() {
        return boardId;
    }

    /**
     * Returns the owning tenant's identifier.
     *
     * @return the tenant id
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * Returns the card's typed discriminant.
     *
     * @return the {@link CardType}
     */
    public CardType getType() {
        return type;
    }

    /**
     * Sets the card's typed discriminant.
     *
     * @param type the {@link CardType} to set
     */
    public void setType(final CardType type) {
        this.type = type;
    }

    /**
     * Returns the type-specific content.
     *
     * @return the content string
     */
    public String getContent() {
        return content;
    }

    /**
     * Sets the type-specific content.
     *
     * @param content the content to set
     */
    public void setContent(final String content) {
        this.content = content;
    }

    /**
     * Returns the opaque JSONB metadata cache.
     *
     * @return the meta JSON string, or {@code null} if not yet enriched
     */
    public String getMeta() {
        return meta;
    }

    /**
     * Sets the opaque JSONB metadata cache.
     *
     * @param meta the meta JSON string to set
     */
    public void setMeta(final String meta) {
        this.meta = meta;
    }

    /**
     * Returns the X position.
     *
     * @return the X position
     */
    public double getPosX() {
        return posX;
    }

    /**
     * Sets the X position.
     *
     * @param posX the X position to set
     */
    public void setPosX(final double posX) {
        this.posX = posX;
    }

    /**
     * Returns the Y position.
     *
     * @return the Y position
     */
    public double getPosY() {
        return posY;
    }

    /**
     * Sets the Y position.
     *
     * @param posY the Y position to set
     */
    public void setPosY(final double posY) {
        this.posY = posY;
    }

    /**
     * Returns the width.
     *
     * @return the width in canvas units
     */
    public double getWidth() {
        return width;
    }

    /**
     * Sets the width.
     *
     * @param width the width to set
     */
    public void setWidth(final double width) {
        this.width = width;
    }

    /**
     * Returns the height.
     *
     * @return the height in canvas units
     */
    public double getHeight() {
        return height;
    }

    /**
     * Sets the height.
     *
     * @param height the height to set
     */
    public void setHeight(final double height) {
        this.height = height;
    }

    /**
     * Returns the card colour.
     *
     * @return the hex colour string
     */
    public String getColor() {
        return color;
    }

    /**
     * Sets the card colour.
     *
     * @param color the hex colour string to set
     */
    public void setColor(final String color) {
        this.color = color;
    }

    /**
     * Returns the group identifier.
     *
     * @return the group UUID, or {@code null} if ungrouped
     */
    public UUID getGroupId() {
        return groupId;
    }

    /**
     * Sets the group identifier.
     *
     * @param groupId the group UUID to set, or {@code null} to ungroup
     */
    public void setGroupId(final UUID groupId) {
        this.groupId = groupId;
    }

    /**
     * Returns the group outline colour.
     *
     * @return the hex colour string, or {@code null}
     */
    public String getGroupColor() {
        return groupColor;
    }

    /**
     * Sets the group outline colour.
     *
     * @param groupColor the hex colour string to set, or {@code null}
     */
    public void setGroupColor(final String groupColor) {
        this.groupColor = groupColor;
    }

    /**
     * Returns whether this card is locked.
     *
     * @return {@code true} if locked
     */
    public boolean isLocked() {
        return locked;
    }

    /**
     * Sets whether this card is locked.
     *
     * @param locked the locked state to set
     */
    public void setLocked(final boolean locked) {
        this.locked = locked;
    }

    /**
     * Returns the Z-order layer.
     *
     * @return the layer
     */
    public int getLayer() {
        return layer;
    }

    /**
     * Sets the Z-order layer.
     *
     * @param layer the layer to set
     */
    public void setLayer(final int layer) {
        this.layer = layer;
    }

    /**
     * Returns the creation timestamp.
     *
     * @return the {@code createdAt} instant
     */
    public Instant getCreatedAt() {
        return createdAt;
    }

    /**
     * Returns the last-update timestamp.
     *
     * @return the {@code updatedAt} instant
     */
    public Instant getUpdatedAt() {
        return updatedAt;
    }
}
