package fr.pivot.collaboratif.whiteboard.canvas;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;

import java.time.Instant;
import java.util.UUID;

/**
 * JPA entity representing the current, mutable state of one whiteboard frame — a rectangular
 * container ("cadre"/section box) that groups an area of the canvas (EN08, Frames).
 *
 * <p>Same durable current-state model as {@link Card}: a single row per frame, updated in place
 * by {@code frame:move}, {@code frame:resize}, {@code frame:update} and {@code frame:layer}
 * actions (see {@link CanvasActionService}). This is the state a late-joining participant is
 * brought up to date on via the {@code board:state} reply on {@code JOIN}.
 *
 * <p>Mirrors the frontend's {@code Frame} model ({@code board.types.ts}):
 * {@code {id, boardId, title, posX, posY, width, height, color, active, layer}} — see
 * {@link fr.pivot.collaboratif.whiteboard.canvas.dto.FrameDto} for the wire shape.
 *
 * <p>Default field values ({@code posX}/{@code posY} = 0, {@code width} = 400,
 * {@code height} = 300, {@code title} = empty, {@code color} = {@code #94A3B8},
 * {@code active} = {@code false}, {@code layer} = 0) are server-authoritative — the frontend's
 * basic create sends only {@code {boardId, posX, posY}} and adopts whatever the server echoes
 * back on {@code frame:created}. {@code layer} defaults to 0 so frames sit behind cards
 * (default card layer 1).
 */
@Entity
@Table(name = "frame", schema = "collaboratif")
public class Frame {

    /** Primary key generated by the database via UUID strategy — never client-supplied. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Board this frame belongs to; cascades on board deletion (FK {@code ON DELETE CASCADE}). */
    @Column(name = "board_id", nullable = false, updatable = false)
    private UUID boardId;

    /** Tenant owning the board this frame belongs to — for tenant-scoped queries. */
    @Column(name = "tenant_id", nullable = false, updatable = false)
    private Long tenantId;

    /** X position on the canvas; defaults to 0. */
    @Column(name = "pos_x", nullable = false)
    private double posX;

    /** Y position on the canvas; defaults to 0. */
    @Column(name = "pos_y", nullable = false)
    private double posY;

    /** Frame width in canvas units; defaults to 400. */
    @Column(name = "width", nullable = false)
    private double width = 400;

    /** Frame height in canvas units; defaults to 300. */
    @Column(name = "height", nullable = false)
    private double height = 300;

    /** Frame title/label; defaults to an empty string (user-editable). */
    @Column(name = "title", nullable = false, length = 200)
    private String title = "";

    /** Frame colour (hex); defaults to {@code #94A3B8} (a neutral slate). */
    @Column(name = "color", nullable = false, length = 20)
    private String color = "#94A3B8";

    /** When {@code true}, dragging the frame carries its contained cards (frontend behaviour). */
    @Column(name = "active", nullable = false)
    private boolean active;

    /** Z-order among cards/frames on the same board; defaults to 0 (behind cards). */
    @Column(name = "layer", nullable = false)
    private int layer;

    /** Timestamp when this frame was first persisted. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** No-arg constructor required by JPA. */
    protected Frame() {
    }

    /**
     * Creates a new frame at the given position, taking every other field's default value.
     *
     * @param boardId  the owning board's UUID
     * @param tenantId the owning board's tenant id
     * @param posX     initial X position
     * @param posY     initial Y position
     * @param now      timestamp used for {@code createdAt}
     */
    public Frame(
            final UUID boardId,
            final Long tenantId,
            final double posX,
            final double posY,
            final Instant now) {
        this.boardId = boardId;
        this.tenantId = tenantId;
        this.posX = posX;
        this.posY = posY;
        this.createdAt = now;
    }

    /**
     * Sets {@code createdAt} to the current instant before the first insert, when not already set.
     */
    @PrePersist
    public void prePersist() {
        if (this.createdAt == null) {
            this.createdAt = Instant.now();
        }
    }

    /**
     * Returns the frame's unique identifier.
     *
     * @return the UUID
     */
    public UUID getId() {
        return id;
    }

    /**
     * Returns the owning board's identifier.
     *
     * @return the board UUID
     */
    public UUID getBoardId() {
        return boardId;
    }

    /**
     * Returns the owning tenant's identifier.
     *
     * @return the tenant id
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * Returns the X position.
     *
     * @return the X position
     */
    public double getPosX() {
        return posX;
    }

    /**
     * Sets the X position.
     *
     * @param posX the X position to set
     */
    public void setPosX(final double posX) {
        this.posX = posX;
    }

    /**
     * Returns the Y position.
     *
     * @return the Y position
     */
    public double getPosY() {
        return posY;
    }

    /**
     * Sets the Y position.
     *
     * @param posY the Y position to set
     */
    public void setPosY(final double posY) {
        this.posY = posY;
    }

    /**
     * Returns the width.
     *
     * @return the width in canvas units
     */
    public double getWidth() {
        return width;
    }

    /**
     * Sets the width.
     *
     * @param width the width to set
     */
    public void setWidth(final double width) {
        this.width = width;
    }

    /**
     * Returns the height.
     *
     * @return the height in canvas units
     */
    public double getHeight() {
        return height;
    }

    /**
     * Sets the height.
     *
     * @param height the height to set
     */
    public void setHeight(final double height) {
        this.height = height;
    }

    /**
     * Returns the frame title.
     *
     * @return the title
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the frame title.
     *
     * @param title the title to set
     */
    public void setTitle(final String title) {
        this.title = title;
    }

    /**
     * Returns the frame colour.
     *
     * @return the hex colour string
     */
    public String getColor() {
        return color;
    }

    /**
     * Sets the frame colour.
     *
     * @param color the hex colour string to set
     */
    public void setColor(final String color) {
        this.color = color;
    }

    /**
     * Returns whether this frame is active (carries its contained cards when dragged).
     *
     * @return {@code true} if active
     */
    public boolean isActive() {
        return active;
    }

    /**
     * Sets whether this frame is active.
     *
     * @param active the active state to set
     */
    public void setActive(final boolean active) {
        this.active = active;
    }

    /**
     * Returns the Z-order layer.
     *
     * @return the layer
     */
    public int getLayer() {
        return layer;
    }

    /**
     * Sets the Z-order layer.
     *
     * @param layer the layer to set
     */
    public void setLayer(final int layer) {
        this.layer = layer;
    }

    /**
     * Returns the creation timestamp.
     *
     * @return the {@code createdAt} instant
     */
    public Instant getCreatedAt() {
        return createdAt;
    }
}
