package fr.pivot.collaboratif.whiteboard.vote;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;

import java.time.Instant;
import java.util.UUID;

/**
 * JPA entity representing a single dot cast by a user on a card within a {@link VoteSession}.
 *
 * <p>Dot-voting stacks: a user may hold several votes on the same card (up to the session's
 * per-user quota), so there is deliberately no uniqueness on {@code (sessionId, cardId, userId)}.
 * The per-user quota is enforced in {@link VoteActionService} under a pessimistic row lock on the
 * parent session (see {@code V4__vote.sql} for the rationale).
 *
 * <p>{@code sessionId} and {@code cardId} both reference rows with {@code ON DELETE CASCADE}:
 * deleting the session or the card removes this vote automatically.
 */
@Entity
@Table(name = "vote", schema = "collaboratif")
public class Vote {

    /** Primary key generated by the database via UUID strategy — never client-supplied. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Session this vote belongs to; cascades on session deletion. */
    @Column(name = "session_id", nullable = false, updatable = false)
    private UUID sessionId;

    /** Card this vote targets; cascades on card deletion. */
    @Column(name = "card_id", nullable = false, updatable = false)
    private UUID cardId;

    /** The voting user's {@code public.users.id}. */
    @Column(name = "user_id", nullable = false, updatable = false)
    private Long userId;

    /** Timestamp when this vote was cast. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** No-arg constructor required by JPA. */
    protected Vote() {
    }

    /**
     * Creates a new vote.
     *
     * @param sessionId the owning session's UUID
     * @param cardId    the targeted card's UUID
     * @param userId    the voting user's {@code public.users.id}
     * @param now       timestamp used for {@code createdAt}
     */
    public Vote(final UUID sessionId, final UUID cardId, final Long userId, final Instant now) {
        this.sessionId = sessionId;
        this.cardId = cardId;
        this.userId = userId;
        this.createdAt = now;
    }

    /**
     * Sets {@code createdAt} to the current instant before the first insert, when not already set.
     */
    @PrePersist
    public void prePersist() {
        if (this.createdAt == null) {
            this.createdAt = Instant.now();
        }
    }

    /**
     * Returns the vote's unique identifier.
     *
     * @return the UUID
     */
    public UUID getId() {
        return id;
    }

    /**
     * Returns the owning session's identifier.
     *
     * @return the session UUID
     */
    public UUID getSessionId() {
        return sessionId;
    }

    /**
     * Returns the targeted card's identifier.
     *
     * @return the card UUID
     */
    public UUID getCardId() {
        return cardId;
    }

    /**
     * Returns the voting user's identifier.
     *
     * @return the user id
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * Returns the creation timestamp.
     *
     * @return the {@code createdAt} instant
     */
    public Instant getCreatedAt() {
        return createdAt;
    }
}
