package fr.pivot.collaboratif.whiteboard.vote;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;

import java.time.Instant;
import java.util.List;
import java.util.UUID;

/**
 * JPA entity representing a dot-voting session over a board's cards (Vote / dot-voting feature).
 *
 * <p>Created and closed exclusively over STOMP ({@code vote:start}/{@code vote:stop}, see {@link
 * VoteActionService}); its live and last-closed states are additionally exposed read-only over
 * REST ({@code GET /whiteboard/boards/{boardId}/vote/current|last}, see {@code VoteController}).
 *
 * <p>At most one {@link VoteStatus#ACTIVE} session exists per board at any time — enforced in
 * {@link VoteActionService} and backed by a partial unique index (see {@code V4__vote.sql}).
 *
 * <p>{@code voterIds} (the facilitator-supplied eligible-voter allowlist) is persisted as a
 * comma-separated string of {@code public.users.id} values in a single {@code voter_ids} column —
 * echoed to the frontend for its participant-count display only, never a casting security
 * boundary (casting is gated by board membership and the per-user quota). Access it through
 * {@link #getVoterIds()}/{@link #setVoterIds(List)}, which handle the CSV encoding.
 */
@Entity
@Table(name = "vote_session", schema = "collaboratif")
public class VoteSession {

    /** Primary key generated by the database via UUID strategy — never client-supplied. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Board this session belongs to; cascades on board deletion (FK {@code ON DELETE CASCADE}). */
    @Column(name = "board_id", nullable = false, updatable = false)
    private UUID boardId;

    /** Tenant owning the board this session belongs to — for tenant-scoped queries. */
    @Column(name = "tenant_id", nullable = false, updatable = false)
    private Long tenantId;

    /** Lifecycle status; {@link VoteStatus#ACTIVE} at creation, {@link VoteStatus#CLOSED} on stop. */
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    private VoteStatus status = VoteStatus.ACTIVE;

    /** Per-participant quota (number of voices each voter may cast in this session). */
    @Column(name = "votes_per_person", nullable = false)
    private int votesPerPerson;

    /** Timer duration in seconds, or {@code null} when the session runs without a timer. */
    @Column(name = "timer_seconds")
    private Integer timerSeconds;

    /** Instant the timer elapses, or {@code null} when the session runs without a timer. */
    @Column(name = "timer_ends_at")
    private Instant timerEndsAt;

    /** CSV of eligible voter user ids (see class Javadoc); accessed via {@link #getVoterIds()}. */
    @Column(name = "voter_ids", nullable = false)
    private String voterIdsCsv = "";

    /** Timestamp when this session was started. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** Timestamp when this session was closed, or {@code null} while it is still active. */
    @Column(name = "closed_at")
    private Instant closedAt;

    /** No-arg constructor required by JPA. */
    protected VoteSession() {
    }

    /**
     * Creates a new active vote session.
     *
     * @param boardId        the owning board's UUID
     * @param tenantId       the owning board's tenant id
     * @param votesPerPerson the per-participant quota (must be positive; validated by the caller)
     * @param timerSeconds   the timer duration in seconds, or {@code null} for no timer
     * @param timerEndsAt    the instant the timer elapses, or {@code null} for no timer
     * @param voterIds       the eligible-voter allowlist (user ids as strings)
     * @param now            timestamp used for {@code createdAt}
     */
    public VoteSession(
            final UUID boardId,
            final Long tenantId,
            final int votesPerPerson,
            final Integer timerSeconds,
            final Instant timerEndsAt,
            final List<String> voterIds,
            final Instant now) {
        this.boardId = boardId;
        this.tenantId = tenantId;
        this.votesPerPerson = votesPerPerson;
        this.timerSeconds = timerSeconds;
        this.timerEndsAt = timerEndsAt;
        setVoterIds(voterIds);
        this.createdAt = now;
    }

    /**
     * Sets {@code createdAt} to the current instant before the first insert, when not already set.
     */
    @PrePersist
    public void prePersist() {
        if (this.createdAt == null) {
            this.createdAt = Instant.now();
        }
    }

    /**
     * Returns the session's unique identifier.
     *
     * @return the UUID
     */
    public UUID getId() {
        return id;
    }

    /**
     * Returns the owning board's identifier.
     *
     * @return the board UUID
     */
    public UUID getBoardId() {
        return boardId;
    }

    /**
     * Returns the owning tenant's identifier.
     *
     * @return the tenant id
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * Returns the lifecycle status.
     *
     * @return the status
     */
    public VoteStatus getStatus() {
        return status;
    }

    /**
     * Returns the per-participant quota.
     *
     * @return the number of voices each voter may cast
     */
    public int getVotesPerPerson() {
        return votesPerPerson;
    }

    /**
     * Returns the timer duration in seconds.
     *
     * @return the timer seconds, or {@code null} for no timer
     */
    public Integer getTimerSeconds() {
        return timerSeconds;
    }

    /**
     * Returns the instant the timer elapses.
     *
     * @return the timer end instant, or {@code null} for no timer
     */
    public Instant getTimerEndsAt() {
        return timerEndsAt;
    }

    /**
     * Returns the eligible-voter allowlist as a list of user id strings, decoded from the stored
     * CSV. An empty CSV yields an empty list.
     *
     * @return the voter ids (never {@code null})
     */
    public List<String> getVoterIds() {
        if (voterIdsCsv == null || voterIdsCsv.isBlank()) {
            return List.of();
        }
        return List.of(voterIdsCsv.split(","));
    }

    /**
     * Returns the creation timestamp.
     *
     * @return the {@code createdAt} instant
     */
    public Instant getCreatedAt() {
        return createdAt;
    }

    /**
     * Returns the close timestamp.
     *
     * @return the {@code closedAt} instant, or {@code null} while active
     */
    public Instant getClosedAt() {
        return closedAt;
    }

    /**
     * Sets the lifecycle status.
     *
     * @param status the new status
     */
    public void setStatus(final VoteStatus status) {
        this.status = status;
    }

    /**
     * Sets the timer duration in seconds.
     *
     * @param timerSeconds the new timer seconds, or {@code null} for no timer
     */
    public void setTimerSeconds(final Integer timerSeconds) {
        this.timerSeconds = timerSeconds;
    }

    /**
     * Sets the instant the timer elapses.
     *
     * @param timerEndsAt the new timer end instant, or {@code null} for no timer
     */
    public void setTimerEndsAt(final Instant timerEndsAt) {
        this.timerEndsAt = timerEndsAt;
    }

    /**
     * Sets the close timestamp.
     *
     * @param closedAt the close instant
     */
    public void setClosedAt(final Instant closedAt) {
        this.closedAt = closedAt;
    }

    /**
     * Encodes the eligible-voter allowlist into the stored CSV. A {@code null} or empty list
     * clears it. Blank entries are dropped; each id is trimmed.
     *
     * @param voterIds the voter ids (user ids as strings), or {@code null}
     */
    public final void setVoterIds(final List<String> voterIds) {
        if (voterIds == null || voterIds.isEmpty()) {
            this.voterIdsCsv = "";
            return;
        }
        this.voterIdsCsv = voterIds.stream()
                .filter(id -> id != null && !id.isBlank())
                .map(String::trim)
                .reduce((a, b) -> a + "," + b)
                .orElse("");
    }
}
