package fr.pivot.agilite.standup;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

import java.time.Instant;
import java.util.UUID;

/**
 * JPA entity representing a single participant of a {@link StandupSession} (US10.1.1).
 *
 * <p>Always references an existing team member ({@code teamMemberId}, {@code public.team_members
 * .id}) — unlike {@code fr.pivot.agilite.wheel.WheelEntry}, this US has no free-text entrant
 * (Hors périmètre, see the pivot-docs AC). {@code name} is resolved server-side from {@code
 * public.users} at creation time and denormalized here so a later team departure never breaks a
 * past session's history.
 */
@Entity
@Table(name = "standup_participant", schema = "agilite")
public class StandupParticipant {

    /** Primary key generated by the database via UUID strategy. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Owning session. */
    @ManyToOne
    @JoinColumn(name = "session_id", nullable = false)
    private StandupSession session;

    /**
     * Referenced {@code public.team_members.id} — always populated at creation time, but
     * nullable: the FK is {@code ON DELETE SET NULL}, so a later team-membership deletion clears
     * this reference without breaking session history (the display {@link #name} is already
     * denormalized for exactly this reason).
     */
    @Column(name = "team_member_id")
    private Long teamMemberId;

    /** Denormalized display name, resolved server-side at creation time. */
    @Column(name = "name", nullable = false, length = 200)
    private String name;

    /**
     * Speaking-turn order within the session, {@code 0}-based — column named {@code
     * participant_order} ({@code order} is a reserved SQL keyword).
     */
    @Column(name = "participant_order", nullable = false)
    private int participantOrder;

    /** Turn-taking status — see {@link StandupParticipantStatus}. */
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    private StandupParticipantStatus status;

    /** Timestamp this participant started speaking, {@code null} until it is their turn. */
    @Column(name = "speaking_at")
    private Instant speakingAt;

    /** Timestamp this participant finished speaking (or was skipped), {@code null} until then. */
    @Column(name = "done_speaking")
    private Instant doneSpeaking;

    /**
     * Cumulative extra seconds granted via {@code POST .../extend} (US10.2.2), added to {@link
     * StandupSession#getTimePerPersonSeconds()} when computing this participant's speaking
     * deadline. Defaults to {@code 0}.
     */
    @Column(name = "extra_seconds", nullable = false)
    private int extraSeconds;

    /** No-arg constructor required by JPA. */
    protected StandupParticipant() {
    }

    /**
     * Full constructor for creating a new participant, {@link StandupParticipantStatus#WAITING}.
     *
     * @param session          the owning session
     * @param teamMemberId     the referenced {@code public.team_members.id}
     * @param name             the resolved display name
     * @param participantOrder the {@code 0}-based speaking-turn order
     */
    public StandupParticipant(
            final StandupSession session,
            final Long teamMemberId,
            final String name,
            final int participantOrder) {
        this.session = session;
        this.teamMemberId = teamMemberId;
        this.name = name;
        this.participantOrder = participantOrder;
        this.status = StandupParticipantStatus.WAITING;
    }

    /**
     * Returns the participant's unique identifier.
     *
     * @return the UUID
     */
    public UUID getId() {
        return id;
    }

    /**
     * Returns the owning session.
     *
     * @return the session
     */
    public StandupSession getSession() {
        return session;
    }

    /**
     * Returns the referenced team member id.
     *
     * @return the {@code public.team_members.id}
     */
    public Long getTeamMemberId() {
        return teamMemberId;
    }

    /**
     * Returns the denormalized display name.
     *
     * @return the name
     */
    public String getName() {
        return name;
    }

    /**
     * Returns the {@code 0}-based speaking-turn order.
     *
     * @return the participant order
     */
    public int getParticipantOrder() {
        return participantOrder;
    }

    /**
     * Sets the {@code 0}-based speaking-turn order (US10.2.2 {@code reorder}).
     *
     * @param participantOrder the new order
     */
    public void setParticipantOrder(final int participantOrder) {
        this.participantOrder = participantOrder;
    }

    /**
     * Returns the turn-taking status.
     *
     * @return the status
     */
    public StandupParticipantStatus getStatus() {
        return status;
    }

    /**
     * Sets the turn-taking status.
     *
     * @param status the new status
     */
    public void setStatus(final StandupParticipantStatus status) {
        this.status = status;
    }

    /**
     * Returns the timestamp this participant started speaking, or {@code null}.
     *
     * @return the speakingAt instant, or {@code null}
     */
    public Instant getSpeakingAt() {
        return speakingAt;
    }

    /**
     * Sets the timestamp this participant started speaking.
     *
     * @param speakingAt the new speakingAt instant
     */
    public void setSpeakingAt(final Instant speakingAt) {
        this.speakingAt = speakingAt;
    }

    /**
     * Returns the timestamp this participant finished speaking or was skipped, or {@code null}.
     *
     * @return the doneSpeaking instant, or {@code null}
     */
    public Instant getDoneSpeaking() {
        return doneSpeaking;
    }

    /**
     * Sets the timestamp this participant finished speaking or was skipped.
     *
     * @param doneSpeaking the new doneSpeaking instant
     */
    public void setDoneSpeaking(final Instant doneSpeaking) {
        this.doneSpeaking = doneSpeaking;
    }

    /**
     * Returns the cumulative extra seconds granted via {@code extend} (US10.2.2).
     *
     * @return the extra seconds, {@code 0} if never extended
     */
    public int getExtraSeconds() {
        return extraSeconds;
    }

    /**
     * Increments the cumulative extra seconds by the given amount (US10.2.2 {@code extend},
     * cumulable across multiple calls).
     *
     * @param seconds the amount to add, {@code 30} or {@code 60} per the AC
     */
    public void addExtraSeconds(final int seconds) {
        this.extraSeconds += seconds;
    }
}
