package fr.pivot.agilite.standup;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OrderBy;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;

import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * JPA entity representing a daily standup session (US10.1.1/US10.1.2).
 *
 * <p>Belongs to a single team, exactly mirroring {@code fr.pivot.agilite.wheel.Wheel}'s
 * team-ownership shape. Owns its ordered list of {@link StandupParticipant} rows as an aggregate
 * (cascade all, orphan removal) — participants are never created/deleted independently of their
 * session.
 */
@Entity
@Table(name = "standup_session", schema = "agilite")
public class StandupSession {

    /** Default speaking time per participant when not specified at creation (US10.1.1 AC). */
    public static final int DEFAULT_TIME_PER_PERSON_SECONDS = 120;

    /** Primary key generated by the database via UUID strategy. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Tenant that owns this session; used for multi-tenant isolation. */
    @Column(name = "tenant_id", nullable = false)
    private Long tenantId;

    /** Team this session belongs to; immutable after creation. */
    @Column(name = "team_id", nullable = false)
    private Long teamId;

    /** Human-readable session name; maximum 100 characters enforced at the service layer. */
    @Column(name = "name", nullable = false, length = 100)
    private String name;

    /** Lifecycle status — see {@link StandupSessionStatus}. */
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    private StandupSessionStatus status;

    /** {@code order} of the currently/last-speaking participant; {@code 0} until started. */
    @Column(name = "current_index", nullable = false)
    private int currentIndex;

    /** Configured speaking time per participant, in seconds (bounds [30, 1800], US10.1.1). */
    @Column(name = "time_per_person_seconds", nullable = false)
    private int timePerPersonSeconds;

    /** Timestamp the session was started ({@code POST .../start}), {@code null} until then. */
    @Column(name = "started_at")
    private Instant startedAt;

    /** Timestamp the session ended (rotation past the last participant, or {@code end}). */
    @Column(name = "ended_at")
    private Instant endedAt;

    /** User who created this session. */
    @Column(name = "created_by", nullable = false)
    private Long createdBy;

    /** Timestamp when the session was first persisted. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** Timestamp of the last update; refreshed automatically before every update. */
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /** Participants of this session — aggregate-owned, cascades all persistence operations. */
    @OneToMany(mappedBy = "session", cascade = CascadeType.ALL, orphanRemoval = true)
    @OrderBy("participantOrder ASC")
    private List<StandupParticipant> participants = new ArrayList<>();

    /** No-arg constructor required by JPA. */
    protected StandupSession() {
    }

    /**
     * Full constructor for creating a new session, {@link StandupSessionStatus#PENDING}.
     *
     * @param tenantId              owning tenant's {@code public.tenants.id}
     * @param teamId                owning team's {@code public.teams.id}
     * @param name                  session name (max 100 chars)
     * @param timePerPersonSeconds  configured speaking time per participant, in seconds
     * @param createdBy             creating user's {@code public.users.id}
     * @param now                   timestamp used for {@code createdAt}/{@code updatedAt}
     */
    public StandupSession(
            final Long tenantId,
            final Long teamId,
            final String name,
            final int timePerPersonSeconds,
            final Long createdBy,
            final Instant now) {
        this.tenantId = tenantId;
        this.teamId = teamId;
        this.name = name;
        this.status = StandupSessionStatus.PENDING;
        this.currentIndex = 0;
        this.timePerPersonSeconds = timePerPersonSeconds;
        this.createdBy = createdBy;
        this.createdAt = now;
        this.updatedAt = now;
    }

    /**
     * Sets {@code createdAt} and {@code updatedAt} to the current instant before
     * the first insert, when the fields have not already been set.
     */
    @PrePersist
    public void prePersist() {
        Instant now = Instant.now();
        if (this.createdAt == null) {
            this.createdAt = now;
        }
        if (this.updatedAt == null) {
            this.updatedAt = now;
        }
    }

    /**
     * Refreshes {@code updatedAt} to the current instant before every update.
     */
    @PreUpdate
    public void preUpdate() {
        this.updatedAt = Instant.now();
    }

    /**
     * Transitions this session to {@link StandupSessionStatus#RUNNING} (US10.1.2 {@code start}).
     *
     * @param now the transition timestamp, used for {@code startedAt}
     */
    public void start(final Instant now) {
        this.status = StandupSessionStatus.RUNNING;
        this.startedAt = now;
    }

    /**
     * Transitions this session to the terminal {@link StandupSessionStatus#DONE} (US10.1.2
     * {@code next}/{@code end}, or the US10.2.1 auto-expiry scheduler).
     *
     * @param now the transition timestamp, used for {@code endedAt}
     */
    public void end(final Instant now) {
        this.status = StandupSessionStatus.DONE;
        this.endedAt = now;
    }

    /**
     * Returns the session's unique identifier.
     *
     * @return the UUID
     */
    public UUID getId() {
        return id;
    }

    /**
     * Returns the tenant identifier.
     *
     * @return the tenant's {@code public.tenants.id}
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * Returns the team identifier.
     *
     * @return the team's {@code public.teams.id}
     */
    public Long getTeamId() {
        return teamId;
    }

    /**
     * Returns the session name.
     *
     * @return the name
     */
    public String getName() {
        return name;
    }

    /**
     * Returns the lifecycle status.
     *
     * @return the status
     */
    public StandupSessionStatus getStatus() {
        return status;
    }

    /**
     * Returns the {@code order} of the currently/last-speaking participant.
     *
     * @return the current index
     */
    public int getCurrentIndex() {
        return currentIndex;
    }

    /**
     * Sets the {@code order} of the currently/last-speaking participant.
     *
     * @param currentIndex the new current index
     */
    public void setCurrentIndex(final int currentIndex) {
        this.currentIndex = currentIndex;
    }

    /**
     * Returns the configured speaking time per participant, in seconds.
     *
     * @return the time per person, in seconds
     */
    public int getTimePerPersonSeconds() {
        return timePerPersonSeconds;
    }

    /**
     * Returns the timestamp the session was started, or {@code null} if not yet started.
     *
     * @return the startedAt instant, or {@code null}
     */
    public Instant getStartedAt() {
        return startedAt;
    }

    /**
     * Returns the timestamp the session ended, or {@code null} if not yet ended.
     *
     * @return the endedAt instant, or {@code null}
     */
    public Instant getEndedAt() {
        return endedAt;
    }

    /**
     * Returns the creating user's identifier.
     *
     * @return the creator's {@code public.users.id}
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * Returns the creation timestamp.
     *
     * @return the createdAt instant
     */
    public Instant getCreatedAt() {
        return createdAt;
    }

    /**
     * Returns the last-updated timestamp.
     *
     * @return the updatedAt instant
     */
    public Instant getUpdatedAt() {
        return updatedAt;
    }

    /**
     * Returns the live, mutable, order-sorted list of participants.
     *
     * @return the mutable participants list
     */
    public List<StandupParticipant> getParticipants() {
        return participants;
    }
}
