package fr.pivot.agilite.retro.card;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;

import java.time.Instant;
import java.util.UUID;

/**
 * JPA entity representing a single retrospective contribution card (US20.1.2a).
 *
 * <p>Maps {@code agilite.retro_cards}, whose DDL — including the anonymity {@code CHECK}
 * constraint {@code chk_retro_cards_anonymous_no_author} — was laid down by US20.1.1 as a
 * foundation this US builds the business logic on top of, without redefining it (see
 * {@code V1__schema_init.sql}'s comment on that table). {@link #anonymous} {@code == true} always
 * implies {@link #authorUserId} {@code == null}, enforced both here (see
 * {@code RetroCardService#submit}) and by the database constraint itself — the stronger, DB-level
 * guarantee is what actually makes "an anonymous card's author is never retrievable, even by the
 * facilitator" true, not this entity's own discipline.
 */
@Entity
@Table(name = "retro_cards", schema = "agilite")
public class RetroCard {

    /** Primary key generated by the database via UUID strategy. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Owning session; FK to {@code agilite.retro_sessions.id}. */
    @Column(name = "session_id", nullable = false)
    private UUID sessionId;

    /** Format-defined target column key (e.g. {@code "went-well"}) — catalogue owned by US20.2.1. */
    @Column(name = "column_key", nullable = false, length = 50)
    private String columnKey;

    /** Free-text card content, as submitted by the participant. */
    @Column(name = "content", nullable = false)
    private String content;

    /**
     * Whether this card was submitted anonymously. When {@code true}, {@link #authorUserId} is
     * always {@code null} — never persisted at all, not merely hidden.
     */
    @Column(name = "is_anonymous", nullable = false)
    private boolean anonymous;

    /**
     * The submitting participant's {@code public.users.id}, or {@code null} when {@link
     * #anonymous} is {@code true}, or when the participant joined without a resolvable
     * same-tenant account at all.
     */
    @Column(name = "author_user_id")
    private Long authorUserId;

    /** Timestamp when the card was submitted. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** No-arg constructor required by JPA. */
    protected RetroCard() {
    }

    /**
     * Full constructor for creating a new card.
     *
     * @param sessionId    the owning session's id
     * @param columnKey    the target column key
     * @param content      the card's free-text content
     * @param anonymous    whether the card is anonymous (author never persisted when {@code true})
     * @param authorUserId the author's user id, or {@code null} (must be {@code null} when
     *                     {@code anonymous} is {@code true})
     * @param createdAt    the submission timestamp
     */
    public RetroCard(
            final UUID sessionId,
            final String columnKey,
            final String content,
            final boolean anonymous,
            final Long authorUserId,
            final Instant createdAt) {
        this.sessionId = sessionId;
        this.columnKey = columnKey;
        this.content = content;
        this.anonymous = anonymous;
        this.authorUserId = anonymous ? null : authorUserId;
        this.createdAt = createdAt;
    }

    /**
     * Sets {@code createdAt} to the current instant before the first insert, when not already
     * set.
     */
    @PrePersist
    public void prePersist() {
        if (this.createdAt == null) {
            this.createdAt = Instant.now();
        }
    }

    /**
     * Returns the card's unique identifier.
     *
     * @return the UUID, {@code null} until first persisted
     */
    public UUID getId() {
        return id;
    }

    /**
     * Returns the owning session's identifier.
     *
     * @return the session UUID
     */
    public UUID getSessionId() {
        return sessionId;
    }

    /**
     * Returns the target column key.
     *
     * @return the column key
     */
    public String getColumnKey() {
        return columnKey;
    }

    /**
     * Returns the card's free-text content.
     *
     * @return the content
     */
    public String getContent() {
        return content;
    }

    /**
     * Returns whether this card was submitted anonymously.
     *
     * @return {@code true} if anonymous
     */
    public boolean isAnonymous() {
        return anonymous;
    }

    /**
     * Returns the author's user id.
     *
     * @return the author's {@code public.users.id}, or {@code null} if anonymous/unresolved
     */
    public Long getAuthorUserId() {
        return authorUserId;
    }

    /**
     * Returns the submission timestamp.
     *
     * @return the createdAt instant
     */
    public Instant getCreatedAt() {
        return createdAt;
    }
}
