package fr.pivot.agilite.pi;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

import java.util.UUID;

/**
 * JPA entity representing a Train team snapshot within a {@link PiCycle} (US50.1.1).
 *
 * <p>Either imported from an existing {@code public.teams} row ({@code sourceTeamId} set, {@code
 * name} denormalized at import time so a later deletion of the source team never breaks a
 * historical PI — same precedent as {@code StandupParticipant.name}/{@code WheelEntry.label}) or
 * added manually (free-text {@code name}, {@code sourceTeamId} {@code null} — external partners
 * not modeled in PIVOT). {@code color} has no PIVOT-side equivalent to copy from ({@code
 * public.teams} carries no color column) — always assigned server-side (import or manual add)
 * from a small fixed palette, cycling by {@code teamOrder}.
 */
@Entity
@Table(name = "pi_cycle_team", schema = "agilite")
public class PiCycleTeam {

    /** Primary key generated by the database via UUID strategy. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Owning cycle. */
    @ManyToOne
    @JoinColumn(name = "cycle_id", nullable = false)
    private PiCycle cycle;

    /** Display name — denormalized snapshot, never re-read from {@code public.teams}. */
    @Column(name = "name", nullable = false, length = 120)
    private String name;

    /** Display color (hex, e.g. {@code "#4F46E5"}), server-assigned. */
    @Column(name = "color", nullable = false, length = 20)
    private String color;

    /** Display order among the cycle's teams (0-based); the dedicated Train row is not a row here. */
    @Column(name = "team_order", nullable = false)
    private int teamOrder;

    /**
     * The {@code public.teams.id} this team was imported from, or {@code null} for a manually
     * added team. Set to {@code null} by the database (ON DELETE SET NULL) if the source team is
     * later deleted — this row and its {@code name}/{@code color} snapshot survive intact.
     */
    @Column(name = "source_team_id")
    private Long sourceTeamId;

    /** No-arg constructor required by JPA. */
    protected PiCycleTeam() {
    }

    /**
     * Full constructor for creating a new Train team.
     *
     * @param cycle        the owning cycle
     * @param name         display name (max 120 chars)
     * @param color        display color, server-assigned
     * @param teamOrder    display order among the cycle's teams
     * @param sourceTeamId the source {@code public.teams.id}, or {@code null} for a manual entry
     */
    public PiCycleTeam(
            final PiCycle cycle,
            final String name,
            final String color,
            final int teamOrder,
            final Long sourceTeamId) {
        this.cycle = cycle;
        this.name = name;
        this.color = color;
        this.teamOrder = teamOrder;
        this.sourceTeamId = sourceTeamId;
    }

    /**
     * Returns the Train team's unique identifier.
     *
     * @return the UUID
     */
    public UUID getId() {
        return id;
    }

    /**
     * Returns the owning cycle.
     *
     * @return the cycle
     */
    public PiCycle getCycle() {
        return cycle;
    }

    /**
     * Returns the display name.
     *
     * @return the name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the display name.
     *
     * @param name the new name
     */
    public void setName(final String name) {
        this.name = name;
    }

    /**
     * Returns the display color.
     *
     * @return the color
     */
    public String getColor() {
        return color;
    }

    /**
     * Sets the display color.
     *
     * @param color the new color
     */
    public void setColor(final String color) {
        this.color = color;
    }

    /**
     * Returns the display order among the cycle's teams.
     *
     * @return the order
     */
    public int getTeamOrder() {
        return teamOrder;
    }

    /**
     * Sets the display order among the cycle's teams.
     *
     * @param teamOrder the new order
     */
    public void setTeamOrder(final int teamOrder) {
        this.teamOrder = teamOrder;
    }

    /**
     * Returns the source {@code public.teams.id}, or {@code null} for a manually added team.
     *
     * @return the source team id, or {@code null}
     */
    public Long getSourceTeamId() {
        return sourceTeamId;
    }
}
