package fr.pivot.agilite.pi;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OrderBy;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;

import java.time.Instant;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * JPA entity representing a SAFe Program Increment cycle (US50.1.1).
 *
 * <p>Owns its ordered {@link PiIteration}/{@link PiCycleTeam} collections as aggregates (cascade
 * all, orphan removal) — same pattern as {@code fr.pivot.agilite.wheel.Wheel}'s entries. {@link
 * PiTicket}/{@link PiDependency} are deliberately NOT mapped as JPA collections here (a cycle can
 * hold many tickets — the Program Board loads them directly via {@code PiTicketRepository}/
 * {@code PiDependencyRepository} by {@code cycleId}, never through this entity, to avoid an
 * unbounded eager collection on every {@code GET .../cycles/{id}}).
 *
 * <p>{@code eventDay1}/{@code eventDay2}/{@code eventLocation} are reserved fields for the
 * deferred US50.2.1 (logistics form integration, blocked on E42/E49) — posed at the socle to
 * avoid an additive migration later; unused until then.
 */
@Entity
@Table(name = "pi_cycle", schema = "agilite")
public class PiCycle {

    /** Default number of iterations generated at creation when {@code iterationCount} is omitted. */
    public static final int DEFAULT_ITERATION_COUNT = 5;

    /** Default iteration length in weeks when {@code iterationWeeks} is omitted. */
    public static final int DEFAULT_ITERATION_WEEKS = 2;

    /** Primary key generated by the database via UUID strategy. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Tenant that owns this cycle; used for multi-tenant isolation. */
    @Column(name = "tenant_id", nullable = false)
    private Long tenantId;

    /** Human-readable cycle name; maximum 120 characters enforced at the service layer. */
    @Column(name = "name", nullable = false, length = 120)
    private String name;

    /** Agile Release Train name; optional. */
    @Column(name = "art_name", length = 120)
    private String artName;

    /** Lifecycle status — see {@link PiCycleStatus}. */
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    private PiCycleStatus status;

    /** Cycle start date, as provided at creation. */
    @Column(name = "start_date", nullable = false)
    private LocalDate startDate;

    /** Cycle end date — always the last generated iteration's ({@code IP Sprint}) end date. */
    @Column(name = "end_date", nullable = false)
    private LocalDate endDate;

    /** Reserved for US50.2.1 (logistics form) — first event day, unused until then. */
    @Column(name = "event_day_1")
    private LocalDate eventDay1;

    /** Reserved for US50.2.1 (logistics form) — second event day, unused until then. */
    @Column(name = "event_day_2")
    private LocalDate eventDay2;

    /** Reserved for US50.2.1 (logistics form) — event location, unused until then. */
    @Column(name = "event_location", length = 200)
    private String eventLocation;

    /** User who created this cycle. */
    @Column(name = "created_by", nullable = false)
    private Long createdBy;

    /** Timestamp when the cycle was first persisted. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** Timestamp of the last update; refreshed automatically before every update. */
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /** Iterations of this cycle — aggregate-owned, cascades all persistence operations. */
    @OneToMany(mappedBy = "cycle", cascade = CascadeType.ALL, orphanRemoval = true)
    @OrderBy("number ASC")
    private List<PiIteration> iterations = new ArrayList<>();

    /** Train teams of this cycle — aggregate-owned, cascades all persistence operations. */
    @OneToMany(mappedBy = "cycle", cascade = CascadeType.ALL, orphanRemoval = true)
    @OrderBy("teamOrder ASC")
    private List<PiCycleTeam> teams = new ArrayList<>();

    /** No-arg constructor required by JPA. */
    protected PiCycle() {
    }

    /**
     * Full constructor for creating a new cycle, {@link PiCycleStatus#PREPARATION}.
     *
     * @param tenantId  owning tenant's {@code public.tenants.id}
     * @param name      cycle name (max 120 chars)
     * @param artName   Agile Release Train name, or {@code null}
     * @param startDate cycle start date
     * @param endDate   cycle end date (last generated iteration's end date)
     * @param createdBy creating user's {@code public.users.id}
     * @param now       timestamp used for both {@code createdAt} and {@code updatedAt}
     */
    public PiCycle(
            final Long tenantId,
            final String name,
            final String artName,
            final LocalDate startDate,
            final LocalDate endDate,
            final Long createdBy,
            final Instant now) {
        this.tenantId = tenantId;
        this.name = name;
        this.artName = artName;
        this.status = PiCycleStatus.PREPARATION;
        this.startDate = startDate;
        this.endDate = endDate;
        this.createdBy = createdBy;
        this.createdAt = now;
        this.updatedAt = now;
    }

    /**
     * Sets {@code createdAt} and {@code updatedAt} to the current instant before
     * the first insert, when the fields have not already been set.
     */
    @PrePersist
    public void prePersist() {
        Instant now = Instant.now();
        if (this.createdAt == null) {
            this.createdAt = now;
        }
        if (this.updatedAt == null) {
            this.updatedAt = now;
        }
    }

    /**
     * Refreshes {@code updatedAt} to the current instant before every update.
     */
    @PreUpdate
    public void preUpdate() {
        this.updatedAt = Instant.now();
    }

    /**
     * Returns the cycle's unique identifier.
     *
     * @return the UUID
     */
    public UUID getId() {
        return id;
    }

    /**
     * Returns the tenant identifier.
     *
     * @return the tenant's {@code public.tenants.id}
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * Returns the cycle name.
     *
     * @return the name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the cycle name.
     *
     * @param name the name to set
     */
    public void setName(final String name) {
        this.name = name;
    }

    /**
     * Returns the Agile Release Train name, or {@code null}.
     *
     * @return the ART name, or {@code null}
     */
    public String getArtName() {
        return artName;
    }

    /**
     * Sets the Agile Release Train name.
     *
     * @param artName the ART name, or {@code null}
     */
    public void setArtName(final String artName) {
        this.artName = artName;
    }

    /**
     * Returns the lifecycle status.
     *
     * @return the status
     */
    public PiCycleStatus getStatus() {
        return status;
    }

    /**
     * Sets the lifecycle status — no state-machine restriction at the socle.
     *
     * @param status the new status
     */
    public void setStatus(final PiCycleStatus status) {
        this.status = status;
    }

    /**
     * Returns the cycle start date.
     *
     * @return the start date
     */
    public LocalDate getStartDate() {
        return startDate;
    }

    /**
     * Returns the cycle end date.
     *
     * @return the end date
     */
    public LocalDate getEndDate() {
        return endDate;
    }

    /**
     * Sets the cycle end date — kept in sync with the last iteration's end date.
     *
     * @param endDate the new end date
     */
    public void setEndDate(final LocalDate endDate) {
        this.endDate = endDate;
    }

    /**
     * Returns the reserved first event day (US50.2.1), or {@code null}.
     *
     * @return the first event day, or {@code null}
     */
    public LocalDate getEventDay1() {
        return eventDay1;
    }

    /**
     * Sets the reserved first event day (US50.2.1).
     *
     * @param eventDay1 the first event day, or {@code null}
     */
    public void setEventDay1(final LocalDate eventDay1) {
        this.eventDay1 = eventDay1;
    }

    /**
     * Returns the reserved second event day (US50.2.1), or {@code null}.
     *
     * @return the second event day, or {@code null}
     */
    public LocalDate getEventDay2() {
        return eventDay2;
    }

    /**
     * Sets the reserved second event day (US50.2.1).
     *
     * @param eventDay2 the second event day, or {@code null}
     */
    public void setEventDay2(final LocalDate eventDay2) {
        this.eventDay2 = eventDay2;
    }

    /**
     * Returns the reserved event location (US50.2.1), or {@code null}.
     *
     * @return the event location, or {@code null}
     */
    public String getEventLocation() {
        return eventLocation;
    }

    /**
     * Sets the reserved event location (US50.2.1).
     *
     * @param eventLocation the event location, or {@code null}
     */
    public void setEventLocation(final String eventLocation) {
        this.eventLocation = eventLocation;
    }

    /**
     * Returns the creating user's identifier.
     *
     * @return the creator's {@code public.users.id}
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * Returns the creation timestamp.
     *
     * @return the createdAt instant
     */
    public Instant getCreatedAt() {
        return createdAt;
    }

    /**
     * Returns the last-updated timestamp.
     *
     * @return the updatedAt instant
     */
    public Instant getUpdatedAt() {
        return updatedAt;
    }

    /**
     * Returns the live, mutable, number-sorted list of iterations.
     *
     * @return the mutable iterations list
     */
    public List<PiIteration> getIterations() {
        return iterations;
    }

    /**
     * Returns the live, mutable, order-sorted list of Train teams.
     *
     * @return the mutable teams list
     */
    public List<PiCycleTeam> getTeams() {
        return teams;
    }
}
