package fr.pivot.agilite.pi;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.util.UUID;

/**
 * JPA entity representing a dependency arrow between two {@link PiTicket}s of the same cycle
 * (US50.3.2).
 *
 * <p>Plain-column entity, same rationale as {@link PiTicket} — never loaded through a JPA
 * relation, always queried directly via {@code PiDependencyRepository} by {@code cycleId}
 * (notably for {@link PiDependencyCycleDetector}, which needs the full edge set of a cycle).
 */
@Entity
@Table(name = "pi_dependency", schema = "agilite")
public class PiDependency {

    /** Primary key generated by the database via UUID strategy. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Owning cycle's id. */
    @Column(name = "cycle_id", nullable = false)
    private UUID cycleId;

    /** Source ticket — the dependency's tail. */
    @Column(name = "from_ticket_id", nullable = false)
    private UUID fromTicketId;

    /** Target ticket — the dependency's head. */
    @Column(name = "to_ticket_id", nullable = false)
    private UUID toTicketId;

    /** Visual/business status — see {@link PiDependencyStatus}. */
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    private PiDependencyStatus status;

    /** Optional free-text note. */
    @Column(name = "note", length = 1000)
    private String note;

    /** No-arg constructor required by JPA. */
    protected PiDependency() {
    }

    /**
     * Full constructor for creating a new dependency.
     *
     * @param cycleId      the owning cycle's id
     * @param fromTicketId the source ticket
     * @param toTicketId   the target ticket
     * @param status       the initial status
     * @param note         an optional free-text note, or {@code null}
     */
    public PiDependency(
            final UUID cycleId,
            final UUID fromTicketId,
            final UUID toTicketId,
            final PiDependencyStatus status,
            final String note) {
        this.cycleId = cycleId;
        this.fromTicketId = fromTicketId;
        this.toTicketId = toTicketId;
        this.status = status;
        this.note = note;
    }

    /**
     * Returns the dependency's unique identifier.
     *
     * @return the UUID
     */
    public UUID getId() {
        return id;
    }

    /**
     * Returns the owning cycle's id.
     *
     * @return the cycle id
     */
    public UUID getCycleId() {
        return cycleId;
    }

    /**
     * Returns the source ticket id.
     *
     * @return the from-ticket id
     */
    public UUID getFromTicketId() {
        return fromTicketId;
    }

    /**
     * Returns the target ticket id.
     *
     * @return the to-ticket id
     */
    public UUID getToTicketId() {
        return toTicketId;
    }

    /**
     * Returns the visual/business status.
     *
     * @return the status
     */
    public PiDependencyStatus getStatus() {
        return status;
    }

    /**
     * Sets the visual/business status.
     *
     * @param status the new status
     */
    public void setStatus(final PiDependencyStatus status) {
        this.status = status;
    }

    /**
     * Returns the free-text note, or {@code null}.
     *
     * @return the note, or {@code null}
     */
    public String getNote() {
        return note;
    }

    /**
     * Sets the free-text note.
     *
     * @param note the new note, or {@code null}
     */
    public void setNote(final String note) {
        this.note = note;
    }
}
