package fr.pivot.agilite.pi;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

import java.time.LocalDate;
import java.util.UUID;

/**
 * JPA entity representing a single iteration (sprint) of a {@link PiCycle} (US50.1.1).
 *
 * <p>Generated in bulk at cycle creation by {@link PiIterationGenerator} — {@code number} 1..N
 * are the regular sprints ({@code label} {@code "IT1"}.. {@code "ITn"}), the final {@code n+1}
 * is always the Innovation & Planning sprint ({@code label} {@code "IP Sprint"}). Adjustable
 * afterwards via {@code PATCH .../cycles/{id}/iterations/{iterationId}}.
 */
@Entity
@Table(name = "pi_iteration", schema = "agilite")
public class PiIteration {

    /** Primary key generated by the database via UUID strategy. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Owning cycle. */
    @ManyToOne
    @JoinColumn(name = "cycle_id", nullable = false)
    private PiCycle cycle;

    /** 1-based position within the cycle, IP Sprint included as the last number. */
    @Column(name = "number", nullable = false)
    private int number;

    /** Display label, e.g. {@code "IT1"} or {@code "IP Sprint"}. */
    @Column(name = "label", nullable = false, length = 50)
    private String label;

    /** Iteration start date. */
    @Column(name = "start_date", nullable = false)
    private LocalDate startDate;

    /** Iteration end date. */
    @Column(name = "end_date", nullable = false)
    private LocalDate endDate;

    /** No-arg constructor required by JPA. */
    protected PiIteration() {
    }

    /**
     * Full constructor for creating a new iteration.
     *
     * @param cycle     the owning cycle
     * @param number    1-based position within the cycle
     * @param label     display label
     * @param startDate iteration start date
     * @param endDate   iteration end date
     */
    public PiIteration(
            final PiCycle cycle,
            final int number,
            final String label,
            final LocalDate startDate,
            final LocalDate endDate) {
        this.cycle = cycle;
        this.number = number;
        this.label = label;
        this.startDate = startDate;
        this.endDate = endDate;
    }

    /**
     * Returns the iteration's unique identifier.
     *
     * @return the UUID
     */
    public UUID getId() {
        return id;
    }

    /**
     * Returns the owning cycle.
     *
     * @return the cycle
     */
    public PiCycle getCycle() {
        return cycle;
    }

    /**
     * Returns the 1-based position within the cycle.
     *
     * @return the number
     */
    public int getNumber() {
        return number;
    }

    /**
     * Returns the display label.
     *
     * @return the label
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the display label.
     *
     * @param label the new label
     */
    public void setLabel(final String label) {
        this.label = label;
    }

    /**
     * Returns the iteration start date.
     *
     * @return the start date
     */
    public LocalDate getStartDate() {
        return startDate;
    }

    /**
     * Sets the iteration start date.
     *
     * @param startDate the new start date
     */
    public void setStartDate(final LocalDate startDate) {
        this.startDate = startDate;
    }

    /**
     * Returns the iteration end date.
     *
     * @return the end date
     */
    public LocalDate getEndDate() {
        return endDate;
    }

    /**
     * Sets the iteration end date.
     *
     * @param endDate the new end date
     */
    public void setEndDate(final LocalDate endDate) {
        this.endDate = endDate;
    }
}
