package fr.pivot.agilite.pi;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.util.UUID;

/**
 * JPA entity representing a single ticket placed on a {@link PiCycle}'s Program Board (US50.3.1).
 *
 * <p>Deliberately modeled with plain {@code cycleId}/{@code teamId}/{@code iterationId} columns
 * rather than JPA {@code @ManyToOne} relations — a cycle's tickets are never loaded through
 * {@link PiCycle} (unbounded collection), always queried directly via {@code PiTicketRepository}
 * by {@code cycleId} (same posture as {@code StandupParticipant.teamMemberId}, a plain column
 * backed only by a database-level FK). {@code teamId == null} places the ticket on the dedicated
 * Train row; {@code iterationId == null} places it in the "Unplanned" column.
 */
@Entity
@Table(name = "pi_ticket", schema = "agilite")
public class PiTicket {

    /** Primary key generated by the database via UUID strategy. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Owning cycle's {@code public.pi_cycle.id} (this module's {@code agilite.pi_cycle.id}). */
    @Column(name = "cycle_id", nullable = false)
    private UUID cycleId;

    /** Ticket type — see {@link PiTicketType}. */
    @Enumerated(EnumType.STRING)
    @Column(name = "type", nullable = false, length = 20)
    private PiTicketType type;

    /** Ticket title; maximum 300 characters enforced at the service layer. */
    @Column(name = "title", nullable = false, length = 300)
    private String title;

    /** Optional free-text description; maximum 3000 characters enforced at the service layer. */
    @Column(name = "description", length = 3000)
    private String description;

    /** Owning Train team, or {@code null} for the dedicated Train row. */
    @Column(name = "team_id")
    private UUID teamId;

    /** Target iteration, or {@code null} for the "Unplanned" column. */
    @Column(name = "iteration_id")
    private UUID iterationId;

    /** Display order within its board cell (team x iteration). */
    @Column(name = "ticket_order", nullable = false)
    private int ticketOrder;

    /** No-arg constructor required by JPA. */
    protected PiTicket() {
    }

    /**
     * Full constructor for creating a new ticket.
     *
     * @param cycleId     the owning cycle's id
     * @param type        the ticket type
     * @param title       the ticket title (max 300 chars)
     * @param description the ticket description, or {@code null}
     * @param teamId      the target Train team, or {@code null} for the Train row
     * @param iterationId the target iteration, or {@code null} for "Unplanned"
     * @param ticketOrder the display order within the target cell
     */
    public PiTicket(
            final UUID cycleId,
            final PiTicketType type,
            final String title,
            final String description,
            final UUID teamId,
            final UUID iterationId,
            final int ticketOrder) {
        this.cycleId = cycleId;
        this.type = type;
        this.title = title;
        this.description = description;
        this.teamId = teamId;
        this.iterationId = iterationId;
        this.ticketOrder = ticketOrder;
    }

    /**
     * Returns the ticket's unique identifier.
     *
     * @return the UUID
     */
    public UUID getId() {
        return id;
    }

    /**
     * Returns the owning cycle's id.
     *
     * @return the cycle id
     */
    public UUID getCycleId() {
        return cycleId;
    }

    /**
     * Returns the ticket type.
     *
     * @return the type
     */
    public PiTicketType getType() {
        return type;
    }

    /**
     * Sets the ticket type.
     *
     * @param type the new type
     */
    public void setType(final PiTicketType type) {
        this.type = type;
    }

    /**
     * Returns the ticket title.
     *
     * @return the title
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the ticket title.
     *
     * @param title the new title
     */
    public void setTitle(final String title) {
        this.title = title;
    }

    /**
     * Returns the ticket description, or {@code null}.
     *
     * @return the description, or {@code null}
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the ticket description.
     *
     * @param description the new description, or {@code null}
     */
    public void setDescription(final String description) {
        this.description = description;
    }

    /**
     * Returns the target Train team, or {@code null} for the Train row.
     *
     * @return the team id, or {@code null}
     */
    public UUID getTeamId() {
        return teamId;
    }

    /**
     * Sets the target Train team.
     *
     * @param teamId the new team id, or {@code null} for the Train row
     */
    public void setTeamId(final UUID teamId) {
        this.teamId = teamId;
    }

    /**
     * Returns the target iteration, or {@code null} for "Unplanned".
     *
     * @return the iteration id, or {@code null}
     */
    public UUID getIterationId() {
        return iterationId;
    }

    /**
     * Sets the target iteration.
     *
     * @param iterationId the new iteration id, or {@code null} for "Unplanned"
     */
    public void setIterationId(final UUID iterationId) {
        this.iterationId = iterationId;
    }

    /**
     * Returns the display order within the current cell.
     *
     * @return the order
     */
    public int getTicketOrder() {
        return ticketOrder;
    }

    /**
     * Sets the display order within the current cell.
     *
     * @param ticketOrder the new order
     */
    public void setTicketOrder(final int ticketOrder) {
        this.ticketOrder = ticketOrder;
    }
}
