package fr.pivot.collaboratif.whiteboard.share;

import fr.pivot.collaboratif.whiteboard.board.BoardRole;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.time.Instant;
import java.util.UUID;

/**
 * JPA entity representing a board share invitation token.
 *
 * <p>The raw token is never stored — only its SHA-256 hash is persisted.
 * Tokens carry an expiry date, a maximum use count, and a role assignment for
 * the joining user.
 */
@Entity
@Table(name = "board_share_token", schema = "collaboratif")
public class BoardShareToken {

    /** Primary key generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Board this token grants access to. */
    @Column(name = "board_id", nullable = false)
    private UUID boardId;

    /** SHA-256 hex digest of the plain invitation token (never stored in clear). */
    @Column(name = "token_hash", nullable = false, length = 64)
    private String tokenHash;

    /** Role assigned to any user who joins using this token. */
    @Enumerated(EnumType.STRING)
    @Column(name = "role", nullable = false, length = 20)
    private BoardRole role;

    /** Maximum number of times this token may be used. */
    @Column(name = "max_uses", nullable = false)
    private int maxUses;

    /** Current number of successful uses. */
    @Column(name = "use_count", nullable = false)
    private int useCount;

    /** Instant at which this token expires and becomes invalid. */
    @Column(name = "expires_at", nullable = false)
    private Instant expiresAt;

    /** Set when the token is explicitly revoked; {@code null} means active. */
    @Column(name = "revoked_at")
    private Instant revokedAt;

    /** User who generated this token. */
    @Column(name = "created_by", nullable = false)
    private Long createdBy;

    /** When this token was created. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** No-arg constructor required by JPA. */
    protected BoardShareToken() {
    }

    /**
     * Creates a new share token record.
     *
     * @param boardId   the board this token grants access to
     * @param tokenHash SHA-256 hex hash of the plain token
     * @param role      role assigned on successful join
     * @param maxUses   maximum allowed use count
     * @param expiresAt expiry instant
     * @param createdBy {@code public.users.id} of the user who generated the token
     * @param now       creation timestamp
     */
    public BoardShareToken(
            final UUID boardId,
            final String tokenHash,
            final BoardRole role,
            final int maxUses,
            final Instant expiresAt,
            final Long createdBy,
            final Instant now) {
        this.boardId = boardId;
        this.tokenHash = tokenHash;
        this.role = role;
        this.maxUses = maxUses;
        this.useCount = 0;
        this.expiresAt = expiresAt;
        this.createdBy = createdBy;
        this.createdAt = now;
    }

    /**
     * Returns the token identifier.
     *
     * @return the UUID
     */
    public UUID getId() {
        return id;
    }

    /**
     * Returns the board identifier.
     *
     * @return the board UUID
     */
    public UUID getBoardId() {
        return boardId;
    }

    /**
     * Returns the SHA-256 hash of the plain token.
     *
     * @return the hex-encoded hash
     */
    public String getTokenHash() {
        return tokenHash;
    }

    /**
     * Returns the role assigned to joining users.
     *
     * @return the board role
     */
    public BoardRole getRole() {
        return role;
    }

    /**
     * Returns the maximum number of times this token may be used.
     *
     * @return the use limit
     */
    public int getMaxUses() {
        return maxUses;
    }

    /**
     * Returns the current use count.
     *
     * @return the number of successful uses
     */
    public int getUseCount() {
        return useCount;
    }

    /**
     * Returns the expiry instant.
     *
     * @return the expiry
     */
    public Instant getExpiresAt() {
        return expiresAt;
    }

    /**
     * Returns the revocation instant, or {@code null} if the token is still active.
     *
     * @return the revoked-at instant, or {@code null}
     */
    public Instant getRevokedAt() {
        return revokedAt;
    }

    /**
     * Marks this token as revoked at the given instant.
     *
     * @param revokedAt the instant of revocation
     */
    public void revoke(final Instant revokedAt) {
        this.revokedAt = revokedAt;
    }

    /**
     * Returns the identifier of the user who created this token.
     *
     * @return the creator's {@code public.users.id}
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * Returns the creation timestamp.
     *
     * @return the created-at instant
     */
    public Instant getCreatedAt() {
        return createdAt;
    }

    /**
     * Atomically increments the use count, recording one successful join.
     */
    public void incrementUseCount() {
        this.useCount++;
    }

    /**
     * Returns {@code true} if this token is currently valid (not revoked, not expired,
     * and within its use limit).
     *
     * @param now current instant for expiry comparison
     * @return {@code true} when the token may be used
     */
    public boolean isUsable(final Instant now) {
        return revokedAt == null && expiresAt.isAfter(now) && useCount < maxUses;
    }
}
