package fr.pivot.collaboratif.session.quiz;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.time.Instant;
import java.util.UUID;

/**
 * A participant's answer to one QUIZ question (US19.3.1) — one row per
 * {@code (session, participant, questionIndex)}, never overwritten. Records the graded outcome
 * ({@code correct}) and the {@code pointsAwarded} (base points plus a submission-rank speed bonus)
 * at submission time, so the leaderboard is a simple sum with no re-grading.
 */
@Entity
@Table(name = "session_quiz_answer", schema = "collaboratif")
public class SessionQuizAnswer {

    /** Primary key generated by the database via UUID strategy — never client-supplied. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Owning session; cascades on session deletion. */
    @Column(name = "session_id", nullable = false, updatable = false)
    private UUID sessionId;

    /** The answering participant. */
    @Column(name = "participant_id", nullable = false, updatable = false)
    private UUID participantId;

    /** The question this answer is for. */
    @Column(name = "question_index", nullable = false, updatable = false)
    private int questionIndex;

    /** The selected option indices, as a JSONB array. */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "selected_indices", nullable = false, updatable = false, columnDefinition = "jsonb")
    private String selectedIndices;

    /** Whether the answer matched the question's correct option set. */
    @Column(nullable = false, updatable = false)
    private boolean correct;

    /** Points awarded (base + speed bonus), frozen at submission. */
    @Column(name = "points_awarded", nullable = false, updatable = false)
    private int pointsAwarded;

    /** Submission timestamp. */
    @Column(name = "submitted_at", nullable = false, updatable = false)
    private Instant submittedAt;

    /** No-arg constructor required by JPA. */
    protected SessionQuizAnswer() {
    }

    /**
     * Creates a graded answer.
     *
     * @param sessionId       the owning session's UUID
     * @param participantId   the answering participant's UUID
     * @param questionIndex   the question index
     * @param selectedIndices the selected option indices, as a JSON array string
     * @param correct         whether the answer was correct
     * @param pointsAwarded   the points awarded (base + speed bonus)
     * @param now             the submission timestamp
     */
    public SessionQuizAnswer(
            final UUID sessionId, final UUID participantId, final int questionIndex,
            final String selectedIndices, final boolean correct, final int pointsAwarded, final Instant now) {
        this.sessionId = sessionId;
        this.participantId = participantId;
        this.questionIndex = questionIndex;
        this.selectedIndices = selectedIndices;
        this.correct = correct;
        this.pointsAwarded = pointsAwarded;
        this.submittedAt = now;
    }

    /** Sets {@code submittedAt} before the first insert, when not already set. */
    @PrePersist
    public void prePersist() {
        if (this.submittedAt == null) {
            this.submittedAt = Instant.now();
        }
    }

    public UUID getId() {
        return id;
    }

    public UUID getSessionId() {
        return sessionId;
    }

    public UUID getParticipantId() {
        return participantId;
    }

    public int getQuestionIndex() {
        return questionIndex;
    }

    public String getSelectedIndices() {
        return selectedIndices;
    }

    public boolean isCorrect() {
        return correct;
    }

    public int getPointsAwarded() {
        return pointsAwarded;
    }

    public Instant getSubmittedAt() {
        return submittedAt;
    }
}
