package fr.pivot.collaboratif.session.qa;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;

import java.time.Instant;
import java.util.UUID;

/**
 * A single participant's upvote on a Q&amp;A question (US19.3.5) — at most one row per
 * {@code (questionId, participantId)}, enforced by a unique index so a repeated upvote surfaces as
 * a 409 rather than silently inflating the tally.
 */
@Entity
@Table(name = "session_qa_upvote", schema = "collaboratif")
public class SessionQaUpvote {

    /** Primary key generated by the database via UUID strategy — never client-supplied. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** The upvoted question; cascades on question deletion. */
    @Column(name = "question_id", nullable = false, updatable = false)
    private UUID questionId;

    /** The upvoting participant. */
    @Column(name = "participant_id", nullable = false, updatable = false)
    private UUID participantId;

    /** Timestamp of the upvote. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** No-arg constructor required by JPA. */
    protected SessionQaUpvote() {
    }

    /**
     * Creates a new upvote.
     *
     * @param questionId    the upvoted question's UUID
     * @param participantId the upvoting participant's UUID
     * @param now           the upvote timestamp
     */
    public SessionQaUpvote(final UUID questionId, final UUID participantId, final Instant now) {
        this.questionId = questionId;
        this.participantId = participantId;
        this.createdAt = now;
    }

    /** Sets {@code createdAt} before the first insert, when not already set. */
    @PrePersist
    public void prePersist() {
        if (this.createdAt == null) {
            this.createdAt = Instant.now();
        }
    }

    public UUID getId() {
        return id;
    }

    public UUID getQuestionId() {
        return questionId;
    }

    public UUID getParticipantId() {
        return participantId;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }
}
