package fr.pivot.collaboratif.session.qa;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;

import java.time.Instant;
import java.util.UUID;

/**
 * A single participant-submitted question in a Q&amp;A activity (US19.3.5) — one row per question,
 * upvoted independently by other participants (see {@link SessionQaUpvote}) and optionally marked
 * {@code answered} by the facilitator.
 *
 * <p>{@code participantId} always records the author for ownership/moderation, even when {@code
 * anonymous} is {@code true}: anonymity withholds the author's display name from other
 * participants (resolved at read time), it does not make the row un-attributable server-side.
 */
@Entity
@Table(name = "session_qa_question", schema = "collaboratif")
public class SessionQaQuestion {

    /** Primary key generated by the database via UUID strategy — never client-supplied. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Owning session; cascades on session deletion. */
    @Column(name = "session_id", nullable = false, updatable = false)
    private UUID sessionId;

    /** The authoring participant; retained for ownership even when {@link #anonymous}. */
    @Column(name = "participant_id", nullable = false, updatable = false)
    private UUID participantId;

    /** The raw question text, stored verbatim — escaping is a render-time (frontend) concern. */
    @Column(nullable = false, updatable = false, length = 500)
    private String text;

    /** Whether the author's display name must be withheld from other participants. */
    @Column(nullable = false, updatable = false)
    private boolean anonymous;

    /** Whether the facilitator has marked this question as answered. */
    @Column(nullable = false)
    private boolean answered;

    /** Creation timestamp, used as the stable tie-breaker for equal-upvote ordering. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** No-arg constructor required by JPA. */
    protected SessionQaQuestion() {
    }

    /**
     * Creates a new, unanswered question.
     *
     * @param sessionId     the owning session's UUID
     * @param participantId the authoring participant's UUID
     * @param text          the raw question text
     * @param anonymous     whether the author's name is withheld from other participants
     * @param now           the creation timestamp
     */
    public SessionQaQuestion(
            final UUID sessionId, final UUID participantId, final String text,
            final boolean anonymous, final Instant now) {
        this.sessionId = sessionId;
        this.participantId = participantId;
        this.text = text;
        this.anonymous = anonymous;
        this.answered = false;
        this.createdAt = now;
    }

    /** Sets {@code createdAt} before the first insert, when not already set. */
    @PrePersist
    public void prePersist() {
        if (this.createdAt == null) {
            this.createdAt = Instant.now();
        }
    }

    /** Marks this question as answered (facilitator action). */
    public void markAnswered() {
        this.answered = true;
    }

    public UUID getId() {
        return id;
    }

    public UUID getSessionId() {
        return sessionId;
    }

    public UUID getParticipantId() {
        return participantId;
    }

    public String getText() {
        return text;
    }

    public boolean isAnonymous() {
        return anonymous;
    }

    public boolean isAnswered() {
        return answered;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }
}
