package fr.pivot.agilite.retro.session;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;

import java.time.Instant;
import java.util.UUID;

/**
 * JPA entity representing a retrospective session (US20.1.1).
 *
 * <p>A session belongs to a single tenant and a single team, is facilitated by its creator, and
 * is joined by other participants via a globally unique {@code joinCode}. Only the DDL/entity
 * shape is delivered by this US — the real-time animation of phases (card submission, votes,
 * timers) is US20.1.2a/b/c's scope, built on top of this contract without redefining it.
 */
@Entity
@Table(name = "retro_sessions", schema = "agilite")
public class RetroSession {

    /** Primary key generated by the database via UUID strategy. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Owning tenant; used for multi-tenant isolation — never trusted from client input. */
    @Column(name = "tenant_id", nullable = false)
    private Long tenantId;

    /** Team this session belongs to ({@code public.teams.id}, exported by pivot-core-starter). */
    @Column(name = "team_id", nullable = false)
    private Long teamId;

    /** Human-readable session title; maximum 100 characters enforced at the API layer. */
    @Column(name = "title", nullable = false, length = 100)
    private String title;

    /** Retrospective format reference (US20.2.1 owns the detailed column catalogue). */
    @Enumerated(EnumType.STRING)
    @Column(name = "format", nullable = false, length = 30)
    private RetroFormat format;

    /**
     * Tenant-owned custom format reference (US20.2.1); populated iff {@link #format} is {@link
     * RetroFormat#CUSTOM}, {@code null} otherwise — enforced both by {@code
     * RetroSessionService}'s cross-field validation (for the 400/404 error codes) and, as a
     * structural guarantee, by the {@code chk_retro_sessions_custom_format_id} {@code CHECK}
     * constraint in {@code V1__schema_init.sql}.
     */
    @Column(name = "custom_format_id")
    private UUID customFormatId;

    /** Optional free-text reference to the sprint being retrospected. */
    @Column(name = "sprint_ref", length = 100)
    private String sprintRef;

    /** User who created the session and facilitates it ({@code public.users.id}). */
    @Column(name = "facilitator_user_id", nullable = false)
    private Long facilitatorUserId;

    /** Globally unique 6-character alphanumeric code used for frictionless, unauthenticated join. */
    @Column(name = "join_code", nullable = false, unique = true, length = 6)
    private String joinCode;

    /** Current lifecycle phase; defaults to {@link RetroPhase#CONTRIBUTION} on creation. */
    @Enumerated(EnumType.STRING)
    @Column(name = "current_phase", nullable = false, length = 20)
    private RetroPhase currentPhase = RetroPhase.CONTRIBUTION;

    /** Optional contribution-phase timer, in seconds; {@code null} means no timer (manual only). */
    @Column(name = "contribution_timer_seconds")
    private Integer contributionTimerSeconds;

    /** Optional vote-phase timer, in seconds; {@code null} means no timer (manual only). */
    @Column(name = "vote_timer_seconds")
    private Integer voteTimerSeconds;

    /** Optional action-phase timer, in seconds; {@code null} means no timer (manual only). */
    @Column(name = "action_timer_seconds")
    private Integer actionTimerSeconds;

    /** Number of dot-votes each participant may distribute; defaults to 3. */
    @Column(name = "vote_count_per_participant", nullable = false)
    private Integer voteCountPerParticipant = 3;

    /** Absolute expiry timestamp; defaults to 24h after creation (fixed in this first version). */
    @Column(name = "expires_at", nullable = false)
    private Instant expiresAt;

    /** Timestamp when the session was first persisted. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** Timestamp of the last update; refreshed automatically before every update. */
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /** No-arg constructor required by JPA. */
    protected RetroSession() {
    }

    /**
     * Full constructor for creating a new retro session with all required fields.
     *
     * @param tenantId                 owning tenant's {@code public.tenants.id}
     * @param teamId                   owning team's {@code public.teams.id}
     * @param title                    session title (max 100 chars)
     * @param format                   retrospective format reference
     * @param customFormatId           tenant-owned custom format id, non-{@code null} iff {@code
     *                                 format} is {@link RetroFormat#CUSTOM}
     * @param sprintRef                optional free-text sprint reference, may be {@code null}
     * @param facilitatorUserId        creating user's {@code public.users.id}
     * @param joinCode                 globally unique 6-character alphanumeric join code
     * @param contributionTimerSeconds optional contribution-phase timer in seconds
     * @param voteTimerSeconds         optional vote-phase timer in seconds
     * @param actionTimerSeconds       optional action-phase timer in seconds
     * @param voteCountPerParticipant  number of dot-votes per participant
     * @param expiresAt                absolute expiry timestamp
     * @param now                      timestamp used for both {@code createdAt} and {@code updatedAt}
     */
    public RetroSession(
            final Long tenantId,
            final Long teamId,
            final String title,
            final RetroFormat format,
            final UUID customFormatId,
            final String sprintRef,
            final Long facilitatorUserId,
            final String joinCode,
            final Integer contributionTimerSeconds,
            final Integer voteTimerSeconds,
            final Integer actionTimerSeconds,
            final Integer voteCountPerParticipant,
            final Instant expiresAt,
            final Instant now) {
        this.tenantId = tenantId;
        this.teamId = teamId;
        this.title = title;
        this.format = format;
        this.customFormatId = customFormatId;
        this.sprintRef = sprintRef;
        this.facilitatorUserId = facilitatorUserId;
        this.joinCode = joinCode;
        this.currentPhase = RetroPhase.CONTRIBUTION;
        this.contributionTimerSeconds = contributionTimerSeconds;
        this.voteTimerSeconds = voteTimerSeconds;
        this.actionTimerSeconds = actionTimerSeconds;
        this.voteCountPerParticipant = voteCountPerParticipant;
        this.expiresAt = expiresAt;
        this.createdAt = now;
        this.updatedAt = now;
    }

    /**
     * Sets {@code createdAt} and {@code updatedAt} to the current instant before the first
     * insert, when the fields have not already been set.
     */
    @PrePersist
    public void prePersist() {
        Instant now = Instant.now();
        if (this.createdAt == null) {
            this.createdAt = now;
        }
        if (this.updatedAt == null) {
            this.updatedAt = now;
        }
    }

    /**
     * Refreshes {@code updatedAt} to the current instant before every update.
     */
    @PreUpdate
    public void preUpdate() {
        this.updatedAt = Instant.now();
    }

    /**
     * Returns the session's unique identifier.
     *
     * @return the UUID
     */
    public UUID getId() {
        return id;
    }

    /**
     * Returns the tenant identifier.
     *
     * @return the owning tenant's {@code public.tenants.id}
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * Returns the team identifier.
     *
     * @return the owning team's {@code public.teams.id}
     */
    public Long getTeamId() {
        return teamId;
    }

    /**
     * Returns the session title.
     *
     * @return the title
     */
    public String getTitle() {
        return title;
    }

    /**
     * Returns the retrospective format.
     *
     * @return the format
     */
    public RetroFormat getFormat() {
        return format;
    }

    /**
     * Returns the tenant-owned custom format reference.
     *
     * @return the custom format's {@code agilite.retro_formats.id}, or {@code null} if {@link
     *     #format} is not {@link RetroFormat#CUSTOM}
     */
    public UUID getCustomFormatId() {
        return customFormatId;
    }

    /**
     * Returns the optional sprint reference.
     *
     * @return the sprint reference, or {@code null} if not provided
     */
    public String getSprintRef() {
        return sprintRef;
    }

    /**
     * Returns the facilitator user identifier.
     *
     * @return the facilitator's {@code public.users.id}
     */
    public Long getFacilitatorUserId() {
        return facilitatorUserId;
    }

    /**
     * Returns the globally unique join code.
     *
     * @return the 6-character alphanumeric join code
     */
    public String getJoinCode() {
        return joinCode;
    }

    /**
     * Returns the current lifecycle phase.
     *
     * @return the current phase
     */
    public RetroPhase getCurrentPhase() {
        return currentPhase;
    }

    /**
     * Sets the current lifecycle phase (real-time phase transitions are US20.1.2a/b/c's scope;
     * exposed here only so the contract is ready for them to build on).
     *
     * @param currentPhase the new phase
     */
    public void setCurrentPhase(final RetroPhase currentPhase) {
        this.currentPhase = currentPhase;
    }

    /**
     * Returns the optional contribution-phase timer.
     *
     * @return the timer in seconds, or {@code null} if unconfigured (manual closure only)
     */
    public Integer getContributionTimerSeconds() {
        return contributionTimerSeconds;
    }

    /**
     * Returns the optional vote-phase timer.
     *
     * @return the timer in seconds, or {@code null} if unconfigured (manual closure only)
     */
    public Integer getVoteTimerSeconds() {
        return voteTimerSeconds;
    }

    /**
     * Returns the optional action-phase timer.
     *
     * @return the timer in seconds, or {@code null} if unconfigured (manual closure only)
     */
    public Integer getActionTimerSeconds() {
        return actionTimerSeconds;
    }

    /**
     * Returns the number of dot-votes allotted per participant.
     *
     * @return the vote count per participant
     */
    public Integer getVoteCountPerParticipant() {
        return voteCountPerParticipant;
    }

    /**
     * Returns the absolute expiry timestamp.
     *
     * @return the expiresAt instant
     */
    public Instant getExpiresAt() {
        return expiresAt;
    }

    /**
     * Returns the creation timestamp.
     *
     * @return the createdAt instant
     */
    public Instant getCreatedAt() {
        return createdAt;
    }

    /**
     * Returns the last-updated timestamp.
     *
     * @return the updatedAt instant
     */
    public Instant getUpdatedAt() {
        return updatedAt;
    }
}
